### ISSUE TITLE
Mocking nested smart components with mocha

### ISSUE THREAD

**Issue by gothy** [rackt/redux#1000]
Hi,

I'm trying to test a "smart" connected component that has another connect'ed child inside.
Preparing a store for the test and providing it directly
```js
TestUtils.renderIntoDocument(
    <SmartParent store={store} />
);
```

and SmartParent has `<SmartChild />` in it that throws an exception like `Either wrap the root component in a <Provider>, or explicitly pass "store"...`

I know there's `rewire`, but I couldn't manage babel\webpack\karma\rewire setup easily, so I went with making the `SmartChild` dumb for now. But I really would like to figure testing thing out.
Any hints on this? Maybe some working examples?

Thanks!

**Comment by gaearon** [comment]
```js
TestUtils.renderIntoDocument(
  <Provider store={store}>
    <SmartParent />
  </Provider>
);
```

**Comment by gothy** [comment]
Thanks!

ps. That was easy... good sign I need to have some rest :)

**Comment by markerikson** [comment]
Followup observation: the wrapper components generated by `connect()` do support taking `store` as a prop, which seems like it would be an alternate approach to passing it in to a smart component.  Also, it looks like the Enzyme library supports defining the context for a component being tested.
