### ISSUE TITLE
Can we implement redux thunk middleware as wrapper around winston node module? 

### ISSUE THREAD

**Issue by Durgesh1986** [rackt/redux#1002]
Hi,

As we have a winston logging node module with good features can we write a wrapper around winston module which with which we can use it as a redux thunk middleware and use its features in store calls, action dispatchers etc.?

Thanks

**Comment by gaearon** [comment]
You can have more than one middleware. Thunk middleware is not related to logging, so I'm not sure why you're aiming to mix them. You can take inspiration from [redux-logger](https://github.com/fcomb/redux-logger) and modify it to work with winston instead, but there is no need to mix it with thunk middleware—both can be used together independently.
