### ISSUE TITLE
stage is no longer a valid option for the babelrc file

### ISSUE THREAD

**Issue by paltman** [rackt/redux#1004]
https://github.com/rackt/redux/blob/master/.babelrc#L2

This is no longer valid if using Babel 6.  It causes the entire build process to fail. What would be a work around?

https://github.com/babel/babel/issues/2572#issuecomment-152444952

**Comment by gaearon** [comment]
This is not an issue in Redux.
Why file this issue here? :wink:

We will update the examples to use Babel 6 when we are ready.
In the meantime please consult the Babel documentation and articles such as [this one](https://medium.com/@malyw/how-to-update-babel-5-x-6-x-d828c230ec53#.yqxukuzdk).

**Comment by paltman** [comment]
Well in order to get my project to compile I have to delete the babelrc file. I'll file an issue with Babel as well. Not sure how anything In the docs gets around the problem. Tried lots of things today.

**Comment by danmartinez101** [comment]
@paltman There is a preset for the stages now. 

See:
http://babeljs.io/docs/plugins/#presets
and
http://babeljs.io/docs/plugins/preset-stage-2/

**Comment by gaearon** [comment]
Please don't file new issues with Babel.
From [Babel 6 release notes](http://babeljs.io/blog/2015/10/29/6.0.0/):

>We also added presets for stages such as `babel-preset-stage-0` (used to be `stage: 0` in `.babelrc` in babel 5.x).

From the [article I linked to in my previous comment](https://medium.com/@malyw/how-to-update-babel-5-x-6-x-d828c230ec53#.yqxukuzdk):

>Change `optional` and `stage` params to `presets: [‘es2015’]` (or one/set of the presets in your `package.json`)

Googling will also give you some results:

<img width="804" alt="screen shot 2015-11-05 at 02 55 54" src="https://cloud.githubusercontent.com/assets/810438/10955991/d009a85a-8368-11e5-946b-c460e1bdab51.png">

It's always best to look for release notes and/or upgrade instructions and articles before filing issues to save maintainers time.

**Comment by gaearon** [comment]
In fact, the thread you linked to in the first comment provides a solution: https://github.com/babel/babel/issues/2572#issuecomment-152946955.

**Comment by paltman** [comment]
I had tried that originally but build only succeeded after deleting the file. Sorry for wasting people's time. I'll carry on.

**Comment by gaearon** [comment]
>I had tried that originally but build only succeeded after deleting the file.

That's weird. Presets should “just work” as long as you kill the `stage` option.
Either way, it's best to get Babel support in its [Slack community](https://slack.babeljs.io/).

**Comment by gaearon** [comment]
By the way I'm sorry if I sounded angry or arrogant in the previous comments.
It wasn't my intention, so please forgive me if it sounds this way.

I know Babel maintainers are having a hard time right now with all these breaking changes and people drowning them in “everything's in flames!” support requests, so that's why I suggest waiting a little bit before filing issues, and if something doesn't work, to look for new projects/boilerplates that already use Babel 6, and see how their setup is different from yours.

Happy coding!

**Comment by paltman** [comment]
Thanks!  Much appreciated.  As a maintainer myself to 50+ projects, I
understand the stress of staying on top of issues.  My apologies if I came
across badly as well.  I appreciate your help.

On Wed, Nov 4, 2015 at 6:07 PM, Dan Abramov <notifications@github.com>
wrote:

> By the way I'm sorry if I sounded angry or arrogant in the previous
> comments.
> It wasn't my intention, so please forgive me if it sounds this way.
>
> I know Babel maintainers are having a hard time right now with all these
> breaking changes and people drowning them in “everything's in flames!”
> support requests, so that's why I suggest waiting a little bit before
> filing issues, and if something doesn't work, to look for new
> projects/boilerplates that already use Babel 6, and see how their setup is
> different from yours.
>
> Happy coding!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rackt/redux/issues/1004#issuecomment-153910454>.
>



-- 
Patrick Altman
Nashville, TN

http://paltman.com

**Comment by paltman** [comment]
In case anyone else hits this issue like I did, the resolution to my problem had to do with my configuration in `webpack.config.js`. I needed to make sure and not parse the `node_modules` with my `babel-loader` (which I should have been doing anyway):

```javascript
            {
                test: /\.jsx?$/,
                loader: "babel-loader",
                include: [
                    path.resolve(__dirname, "src/js")
                ],
                query: {compact: false, presets: ['es2015', 'react', 'stage-0']}
            },
```

**Comment by gaearon** [comment]
Oh, good point. :+1:

**Comment by smazurov** [comment]
> I needed to make sure and not parse the `node_modules` with my `babel-loader`

@paltman thanks for the tip, that saved me quite a bit of time!
