### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by hnordt** [rackt/redux#1009]
Hello.

I've opened an issue on `ducks-modular-redux` about it, but I would like to open it here too because I would like to know the opinions from Redux developers.

1. Is a bad practice importing "third-party" actions inside a module? Example:

```js
// users.js

import { callAPI } from '../helpers';
import { showNotification } from './notifications';

export default function reducer(...) {}

export function login(username, password) {
  return dispatch => {
    return callAPI('post', '/auth/login', { username, password })
    .catch(() => dispatch(showNotification('error', 'Invalid username or password'));
  };
}
```

2. Is a bad practice handling "third-party" actions inside a reducer? Example:

```js
// notifications.js

import _ from 'lodash';

const initialState = { notifications: [] };

export default function reducer(state = initialState, action) {
  if (action.type === 'SHOW_NOTIFICATION') {
    return _.assign({}, state, {
      notifications: [...state.notifications, {
        id: new Date().toISOString(),
        type: action.payload.type,
        message: action.payload.message
      }]
    });
  }
  if (action.type === 'HIDE_NOTIFICATION') {
    return _.assign({}, state, {
      notifications: _.reject(state.notifications, { id: action.payload.id })
    });
  }
  // It's what I call "third-party" action, this action belongs to another module
  // Of course it should be an imported constant, but it's just an example
  if (action.type === 'LOGOUT_SUCCESS') {
    return initialState;
  }
  return state;
}

export function showNotification(type, message) {
  return { type: 'SHOW_NOTIFICATION', payload: { type, message } };
}

export function hideNotification(id) {
  return { type: 'HIDE_NOTIFICATION', payload: { id } };
}

```

**Comment by gaearon** [comment]
It looks just fine to me.
This is exactly why we don't encourage the “ducks” approach in the official docs (although we don't discourage it either—use what works best for you).
It should be very clear that having many reducers handle the same action is fine, and in fact **the very reason why you'd want to use Redux**—if you don't need to do this, you might as well not use actions to decouple state mutations from components, and instead use cursors to operate on the tree directly.

**Comment by hnordt** [comment]
Thank you for the quick answer ;)

**Comment by hnordt** [comment]
@gaearon https://github.com/erikras/ducks-modular-redux/issues/27 toughts?
