### ISSUE TITLE
Can't use immutable record as store

### ISSUE THREAD

**Issue by afraser** [rackt/redux#1017]
I'd really like to be able to extend Immutable records and use them in my reducers but redux says:

`DATA FETCHING ERROR:   TypeError: Reducers must return Immutable objects`

```
class CourseCollection extends Record({
  courses: new Map(),
  loading: false,
  loaded: false,
  error: null
}) {
  // Methods!
}

const initialState = new CourseCollection()

export default createReducer(initialState, {
  [actions.loadCourses](state, { courseId }) {
    return state.merge({
      loading: true,
      loaded: false
    })
  },
  ...
```

**Comment by gaearon** [comment]
There is no place in Redux source code that says this.
Please check your other dependencies.

**Comment by gaearon** [comment]
(Most likely `createReducer` is the culprit.)

**Comment by afraser** [comment]
ah, thank you! and apologies for the mixup.
