### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by JacquesBonet** [rackt/redux#1020]
Actions in Redux is an object with a mandatory type attribute.

ex : 
```javascript
{
  type: ADD_BIKE,
  text: 'Build my first Redux app'
}
```

```javascript
{
  type: ADD_CAR,
  text: 'Build my first Redux app'
}
```

What is your opinion to specify 'res' attribute as mandatory in action object. 'res' meaning resource.

This Design Patterns will permits to share action type. 
Ex : 
ADD_CAR and ADD_BIKE become ADD,
REMOVE_CAR and REMOVE_BIKE become REMOVE, 
UPDATE_XXX become UPDATE,
READ_XXX become READ etc ...

In order to distinguish the actions ADD, DELETE, UPDATE, READ between resources, we add the resource name on the action.

ex : 
```javascript
{
  type: ADD,
  res: 'TODO'
  text: 'Build my first Redux app'
}
```

```javascript{
  type: ADD,
  res: 'BIKE',
  text: 'Build my first Redux app'
}
```

This will permits to share easily the handling of common actions on the reducer, likes CRUD actions.
In contrarily, when its necessary to do a specific handling on a resource, we check the resource on the reducer.

ex : the Redux TodoMVC action become :

```javascript
import * as types from '../constants/ActionTypes'
import * as res from '../constants/TodoFilters'

export function addTodo(text) {
  return {
    type: types.ADD,
    res: res.TODOS,
    data: {
      completed: false,
      text: text
    }
  }
}

export function deleteTodo(id) {
  return { type: types.DELETE, res: res.TODOS, id }
}

export function editTodo(id, update) {
  return { type: types.UPDATE, res: res.TODOS, id, update}
}

export function completeTodo(id) {
  return { type: types.COMPLETE, res: res.TODOS, id }
}

export function completeAll() {
  return { type: types.COMPLETE_ALL, res: res.TODOS}
}

export function clearCompleted() {
  return { type: types.CLEAR_COMPLETED, res: res.TODOS }
}
```

And the reducer become

```javascript
export default function todos(state = initialState, action) {
    if (action.res === res.TODOS) {
        switch (action.type) {
            case 
            COMPLETE:
                return state.map(todo =>
                    todo.id === action.id ?
                        Object.assign({}, todo, {completed: !todo.completed}) :
                        todo
                )
            case
            COMPLETE_ALL:
                const areAllMarked = state.every(todo => todo.completed)
                return state.map(todo => Object.assign({}, todo, {
                    completed: !areAllMarked
                }))

            case
            CLEAR_COMPLETED:
                return state.filter(todo => todo.completed === false)
        }
    }
    return base( state, action)
}
```

base function is

```javascript
export default function base(state = [], action) {
    switch (action.type) {
        case ADD:
            return [
                Object.assign( {}, action.data, {id: state.reduce((maxId, elem) => Math.max(elem.id, maxId), -1) + 1}),
                ...state
            ]

        case DELETE:
            return state.filter(elem =>
                elem.id !== action.id
            )

        case UPDATE:
            return state.map(elem =>
                elem.id === action.id ?
                    Object.assign({}, elem, action.update) :
                    elem
            )

        default:
            return state
    }
}
```

Jacques

**Comment by cappslock** [comment]
Are you proposing this as a layer in user space or a modification to the core library? My two cents (not a project maintainer) this does not belong in the project core as it's highly domain specific. It's relatively trivial to add the functionality you're describing to your app with custom middleware, something like:

```
const requireResource = store => next => action {
  if (!action.resource) {
    throw new Error('resource is required in MyApp actions');
  }
  else {
    return next(action);
  }
}
```

**Comment by gaearon** [comment]
Actions don't have to be related to some "resource". Say, "show notification" or "route change" actions have nothing to do with resources.

This is fine as a convention in your specific project. And indeed you can write a custom middleware to enforce it. However we won't introduce something like this in the core.

The "type" is special because it's the way to tell actions apart. People often make typos when specifying actions, and requiring type to be present help cases where wrong constant is imported resulting in undefined type. Other than that, we don't want to enforce constraints on action structure.

**Comment by JacquesBonet** [comment]
Thks for your reply gaeron and cappslock.

I propose this modification, at first on the user space. 

gearon,

I don't agrea when you say "Actions don't have to be related to some "resource". 

Take a sample to illustrate its necessary to associate a resource to an action : 
I have a todos application which must handle two todos list : todos1 and todos2.
With your solution, I will have to duplicate the todos action to todos1 and todos2 action
Same for the reducers, todos reducer become todos1 and todos2.

Thats made a lot of duplicated code. with a code 90% similar. Not very good in my opinion.
And that will be worse if I'll need to have 3, 4, 5 ... todos

You say : "show notification" or "route change" actions have nothing to do with resources."
In "show notification", the resource is notification
In "route change", the resource is route.

Why don't apply the HATEOAS architecture principle to Redux. Both architecture follow already some common patterns, I not matching the missing parts.

Erikras resolve the multi components problem in https://github.com/erikras/multireducer
Its one solution. I think we can do better and less verbose.

I'll try to enhance my proposal which is not complete about this subject.

Best regards and thks a lot for you beautiful job.
