### ISSUE TITLE
redux 

### ISSUE THREAD

**Issue by tek0** [rackt/redux#1022]
@all can you guys tell me when redux can and cannot used in web app

**Comment by gaearon** [comment]
This is a very broad question. We're trying to use issue tracker more for feature requests and issues, and less for questions, so I suggest you to ask this on StackOverflow (assuming you can make it a tiny bit more specific).

In very broad terms,

**Comment by tek0** [comment]
@gaearon thank you :+1:

**Comment by tek0** [comment]
@gaearon is there any reason for cannot used in web app

**Comment by gaearon** [comment]
I don't know. If you find any, please come back and tell us. :wink:
