### ISSUE TITLE
rackt - redux build

### ISSUE THREAD

**Issue by gabrielmicko** [rackt/redux#1023]
Where can I find information about building example/counter code. Is it possible to run this with on any server?

**Comment by gabrielmicko** [comment]
I found babel-node buildAll.js, but It throws and error at spawnSync.

**Comment by ellbee** [comment]
Check out this page in the docs:

http://rackt.org/redux/docs/introduction/Examples.html

**Comment by ellbee** [comment]
I also recommend checking out the redux channel on [reactiflux](http://www.reactiflux.com). There are a bunch of friendly people hanging out there who can help you out.

**Comment by gabrielmicko** [comment]
Thanks @ellbee, but I was not able to find the answer to my question. I could run the app with node, but cannot build it for 'production' use.

**Comment by gabrielmicko** [comment]
The discussion page seems to be helpful.
