### ISSUE TITLE
Which Action Should Be Processed by Which Middleware?

### ISSUE THREAD

**Issue by tangrui** [rackt/redux#1025]
This is a very complicated question.

I have two middleware, one is the thunkMiddleware, and one is like below:

```javascript
export default function clientMiddleware(client) {
  return next => action => {
    // This means that the action is a function and with one argument, which is of client's type.
    if (typeof action === 'function' && action.length === 1) {
      return next(action(client))
    }
    next(action)
  }
}
```

And the action dispatching is like this:

```javascript
// action creator
function loadUserInfo(userId) {
  return (client) => {
    return {
      type: 'LOAD_USER_INFO',
      promise: client.fetch(userId) // this method should return a Promise
    }
  }
}

store.dispatch(loadUserInfo('tom'))
```

loadUserInfo('tom') returns a new function (It is the action here.) which carries one parameter, but my clientMiddleware and thunkMiddleware can both process this kind of action and cannot distinguish them. But the two middleware are mutually exclusive.

This is real an extreme case, my question is that, how can I have some graceful way to determine which middleware can process the action. Sometimes I may not have enough information.

**Comment by gaearon** [comment]
Indeed, these middleware are incompatible because they both attempt to “interpret” functions. Therefore you shouldn't mix them. It's probably wiser to embed the functionality of the thunk middleware into the client middleware. By this point you're customizing Redux pretty heavily so it's best to do this explicitly.

**Comment by tangrui** [comment]
This means that if I have installed many middleware in my project, I should pay attention to the compatibility of them.

But if I import other's store enhancer (I'd like to treat it as a black box.) and inject my own middleware, it's really hard for me to design the middleware. I have to know all of the action patterns the store enhancer's middleware chain consumed, and design my own carefully to prevent incompatibility.

Thank you! I'll think about it again.

**Comment by gaearon** [comment]
Third party store enhancers shouldn't inject their own middleware that changes behavior so significantly. It's the design problem with them—they are probably trying to do too much. 

Both middleware and especially store enhancers are powerful extension mechanisms. They should be used sparingly and with caution. They add indirection, and we assume the user is cautious to not add too much indirection.

**Comment by tangrui** [comment]
I see that, it's really a design problem.

Thank you!
