### ISSUE TITLE
Warn when code is uglified but not envified

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#1029]
From my series of tweets:

https://twitter.com/dan_abramov/status/665109454870982656
https://twitter.com/dan_abramov/status/665111615520563200
https://twitter.com/dan_abramov/status/665113061590761472
https://twitter.com/dan_abramov/status/665113349248704512

It's a common problem that people don't *know* they need to envify CommonJS builds. We need to help educate them about it, both in the docs and in the running code.

In the docs, we need to mention that you need tools like [loose-envify](https://github.com/zertosh/loose-envify) (Browserify) or `DefinePlugin` (Webpack) to set `process.env.NODE_ENV` to `'production'`. Otherwise you're running a slower development-only build of React, Redux, and other libraries.

In the source, we might want to try checking whether a local identifier is crushed. If it is, we're running in minified mode. If we're running in minified mode *and* `process.env.NODE_ENV` is something other than `'production'`, we should `console.error`, explain the mistake, and point to the relevant doc (a Medium article anyone?) about envifying.

**Comment by nettofarah** [comment]
@gaearon what do you mean by checking whether a local identifier is crushed?

**Comment by gaearon** [comment]
Superseded by #1075.
