### ISSUE TITLE
[React Native] Upgrading to Babel 6 and/or adding .babelrc to .npmignore

### ISSUE THREAD

**Issue by ide** [rackt/redux#1033]
React Native will be shipping with Babel 6 in about three weeks. One consequence of this is that Babel finds .babelrc in `node_modules/redux` and tries to consume it -- since Redux is using Babel 5's configuration, this causes Babel 6 to crash. The current verdict is that packages will have to exclude .babelrc when distributed through npm: https://github.com/facebook/react-native/issues/4062.

**Comment by gaearon** [comment]
Happy to accept a PR excluding it! (And maybe other useless files for good measure—except `src`, we want it there.)

**Comment by gaearon** [comment]
Also, hey, thanks for the heads up.

**Comment by ide** [comment]
OK - I wanted to make sure that excluding .babelrc was OK and you weren't shipping it next to src for some reason.

**Comment by gaearon** [comment]
Wondering how/whether this affects JSPM.
@timbur?

**Comment by ide** [comment]
I think you could make the argument that Babel shouldn't be processing .babelrc files under node_modules... imagine `npm linked` copies of Redux for example.

**Comment by gaearon** [comment]
Usually people turn that off with Webpack/Browserify, but React Native Packager doesn't seem to offer/favor ignoring third-party modules?

**Comment by ide** [comment]
RN is in a unique situation where the JS files under node_modules are ES7, so we want Babel to transform them. But we want Babel to use only the config options that are specified when calling `babel.transform(...)` plus the options in the root project's .babelrc file. So instead of `--ignore node_modules` we want (hypothetically) `--ignore-babelrc node_modules`.

**Comment by timbur** [comment]
AFAIK JSPM doesn't care about `.babelrc` at all but IIRC @guybedford was considering it or had it planned?  I don't remember exactly.  I've personally always kinda avoided using a `.babelrc` and most other dotfiles unless necessary.  Come to think of it I'll make a note to update my fork of `library-boilerplate` and remove it.

**Comment by gaearon** [comment]
Should be fixed in 3.0.5.
