### ISSUE TITLE
Should Redux be used with Relay?

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/redux#1036]
I've began learning about GraphQL, and wanted to implement in a react Application. The current way that I've found to use it with React is to use it with Relay. Should you use Relay with Redux? If so, how would you go about implementing Redux with Relay?

**Comment by gaearon** [comment]
I'm not sure it makes much sense. Both want to own the state and have different paradigms. Relay is cool so just use it directly.

See also #464.

**Comment by zjlovezj** [comment]
Sorry to update this closed thread, but I think it worth for those who want to use both Redux and Relay in the same application.

**Comment by AndrewHenderson** [comment]
@gaearon I have this question as well. I'll ask on Relay's issues, but if you have the time, I'd be interested in hearing your answer.

**Comment by rjdestigter** [comment]
http://beautifulcode.1stdibs.com/2016/09/07/reconcile-relay-redux/
