### ISSUE TITLE
Stateful components

### ISSUE THREAD

**Issue by boristian** [rackt/redux#1038]
Hello,
I'm working on an app with a [MQTT client](https://github.com/mqttjs/MQTT.js).

The client needs to connect to a MQTT broker via websocket on startup. Once connected, it stays connected the whole time, respectively reconnects on failure. The client also needs to react on actions (e.g. ```PUBLISH_MESSAGE```) but also create actions (e.g. ```MESSAGE_RECEIVED```).

What would be best practice to implement this kind of thing? Is implementing a middleware for this like supposed in #789 a good approach? Are there different solutions?

Greets,
boristian

**Comment by gaearon** [comment]
Middleware seems reasonable, but it's hard to say without seeing the code. Regardless, this is a question better asked on StackOverlow. Recently we've been trying to use it for questions, and reserve issue tracker for feature and bug discussions.
