### ISSUE TITLE
Redux integration

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/redux#1041]
Hello,

I'm currently working on a small lib that easily enables people to integrate GraphQL into your redux workflow. Using it would look like this:
```javascript
// Params it takes in
reachGraphQL(path, query, queryParams = {}, actionCreator)

// In use
reachGraphQL('localhost:3000/graphql',`{
    {
        users{
            name
        }
    }
}`, {}, getUsers);
```

It depends on the user to utilize `redux-thunk` when creating a store. Once it executes it dispatches the actionAction creator that was passed in. 

I wanted to ask if there is anything that comes to mind that I should consider that I may have over looked.

**Comment by gaearon** [comment]
>It depends on the user to utilize redux-thunk when creating a store.

This is generally not a very good idea. Userland extensions shouldn't rely on user to use a particular third-party middleware. Make your own middleware if you'd like, but don't force user to use Redux Thunk.

**Comment by kennetpostigo** [comment]
@gaearon, So I should integrate a middleware of my creation into the package? I just thought it would be easier to use one thats already made.

**Comment by gaearon** [comment]
User might already be using middleware that's incompatible with Redux Thunk.

**Comment by gaearon** [comment]
Anyway, it's hard to say more because the code snippet you posted does not fully describe the API you implement.

**Comment by kennetpostigo** [comment]
@gaearon Thank you for the feedback 😄!

**Comment by kennetpostigo** [comment]
Well, currently that is the only exposed part of the API its inner working are like so:

```javascript
import transport from ('./utils/transport.js');

function reachGraphQL (path, query, queryParams = {}, actionCreator) {
    return async dispatch => {
        try{
            let response = await transport(path, query, queryParams);
            dispatch(actionCreator(response.data));
        } catch (error) {
            console.log(error)
        }
    }
}
```
The transport import is using `isomorphic-fetch` in order to create the call.

**Comment by gaearon** [comment]
I still don't understand the API. Maybe we should wait for README for your project and then we can comment on it :-)

**Comment by kennetpostigo** [comment]
@gaearon will do.

**Comment by kennetpostigo** [comment]
@gaearon heres the repo, I just published the beta. http://www.github.com/kennetpostigo/react-reach

**Comment by gaearon** [comment]
I don't see where you rely on thunk middleware. You `dispatch(actionCreator(response.data))` but it doesn't matter whether this action creator is powered by Redux Thunk or just returns an action (or a Promise, or whatever middleware you use). So it seems fine to me.

**Comment by kennetpostigo** [comment]
Thank you :)
