### ISSUE TITLE
Help: Is it ok to have a middleware for authenticating a user.

### ISSUE THREAD

**Issue by Dindaleon** [rackt/redux#1044]
I am struggling to implement user authentication on the client side.

There are some pages and actions that only logged in users have access to. So, I need a way to handle this on the client side. 

I want to know what is the best way to implement this with Redux. I am tempted on implementing a redux middleware that decides whether the requested action is allowed by the user.

The middleware, would also check for an existing access token in the user's localstorage, and try to log the user in if it is valid. If the access token is invalid, send a refresh token to the server to request a new access token and log the user in, if it fails, redirect the user to a login page.

note: I am using react-router with the `onEnter` hook for restricted pages.

If there is a better approach, please let me know. I am still learning redux/flux.

**Comment by gusaiani** [comment]
+1 for a link to an example for the Redux way to authenticate users.
+10 if that includes Facebook login.

**Comment by gaearon** [comment]
Please ask this on StackOverflow so we can have a canonical answer to this.
This is a usage question, not a bug or feature request, and we try to utilize SO for this.
Thanks!

**Comment by gusaiani** [comment]
Did that.
http://stackoverflow.com/questions/33760732/best-practice-for-authenticating-user-with-redux?stw=2
