### ISSUE TITLE
Containers as Component's Children

### ISSUE THREAD

**Issue by hnordt** [rackt/redux#1047]
Hello.

It's actually not a Redux question, sorry if I shouldn't ask it here.

For components that need to interact with the DOM I like to create it as containers.
For example, I have a `<Grid />` stateless function component and a `<ResponsiveGridContainer />` class component that does things like `$(window).on('resize')`.

I want to know if it's a bad practice to use containers as component children, for example:

```jsx
const MyAwesomePanel = ({ title }) => (
  <div className="panel">
    <h1>{title}</h1>
    <div className="panel-body">
      <ResponsiveGridContainer>
        <ColumnA />
        <ColumnB />
      </ResponsiveGridContainer>
    </div>
  </div>
);
```

Thank you.

**Comment by gaearon** [comment]
I don't see any problem with this.
Please, refrain from asking usage questions (not even Redux in this case) on the Redux issue tracker.
Thanks!
