### ISSUE TITLE
Question: example clarification on why to use Action Creators

### ISSUE THREAD

**Issue by jcalfee** [rackt/redux#1053]
See addTodo.js .. http://rackt.org/redux/docs/recipes/ReducingBoilerplate.html  .. Look like addTodo calling  addTodoWithoutCheck could have been solved without boilerplate by testing the actions passed to `dispatch` trapping special actions(like limit applied to ADD_TODO ) .. 

Is there perhaps a better example or am I missing something?  This leads into many Action Creators so I want to understand why that is a good direction.

**Comment by gaearon** [comment]
I'm not sure what you mean. Do you propose to replace

```js
function addTodoWithoutCheck(text) {
  return {
    type: 'ADD_TODO',
    text
  }
}

export function addTodo(text) {
  // This form is allowed by Redux Thunk middleware
  // described below in “Async Action Creators” section.
  return function (dispatch, getState) {
    if (getState().todos.length === 3) {
      // Exit early
      return
    }

    dispatch(addTodoWithoutCheck(text))
  }
}
```

with

```js
export function addTodo(text) {
  return function (dispatch, getState) {
    if (getState().todos.length === 3) {
      return
    }

    dispatch({
      type: 'ADD_TODO',
      text
    })
  }
}
```

?

**Comment by gaearon** [comment]
Action creators are just functions that return actions. You can write an app without a single action creator and always call `dispatch` with inline action objects. The purpose of the docs and examples is to show how to write code that is easier to maintain in the longer term, and not to show the shortest way to write code. Nothing really prevents you from inlining the methods when you think it's better for readability.

**Comment by gaearon** [comment]
I'll close this as non-actionable, but please feel free to contribute to the docs (as PRs) if you find a way to explain you don't *have to* write action creators. Maybe just adding a paragraph in "Reducing Boilerplate" about it will suffice. Thanks!

**Comment by jcalfee** [comment]
No... I am suggesting that a generic pre-dispatch hook ( with the ability to keep or replace the action object ) could replace the Action Creators.   

In this case all the calling code would not need to change and the goals outlined in your example would still be accomplished.
