### ISSUE TITLE
Visual identity

### ISSUE THREAD

**Issue by unindented** [rackt/redux#1058]
I don't want to distract from more important issues but...

Redux has been as game-changing as React for me, and I want to talk about it at meetups and conferences. The problem is that I don't have a logo to go along the React one in my slides!

Does anybody think it'd be a good thing to design one?

**Comment by af** [comment]
There was a lot of discussion about this on #151, including a bunch of logo ideas. Doesn't look like any of them has gone forward at this point though.

**Comment by gaearon** [comment]
We'll have a logo eventually. Give it more time. ;-) I'll post in #151 if we settle on something.
