### ISSUE TITLE
Triggering a reducer after another reducer is done

### ISSUE THREAD

**Issue by scottellis64** [rackt/redux#1063]
Please forgive if this is not the right place to go, but I'm really close to a solution and I have an important architectural question in regards to reducer topology.  I'm implementing an ecommerce application that uses Redux both on the server and the client.  The client triggers redux via ReactJS actions, which selectively sends requests to the server via SocketIO.  I'm working on the concept of having a complete set of products that can be filtered.  I display filters along the left side of the products page, and as filters are selected, the products list shrinks, and vice versa as filters are unselected.  

The server knows the complete set of products and the complete set of filters.  Each product knows which filters it resolves to, but filters are independent entities that know nothing about products.  I currently have two reducers, one for products and one for filters.  Everything is simple for initial display, since all filters and all products are shown.  But as the user clicks on filters, I dispatch an action that indicates that a filter has been selected, which needs to narrow products, and this is where I am confused.

The filter reducer gets the SELECT_FILTER action, which updates a selected flag in the filter state.  This selected flag controls the state of the checkbox on the client page.  But now I want to trigger the product reducer which depends on the updated filter state.  

I could obviously handle the same action in both the filter and product reducers, but I am not aware of a way of chaining the two together.  I could hack something in my socket message handler--in other words, I could make this work, but I'm sure there is a way to do this.  For example, if I had the store's dispatcher in my reducer method, I could manually invoke the appropriate action, but again, I think there must be an aspect-oriented way to say, "call this reducer after this reducer has completed".  

This all sounds like the middleware solution, but if this is so, I don't know how to wire it up.

If I'm in the wrong place to ask such a question, I'm glad to take my question elsewhere.  Thanks for reading!

**Comment by sompylasar** [comment]
I'm interested in this type of questions, too. Facebook got waitFor for
this. Redux says it does not need waitFor.

This tutorial somehow resembles your case:
http://redux.js.org/docs/recipes/ComputingDerivedData.html

The concept as far as I understand is to compute data derived from multiple
stores at the view level.

Another way which was once suggested by Facebook devs is to merge the
stores into one store (into one reducer, in Redux terminology).

@geaeron, please share your thoughts! Thanks!

**Comment by scottellis64** [comment]
@sompylasar, I read that part of the Redux docs after submitting this, and though it seems like it may be the right thing, I'm still not making the full connection.  One problem is that the server application is not at all involved with React, as this is all server data manipulation.  I don't know how to attach this memoized selector to my store.  Thanks for your reply.  I'm considering how to apply the concept but as I said I'm not sure how to make it happen.  I might have to dig into Redux source code which will take some time.

**Comment by sompylasar** [comment]
@scottellis64 Do you do actual filtering server-side?

Here's how I see your case. You should have a `selectFilter` action creator that is called from the filter UI. It does the following:
1. dispatches `FILTERS_SELECTED` (handled by the `filters` store, setting the `selected` flag on the filter);
2. gets the current state of the `filters` store via `getState` (see redux-thunk);
3. dispatches `PRODUCTS_SEARCH_STARTED` via `dispatch` (handled by the `products` store to set the "loading" flag to display the spinner on the UI).
4. sends the server search request based on the obtained state;
5. from the request callbacks (asynchronously) dispatches `PRODUCTS_SEARCH_COMPLETE`, `PRODUCTS_SEARCH_ERROR` (handled by the `products` store to reset the "loading" flag and update the display list).

**Comment by scottellis64** [comment]
@sompylasar Yes I do filtering server-side.  I started with client-side filtering, but when I remove filters I need to access products that I no longer have in client state.  Right now I only have less than 50 products so I could store all my products in client state, but if I were to have a thousand or more, then server-side is the only practical option.

So maybe you are onto something with your strategy.  The client can react to the receipt of updated filter and emit the PRODUCTS_SEARCH_STARTED in response to the server reply of the FILTERS_SELECTED message instead of the server concerning itself over workflow.  I'll try this out.  Thanks.
