### ISSUE TITLE
Namespacing action creators

### ISSUE THREAD

**Issue by Zacqary** [rackt/redux#1064]
I've been able to easily create namespaced bits of my store (e.g. to track the state of a single UI element) using `combineReducers`:

```
let topLevelReducers = {
    aTopLevelReducer: function() { /* Reducer Function */ },
    namespacedReducers: Redux.combineReducers(objectOfReducersToNamespace)
}
```

It's not very easy to do this with action creators using the standard API, since `bindActionCreators` is expecting a flat object containing only functions.

It doesn't look like there's a way to get `bindActionCreators` to recursively bind any child objects it finds inside the object it's passed. Is there a way of doing this in the standard Redux API already?

**Comment by gaearon** [comment]
There's no standard way to do this. It might look like this:

```js
import { bindActionCreators } from 'redux';

export default function bindActionCreatorsDeep(actionCreators, dispatch) {
  return Object.keys(actionCreators).reduce((result, key) => {
    if (!actionCreators[key]) {
      return result;
    }
    switch (typeof actionCreators[key]) {
    case 'object':
      result[key] = bindActionCreatorsDeep(actionCreators[key], dispatch);
      break;
    case 'function':
      result[key] = bindActionCreators(actionCreators[key], dispatch);
      break;
    default:
      break;
    }
    return result;
  }, {});
}
```

We won't include this in core, but if you decide to publish it as a module, let us know!
