### ISSUE TITLE
[QUESTION] How to avoid recursion in redux?

### ISSUE THREAD

**Issue by max107** [rackt/redux#1066]
Problem:
Component receive props from router (params, query) and call `dispatch` from `componentWillMount` method. All good. But if we use filtering / sorting / pagination in component with new query string (example `/news/list?page=5`) new props passed to `componentWillReceiveProps` method - we catch recursion.
`router > componentWillMount -> dispatch -> componentWillReceiveProps -> dispatch ...`

How to avoid this situations?

Sorry for my bad english.

**Comment by gaearon** [comment]
```js
componentWillReceiveProps(nextProps) {
  if (nextProps.query.page !== this.props.query.page) { // only when necessary!
    this.props.fetchPage();
  }
}
```

**Comment by max107** [comment]
But i think it's a bad solution, because i have many params or dynamic params. Any other solution?

**Comment by jackson-sandland** [comment]
I'm curious about this as well. What is the best practice here?
