### ISSUE TITLE
Adding JWT authentication in redux.

### ISSUE THREAD

**Issue by nicolabortignon** [rackt/redux#1068]
I'm trying to add JWT authentication in a redux based app.

What I want to do is
1- login component send a login request to the API server endpoint
2- server API endpoint returns a token
3- I save the token in user's localStorage
4- all the API calls from now on will have in the header header: 'Autentication: Bearer $Token'

When user close the app, and open it again, I want to retrieve from the localStorage the token, and move
straight to point 4.
I thought a good idea is to add this check in the component that handle routes. 
Unfortunately there is some isomorphic problem. LocalStorage and store are not available on the server side. 
How would you implement something like this ?

**Comment by faergeek** [comment]
I use cookies for that, they're "isomorphic" :-)

**Comment by faergeek** [comment]
BTW, it's better to read cookies on server and save them to store as an initial state, I didn't found any other way which will have less problems with isomorphism.

**Comment by gihrig** [comment]
I will soon be facing the same situation, and while I haven't written that code yet, this is my thought:

1. Store the auth token in the state tree.
2. Persist the state tree to a local client-side db that syncs with the server-side db.
see: http://lokijs.org/
3. When client-side app starts, re-hydrate state from local db and begin sync process with server.

Seems this strategy should work well, unless it is possible for your app to log the user out server-side. That might create a situation where the user opens the app and they're logged in, then a few seconds later, after the local db syncs with the server db, they are suddenly logged out. I'll address that issue when and if, it become a problem.

**Comment by faergeek** [comment]
@gihrig it's pretty complicated for such little thing, don't you think?

**Comment by gihrig** [comment]
Considering that the state tree is already there and syncing, why not just use it? 

My app will have a state tree potentially containing thousands of items already, so adding an auth token seems the simplest thing to do. YMMV, of course.

**Comment by faergeek** [comment]
It's just your pretty specific case I think ;-)

**Comment by gihrig** [comment]
If Redux is to be the single source of truth for an app, wouldn't you consider logged-in vs logged-out to be a significant matter of application state?

**Comment by faergeek** [comment]
I'm talking about your state syncing things.

**Comment by faergeek** [comment]
Or you're talking about hydrating and such things?

**Comment by gihrig** [comment]
OP > When user close the app, and open it again, I want to retrieve from the localStorage the token, and move straight to point 4.

In my case I expect the client-side app to be usable without net access and sync when the server becomes available. So yes, this may be beyond the scope of the OP question.

**Comment by nicolabortignon** [comment]
Ok, moving from localStorage to Cookies sounds reasonable to support the isomorphism.

I was wondering if any of you can take me through baby steps in implementing the point 3 and 4.
Should I write the cookie in the response of the reducer that calls the login API,  right ? 
Where should I read the cookie back?

**Comment by faergeek** [comment]
I think it's better to write cookies in action creator, just after you get a response, then pass it to reducer, to persist it in state.

Then read cookie on server and set as an initial state which will be hydrated and sent back to the client.

All other reads go through the store.

**Comment by timdorr** [comment]
I would highly recommend not doing any of this client side. 

Your best bet is to put the token on a HttpOnly cookie from the server, which is set whenever you make an authentication request to the server. That will greatly reduce (even eliminate?) the chance of session hijacking from passing around this token in your client-side code.

**Comment by sompylasar** [comment]
Using cookies to authenticate requests from the browser-side is subject to XSS attacks. The victim's browser would be automatically authenticated by the cookie to perform requests on behalf of the victim. The cookies should be used to pass the token to the authorized JavaScript *that runs on the domain on which the cookie is set*.

https://en.wikipedia.org/wiki/Cross-site_request_forgery#Cookie-to-Header_Token
> Even though the csrf-token cookie will be automatically sent with the rogue request, the server will be still expecting a valid X-Csrf-Token header.

**Comment by timdorr** [comment]
CSRF protection is more of a server-side issue, though. You shouldn't blindly accept POST requests on your server. That's what the `X-Csrf-Token` header is referring to in that linked article. You need something that can only be obtained by code running in the same domain as the server.

For example, Rails has built in forgery protection where it emits a token alongside each form element. I know similar things exist in the Node world.

**Comment by sompylasar** [comment]
@timdorr, sure, it's server-side *plus browser-side*, and we are discussing exactly that here -- isomorphic aproach to browser-to-server request authentication.

**Comment by timdorr** [comment]
You don't deal with POST requests with universal rendering. Not on the initial render request, at least. Maybe in the preloading of state, however you handle that, but that's all internally-run code for the server request. So, at that point, it's best to use HttpOnly cookies.

**Comment by sompylasar** [comment]
@timdorr You deal with HTTP requests to the backend API when the app is running.

**Comment by Dattaya** [comment]
AFAIK, you protect your app from CSRF but expose to XSS because of unprotected cookie. CSFR can be easily prevented with the double-submit cookie solution. Also, JWT might not be the best approach in all cases because you can't revoke it.
