### ISSUE TITLE
Have any good way to implement multi promise control like Async?

### ISSUE THREAD

**Issue by hank7444** [rackt/redux#1070]
example1, I have 3 apis need to call, if they all resolve, return success and get me all data which return by those apis. If one of them are rejected, return failure to me.

example2, I have 2 apis need to call, if one of them resolve, return success and get me data.
If all of them are rejected, return failure to me.

Have any possible do such like these sophisticated async control on redux?

I have already used apiMiddleware, but it only use on 1 ajax call..

**Comment by just-boris** [comment]
It is not a Redux thing. You can do it with native promise

**example 1**
```
Promise.all([callAPI1(), callAPI2(), callAPI3()]).then(onSucces, onFailure)
```

**example 2**
```
Promise.race([callAPI1(), callAPI2(), callAPI3()]).then(onSucces, onFailure)
```

then you can wrap it code in action using https://github.com/gaearon/redux-thunk or https://github.com/acdlite/redux-promise and it will work

**Comment by hank7444** [comment]
@just-boris  thx!  I will try it~

**Comment by itsmepetrov** [comment]
Also, for combining async actions you can use [redux-combine-actions](https://github.com/itsmepetrov/redux-combine-actions).

**Comment by gaearon** [comment]
Yes, we suggest using middleware like [redux-thunk](https://github.com/gaearon/redux-thunk) or [redux-promise](https://github.com/acdlite/redux-promise) for this. You can then use `Promise.all` and other Promise composition functions. Note that you need to include a polyfill for Promises to use them safely—for example, you may use the polyfill that ships with Babel by importing `babel-core/polyfill`.
