### ISSUE TITLE
Add recipe on how to handle (expected) API errors

### ISSUE THREAD

**Issue by adamziel** [rackt/redux#1071]
In traditional flux implementation, I would do something like this:

```js
var PasswordReset = React.createClass({

    getInitialState() { return {error: null}; },

    componentWillMount() {
        PasswordResetStore.on('error', (e) => this.setState({error: e}))
    },

    render() {
        return (
            <div>
                {this.state.error?this.state.error:false}
                {this.renderForm()}
            </div>
        );
    }
});
```

This is nice because if the component is unmounted and then mounted again, the error info is gone.

Now, in redux I suspect it would be something along these lines:

```js
var PasswordReset = React.createClass({
    render() {
        return (
            <div>
                {this.props.error?this.props.error:false}
                {this.renderForm()}
            </div>
        );
    }
});

PasswordReset = connect(s=>({error: s.passwordReset.error}))(PasswordReset)
```

But in this case the error will remain visible after navigating away & back to PasswordReset.
So maybe something like this:

```js
var PasswordReset = React.createClass({

    getInitialState() { return {error: null}; },

    componentWillUpdate(newProps) {
        if(newProps.error && !this.props.error) { 
            this.setState({error: newProps.error}))
        }
    },

    render() {
        return (
            <div>
                {this.state.error?this.state.error:false}
                {this.renderForm()}
            </div>
        );
    }
});

PasswordReset = connect(s=>({error: s.passwordReset.error}))(PasswordReset)
```

But this is very boilerplate-y AND less readable than the regular flux implementation, I don't want to do this for every mid-lifecycle property of every component.

Are there any "idiomatic" solutions?

**Comment by gaearon** [comment]
No, introducing a local state and syncing it with props is definitely *not* the solution we recommend.

It really depends on your app. Can many components cause different errors? Is error a global concept for the whole app (e.g. causing a notification to appear at the very top), or are we talking about an error in a single form? If it's completely local, do you even need to show this error somewhere else other than inside that component? Do other components display similar errors?

If the error is *completely* local and there's no UI for it outside the component causing it, and there's no logic attached to handing it, you *may* make it completely local. If you use something like Redux Thunk middleware to handle async actions, you may return a Promise from the inner function, and call `setState` inside `catch` handler of that promise.

On the other hand, if it is likely you'll want to reuse this code and in the future add it to more components and maybe even add global UI for it (like an error notification above the screen) then it's best to keep state in Redux. In this case don't add local state. Just fire an action in `componentWillUnmount`, like `RESET_ERROR` passing the error type (a string constant) so only the relevant error gets reset. 

Finally check out "real world" example in Redux repo. It has error handling, and clicking on "x" inside a notification dismisses it. This is similar, but you want to dismiss on unmount.
