### ISSUE TITLE
Using other view systems apart from React?

### ISSUE THREAD

**Issue by kokujin** [rackt/redux#1072]
I'm sorry I put this here, I did not find a link to a forum.

From the site, "You can use Redux together with React, or with any other view library." Can someone point me to examples of Redux.js being used with other view libraries?

Thanks

**Comment by gihrig** [comment]
For Riot: http://riotjs.com/
see: https://github.com/ibloat/riot-redux-mixin
also: https://github.com/ibloat/riot-redux-sample

**Comment by af** [comment]
There's [a library](https://github.com/troch/deku-redux) that provides bindings for Deku as well.

**Comment by chentsulin** [comment]
https://github.com/rackt/redux/blob/master/docs/introduction/Ecosystem.md#bindings

**Comment by gaearon** [comment]
Closing, as we list the bindings we know [here](https://github.com/rackt/redux/blob/master/docs/introduction/Ecosystem.md#bindings).
