### ISSUE TITLE
import { compose, createStore } from 'redux' --> ReferenceError: [BABEL]

### ISSUE THREAD

**Issue by SkateFreak** [rackt/redux#1073]
when building bundle.js with webpack i get this error ``` ReferenceError: [BABEL]... ```
i used babel-loader with ``` 'react', 'es2015', 'stage-0' ``` as presets.

could it be that redux does not support babel 6 yet?

same happens with ``` import { Provider } from 'react-redux' ```
thanks

**Comment by SkateFreak** [comment]
update: managed to fix it by using these packages' versions:

```
"babel": "6.1.5",
"babel-core": "6.1.4",
"babel-loader": "6.0.1",
"babel-preset-es2015": "6.1.4",
"babel-preset-react": "6.1.4",
"babel-preset-stage-0": "6.1.2"
```

from this post:
https://github.com/babel/babel-loader/issues/147

**Comment by gaearon** [comment]
Thanks. Not our issue, so closing.
