### ISSUE TITLE
“Apps using Redux”

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#1078]
Per https://github.com/rackt/redux/pull/1076#issuecomment-160194012, let's assemble a list of apps (open source first, then closed source) that use Redux. #310 and https://github.com/xgrommx/awesome-redux can serve as starting points.

We want to have a screenshot and a brief description for each app. Something like http://backbonejs.org/#examples, maybe?

@kolodny volunteered to help assemble the initial list.

**Comment by levibuzolic** [comment]
This is a great idea! :clap:

**Comment by gaearon** [comment]
Closing as inactive. Maybe some other day :D

**Comment by kolodny** [comment]
sorry, I meant to get around to this :cry:

**Comment by gaearon** [comment]
Haha. If you do, just create a PR and let’s discuss there!
