### ISSUE TITLE
Super simple redux

### ISSUE THREAD

**Issue by yonatanmn** [rackt/redux#1083]
Hi guys, 
I've created a proposal/suggestion regarding flux API, suitable for redux too. I'd love to hear what people from redux community think about that, and maybe even someone will present a redux implementation.

https://github.com/yonatanmn/Super-Simple-Flux

Thanks !

**Comment by gaearon** [comment]
Redux was built based on experience and frustration with class/singleton-based Flux implementations with many Stores. This is the model you're suggesting. We don't find it compelling.

See also https://medium.com/@dan_abramov/the-evolution-of-flux-frameworks-6c16ad26bb31
