### ISSUE TITLE
I need a distro of redux, how do I do it?

### ISSUE THREAD

**Issue by lnaie** [rackt/redux#1090]
Hi,

I'm new to this build system, and unfortunately all those config files won't tell the secret. :) It has been overlooked somehow.

Thanks!

UPDATE:
I got this from a different thread, but maybe it's worth making the distro more visible:
`bower install https://cdnjs.cloudflare.com/ajax/libs/redux/3.0.4/redux.js`

**Comment by timdorr** [comment]
This is documented in the README.

> If you don’t yet use npm or a modern module bundler, and would rather prefer a single-file UMD build that makes Redux available as a global object, you can grab a pre-built version from cdnjs. We don’t recommend this approach for any serious application, as most of the libraries complementary to Redux are only available on npm.
