### ISSUE TITLE
Support to observe the relevant actions only

### ISSUE THREAD

**Issue by lnaie** [rackt/redux#1091]
Hi,

In current implementation, all the subscribers are notified when an action has been performed.
Any plans to support notification of the relevant subscribers only? The use-case would be: I would like to subscribe for the results of a particular action only. Or provide the dispatched action as a param in the subscription callback?

It may not be relevant to reactjs, but it will be useful to the other worlds.

Thanks

**Comment by just-boris** [comment]
As you can see in the [shopping-cart](https://github.com/rackt/redux/tree/master/examples/shopping-cart) example, you can the following reducer:

```
function addedIds(state, action) {
  switch (action.type) {
    case ADD_TO_CART:
      return handleCartUpdate(state, action);
    default:
      return state
  }
```

There is a lot of different actions, but you can change state only on some of them. If you get an action, which is not interesting for you, just skip add and go to `default` section.

Does it help for you?

**Comment by lnaie** [comment]
That is clear. is the reducer part of the flow.
The use-case being: In this particular page I would like to be notified only be the action x, it probably relates to the way subscribers are being handled, more exactly this part of dispatch():
'listeners.slice().forEach(listener => listener())
return action'

**Comment by just-boris** [comment]
This is the main concept of Redux. Listeners shouldn't know about recent action.
Here already was a discussion in https://github.com/rackt/redux/pull/622

If you want to handle specific action, just rely on *result* of that action, not the action itself

**Comment by lnaie** [comment]
Did help. Thanks! :)
