### ISSUE TITLE
Accessing store (to do getState()) inside method registered as a callback with store.subscribe()

### ISSUE THREAD

**Issue by nopmop** [rackt/redux#1093]
Hi guys, new to React & Redux here. I have the following code that I use to access a store through the context inside a React component, and bind a callback on it with store.subscribe()
```javascript
export class Menu extends React.Component {
	static contextTypes = {
		store: React.PropTypes.object
	}
	handleChange() { 
		console.log('context:', this.context); // <- THIS THROWS AN ERROR
	}
	componentDidMount(){
		let unscubscribe = this.context.store.subscribe(this.handleChange);
	}
[...]
}
```
However, after I register a handleChange() as callback I cannot access the context anymore inside the handleChange() method. Is that normal? I've tried using bind() for the callback without success too. Is there a better way to have components react on state changes? 

I've read the following on this topic but I don't quite understand what's the accepted conclusion: 
https://github.com/rackt/redux/issues/239
https://github.com/rackt/react-redux/issues/1#issuecomment-120729921

Thanks a lot.

**Comment by gaearon** [comment]
@nopmop You didn't bind the `handleChange` method so you don't get `this` there. You'll need to read about binding functions and how `this` works in JavaScript. This issue is neither specific to React nor to Redux. Finally you might want to check out React Redux library that does the subscription for you.

**Comment by nopmop** [comment]
Well true, I haven't done javascript in a while. 
I did it with a closure, however it doesn't seem right at all. I'll do more reading.
Thanks!

**Comment by travisperson** [comment]
@nopmop You will want to read this: https://facebook.github.io/react/docs/reusable-components.html#es6-classes

Check the 'No Autobinding' section.
