### ISSUE TITLE
dont/cant use npm

### ISSUE THREAD

**Issue by Eagllus** [rackt/redux#1099]
I noticed the git repo has no compiled / minified version of redux.

I don't/can't use npm so I want/need to download a compiled / minified version of redux.
you do have a src directory but I am missing a build directory with a prebuild version.

**Comment by kjbekkelund** [comment]
Check out UMD in https://github.com/rackt/redux#installation

**Comment by Eagllus** [comment]
Sorry I din't noticed that your documentation reference to cdnjs.
Thanks for the fast response!
