### ISSUE TITLE
Immutable initialState and combineReducer

### ISSUE THREAD

**Issue by Thunderbolt-sx** [rackt/redux#1100]
I am using Immutable Map as initialState for each of my sub-reducers. When directly applying combineReducer, there is error regarding with unexpected object in initialState. After searching a bit, I found libraries as [redux-immutable](https://github.com/gajus/redux-immutable) and [redux-immutablejs](https://github.com/indexiatech/redux-immutablejs) which replace default combineReducer. And it works great. However, according to author of of those libs [here](http://stackoverflow.com/questions/31892767/how-to-use-immutable-js-with-redux/31899857#31899857), it seems current (3.04) version of redux should support Immutable initialState natively. 

I just want to make sure it is supported, and no library is needed for current version. (As it obviously not work without libs in my situation)

**Comment by gaearon** [comment]
Redux has no special baked-in support for Immutable.js or any other libraries.

Nothing prevents you from initializing the root state **with a regular object whose values are Immutable Maps**. Then you can use the `combineReducers()` that ships with Redux, but use Immutable for subreducers. Alternatively you can use third-party Immutable-aware `combineReducers()`.

>When directly applying combineReducer, there is error regarding with unexpected object in initialState. 

This means you're passing something other than `{ a: <Map>, b: <Map> }` as the initial state of the store itself. If you use `combineReducers()` from Redux, **your root state object has to be plain object**.

**Comment by mike-hearn** [comment]
I know this is closed, I'd like to ask a follow-up question since I'm investigating this as well. If I use `combineReducers` with immutable sub-reducers, producing `{ a: <Map>, b: <Map> }` ... does that remove the benefits of having an immutable state? In other words, since the top level state is just a simple object, does that mean I can't use, for example, the `PureRenderMixin` that does a shallow diff check?

**Comment by Thunderbolt-sx** [comment]
I am using pure immutable object for the whole state tree with those libs for combineReducer, which works well for me.

**Comment by rclai** [comment]
So just to confirm, if you use the redux-immutable's `combineReducers`, you can achieve an app state store that is entirely a `Map({ a: Map(), b: Map() })` instead of `{ a: Map(), b: Map() }`?

**Comment by Thunderbolt-sx** [comment]
@rclai Since the code I write for getter is state.getIn(['a', 'rest']), which means root state should be Immutable Object
