### ISSUE TITLE
Designing apparently multiple level nested actions and batching them

### ISSUE THREAD

**Issue by ghosthoughts** [rackt/redux#1101]
The setup of a slice of my app is something like this:

An appliance gets its data from one or several dataSources. A user interacts with one or more appliances. Now, the dataSources provides realtime data, which is fetched per appliance at a regular interval and then displayed. So the structure can be displayed something as:

    User <----->  (Appliance1, Appliance2) <------> ((DataSource1, DataSource2), (DataSource1, DataSource3, DataSource4))

Note that the data sources may overlap. So its a two-tier-ish, overlapping design.

Currently, the actions are set up as follows (code is not 100% syntactically true - just a design question):

    ComponentContainer {
        ...

        componentDidMount() {
            this.setInterval(() => {
                this.props.appliances.forEach(appliance => dispatch(fetchApplianceRealtime(appliance))
            }, 4000))
        }
    }

    // in src/actions/appliance.js
    fetchApplianceRealtime(appliance) {
        return (dispatch, getState) => {
            fetchApplianceRealtimeInit(appliance) // I may want to toggle a flag here

            const promises = appliance.dataSources.map(ds => return dispatch(fetchDataSourceRealtime(ds)))
            Promise
                .all(promises)
                .then(() => {
                    dispatch(fetchApplianceRealtimeDone(appliance)
                }
                .catch(() => {
                    dispatch(fetchApplianceRealtimeFail(appliance)
                }
        }
    }

    // in src/actions/data-source.js
    fetchDataSourceRealtime(ds) {
        return (dispatch, getState) => {
            // No need for Init() action as data sources dont need their own fetching flag or something.
            return fetch(...)
                .then(resp => {
                    // normalize
                    return dispatch(fetchDataSourceRealtimeDone(ds, entities)
                })
                .catch(error => {
                    return dispatch(fetchDataSourceRealtimeFail(ds, error)
                })
        }
    }

So, is this a decent design? I strongly feel I am missing out on some feature here. Is the nesting of actions the best way, given the scenario? Can any other improvements be made here?

**Comment by gaearon** [comment]
Please ask usage questions on StackOverflow.
Since recently, we've only been using Github Issues for bug reports and feature requests.

**Comment by ghosthoughts** [comment]
My bad. I will post the question there. Thanks for the quick response.
