### ISSUE TITLE
Redux Framework & Customizer API

### ISSUE THREAD

**Issue by AndreaBazerla** [rackt/redux#1104]
Hi, I'm confused: can I use Redux Framework with Customizer API?

For example, I want to include in a section created with Redux a my custom button to execute a my script in JavaScript...but I don't want to pay any Redux's premium extensions, because code is free!

So I need to get the section's slug to include my custom button, it is possible?

(I've just see your campagne [here](https://ideas.reduxframework.com/campaigns/complete-customizer-integration/), is it in work in progress?)

Thanks

**Comment by ellbee** [comment]
Hi @AndreaBazerla, I think you may be in the wrong place. The Redux Framework project is here: https://github.com/reduxframework/redux-framework

**Comment by AndreaBazerla** [comment]
Lol, sorry

**Comment by ellbee** [comment]
No problem! :smile:
