### ISSUE TITLE
Question with User Authentication

### ISSUE THREAD

**Issue by SpencerCDixon** [rackt/redux#1108]
I was wondering how people normally handle User Authentication with redux?  I am using Redux Router and I have a backend rails API that handles user authentication via an auth token. 

When the user submits the sign in form the api will return the auth token to use for subsequent requests.  Right now I am just storing that in the single state tree and every time I dispatch an action that needs to make an API request that requires user authentication I use the (dispatch, getState) to fetch that auth token and then include it in the API request.  So: `getState().currentUser.auth_token`.  

I'm not sure if I'm approaching this in the right way.  Do some people use localStorage with Redux for user authentication to simulate like server side sessions?  Then every time an API request is made I just check the local storage for the auth token and if it's there the user is signed in?

Any tips or resources would be much appreciated.  I've looked at the real world example and the React Router auth example so far.  The React Router example seems to use localStorage which is why I'm curious if its the right path to take.  I noticed there is also a Redux Localstorage npm package.  If I do use local storage should I make sure to always dispatch actions when setting/updating the storage??

**Comment by sompylasar** [comment]
Refs #1068 , look at https://github.com/erikras/react-redux-universal-hot-example

**Comment by gaearon** [comment]
This is a question that is much better suited for StackOverflow.
Please create it there and I'll be happy to share it so we can get great answers.

**Comment by SpencerCDixon** [comment]
Posted a SO post [here](http://stackoverflow.com/questions/34160157/handling-user-authentication-via-redux-and-redux-router)
