### ISSUE TITLE
Help understanding when to use provide /and or connect

### ISSUE THREAD

**Issue by toranb** [rackt/redux#1112]
I'm new to redux (literally - 25 minutes into the docs). 

http://rackt.org/redux/docs/basics/UsageWithReact.html

Along w/ some of the usage reading I came across this issue https://github.com/rackt/redux/issues/136 and found an interesting decorator "@provide(redux)"

As I continued through this issue I found a mention to "real-world" in the examples. I went over to check that out assuming "provide" would show up but instead I found connect at the bottom (as I found in the usage guide).

```js
// Wrap the component to inject dispatch and state into it
export default connect(select)(App)
```

Where can I read more about provide? Does it replace the requirement for connect as shown above or no? Thanks for maintaining this great library (and the documentation). I've personally found the docs really useful/helpful/all of the above :)

**Comment by gaearon** [comment]
This should probably be a StackOverflow question, not a Github issue.
Especially considering that it's about React Redux library, not Redux itself.

>Along w/ some of the usage reading I came across this issue #136 and found an interesting decorator "@provide(redux)"

It's long gone. There is no `provide()` in React Redux now. Instead, there is a `<Provider>` component.  Please see [its documentation](https://github.com/rackt/react-redux/blob/master/docs/api.md#provider-store).

>Does it replace the requirement for connect as shown above or no?

No, `<Provider>` is a completely different thing from `connect()`. `connect()` generates a container component, but it needs `store` as a prop. It's cumbersome to pass the `store` down to every container component. If you wrap your root component in a `<Provider>` (just once!) then there is no need to pass the `store` down—`connect()`ed components will read `store` from React context.

Please see:

http://stackoverflow.com/questions/34006959/single-provider-for-many-components/34007150#34007150
https://github.com/rackt/react-redux/blob/master/docs/api.md#provider-store

https://egghead.io/lessons/javascript-redux-passing-the-store-down-explicitly-via-props?series=getting-started-with-redux
https://egghead.io/lessons/javascript-redux-passing-the-store-down-implicitly-via-context?series=getting-started-with-redux
https://egghead.io/lessons/javascript-redux-passing-the-store-down-with-provider-from-react-redux?series=getting-started-with-redux

**Comment by toranb** [comment]
@gaearon ah totally legit (sorry for the open issue here). Also -thanks for the blazing fast reply -you are officially my new OSS hero :)
