### ISSUE TITLE
How to export a redux component as a lib to be used by other projects?

### ISSUE THREAD

**Issue by agile116** [rackt/redux#1114]
Hi All,

I have a requirement to export my navbar to a lib and to be used by other projects. How can I do it in redux structured application? Currently the navbar is highly integrated with redux,react-router. If it was exported as a lib, how do the menu click fits with react router routing?

**Comment by gaearon** [comment]
This is a very broad question and it's impossible to answer it without knowing specifics of how you currently implemented it, and how you want it to be used from the other projects.

We also discourage questions in the repo issues. Please create a StackOverflow question instead. Feel free to link to it here.
