### ISSUE TITLE
React native 0.16.0 packager hangs when you require redux

### ISSUE THREAD

**Issue by anshul** [rackt/redux#1115]
The packager transform gets stuck at 97% forever.  This may be because the es6 environment on react native 0.16.0 has changed.

To replicate,  create a fresh 0.16.0 project and require redux in `index.android.js`

**Comment by gaearon** [comment]
Why do you file this in Redux?
Nothing changed on our side.
Must be a packager issue?

**Comment by gaearon** [comment]
If this is caused by `.babelrc` that used to be in the NPM package I can release a patch release that removes it. The build we have always been shipping is ES5. Would this help?

**Comment by anshul** [comment]
Errr... Sorry.  Was only happening with redux and no other libraries and I really don't understand how the packager works.  Reported to the official repo.

https://productpains.com/post/react-native/packager-hangs-indefinitely-on-requireredux-in-v0160/
https://github.com/facebook/react-native/issues/4674

**Comment by holyxiaoxin** [comment]
@anshul I'm getting this error too. It doesn't get stuck only for redux but for other packages as well. This problem only started after i upgraded it to react-native v0.16. I also tried a fresh install of v0.16.

Any progress?

http://stackoverflow.com/questions/34169461/react-native-v0-16-stuck-at-transforming-when-using-external-packages
