### ISSUE TITLE
Hot module replacement not working on the todos example

### ISSUE THREAD

**Issue by andrerpena** [rackt/redux#1121]
I'm using the `todos` example app as a quick boilerplate for some Redux testing and I found out that the hot module replacement isn't working.

I'm trying to modify the `Header` component.

![image](https://i.imgur.com/fhsSS2l.png)

**Comment by ellbee** [comment]
Hi @andrerpena, I'm not able to reproduce the problem, it is working as expected for me. Can you provide further details?

**Comment by gaearon** [comment]
Please provide a way to reproduce.
