### ISSUE TITLE
Sample with functional stateless components

### ISSUE THREAD

**Issue by urbanvikingr** [rackt/redux#1128]
Hi,
I built the todo app from the video series Getting Started with Redux on egghead.io.
It can be seen here https://github.com/urbanvikingr/todo.
Let me know if you want to include it in the samples. If so, I'll add tests and update to latest babel.
Best, Dan

**Comment by gaearon** [comment]
The “Usage with React” guide needs rewriting to match my Egghead tutorial content more closely.
Would you like to work on that?

**Comment by urbanvikingr** [comment]
I can give it a try :)

**Comment by urbanvikingr** [comment]
@gaearon Please would you like code review this https://github.com/urbanvikingr/todo as I will update the documentation based on this.

Please notice that there are 3 containers instead of one top-level.

**Comment by timdorr** [comment]
Happening in #1285! :smile:
