### ISSUE TITLE
Todos example in the docs (and todos-with-undo) should use IDs instead of indexes

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#1129]
The problem is well described here: https://github.com/rackt/redux/pull/795.

I didn't want that particular fix, so I closed the PR.
The fix I want is to use IDs instead of indexes, just like I do in [Egghead series](https://egghead.io/series/getting-started-with-redux).

I'd happily merge a PR doing that.

**Comment by arjunblj** [comment]
Happy to take a stab at this -- looking into it now.

**Comment by gaearon** [comment]
You can take a look at my Egghead series for how I would've done it today:
https://egghead.io/series/getting-started-with-redux

**Comment by gaearon** [comment]
Fixed in all examples now.
