### ISSUE TITLE
redux-in-chinese

### ISSUE THREAD

**Issue by camsong** [rackt/redux#1130]
Can you mention [redux-in-chinese](https://github.com/camsong/redux-in-chinese) somewhere as an elaborate Chinese translation of Redux documentation? We have a translation group to proofread and sync with this consistently, it also includes react-redux translation inside.

**Comment by gaearon** [comment]
Send a PR adding a "Translations" section to the "Ecosystem" doc?

**Comment by camsong** [comment]
sure, will do

**Comment by camsong** [comment]
close by https://github.com/rackt/redux/pull/1131
