### ISSUE TITLE
Question on combineReducers depends on process.env.NODE_ENV  'production' 

### ISSUE THREAD

**Issue by iroy2000** [rackt/redux#1132]
I'm looking at the redux source code and find this line

https://github.com/rackt/redux/blob/master/src/utils/combineReducers.js#L128

So looks like it is assuming that people will always use the same string `production` as node argument when they deploy to production?

**Comment by gaearon** [comment]
Yes. This is a very common idiom, and React does it too. Since most Redux projects also use React it makes sense for us to do the same instead of adopting some other convention that isn't as popular.

**Comment by gaearon** [comment]
Also it's not about *deploying* to production. You need to use `envify` (Browserify) or `DefinePlugin` (Webpack) when *bundling* your code.

**Comment by iroy2000** [comment]
Yes, I meant `bundling` not `deploying` to production.  Thanks for quick response.
