### ISSUE TITLE
Issues with connect()ing from top-level container to redux store in RN

### ISSUE THREAD

**Issue by isikfsc** [rackt/redux#1134]
I have a sample [app on rnplay](https://rnplay.org/apps/SSfloA) and I cannot reach my store inside a component connected to my redux store by `connect()` via `this.props`.

on line 320, I have created my redux store with a mock trivial reducer and an an initial state like:
`
var store = createStore(reducer, {splashViewedCount: 0, loggedIn: false,}); 
`
On line 308, I had then connected my component named `App` to it by `connect()` with a trivial selector:
`
function select(state){
	return state;
};
`
`
connect(select)(App); 
`
On line 261,  I cannot have the state inside my store from inside my component `App` via `this.props`:
`
const {splashViewedCount, loggedIn,} = this.props;
`
and in subsequent lines of conditional code.
On line 281, For debug purposes, I have put those in a component to be rendered when news1 or news2 is clicked. In the coming rendered screen I have only the state from `store.getState()` (it is `{splashViewedCount: 0, loggedIn: false,}` ), but not from `this.props` (it is `{}`).

Is there something I just mix?

**Comment by gaearon** [comment]
`connect()` is not a function with a side effect.
It *returns* a connected component.

So 

```js
connect(select)(App);
```

should be 

```js
App = connect(select)(App);
```
