### ISSUE TITLE
Pseudo-local state question (yet another)

### ISSUE THREAD

**Issue by nopmop** [rackt/redux#1136]
Hello everyone.
I have read https://github.com/rackt/redux/issues/159 but I just can't figure it out :(  I have, on screen, a lot of instances of the same component and I need them to have a state that is a union of a global store & a local state (and to update based on changes of either one of them). 
How can I achieve this?

Thanks.

**Comment by gaearon** [comment]
This is a vague question, so it's hard to answer.
Please create a question on StackOverflow and provide example code for some context.
