### ISSUE TITLE
Recommendations for isomorphic actions

### ISSUE THREAD

**Issue by calebmer** [rackt/redux#1140]
Is there any defined pattern or recommendations for implementing actions which can be sent between the client and the server? In the interest of progressive enhancement, I'd like to be able to render my page on the server, then have a custom button React component which outputs HTML which looks like the following:

```html
<form method="post" action="/dispatch">
  <button type="submit">Star Person!</button>
  <input type="hidden" name="action" value="{\"type\":\"STAR\",\"starGroupId\":2,\"agentId\":5}"/>
</form>
```

…or maybe even:

```html
<form method="post" action="/dispatch">
  <button type="submit">Star Person!</button>
  <input type="hidden" name="type" value="STAR"/>
  <input type="hidden" name="starGroupId" value="2"/>
  <input type="hidden" name="agentId" value="5"/>
</form>
```

…so that actual forms could also work under this system.

The goal is for the action to be sent to the server where it is dispatched on the store used to render the page. However, this requires that an action object is actually a description of the actual “action” which needs to occur. All the examples in the documentation show actions which are completely self descriptive, and all dispatched within one process.

Is it possible/a good idea to add specific action handling? So for example, maybe I add a middleware which takes an object which looks like:

```js
{
  [STAR]: action => dispatch => Promise.resolve(…).then(() => dispatch(…))
}
```

Where the key would be the action to handle and the value would be a function which takes the action object as a parameter and dispatches that functions return value (the above example would require the `redux-thunk` module). I know it would require standardizing the action `type` key convention, so maybe are there other ideas?

I think progressive enhancement is a value we should all strive for (even if we can never achieve it) and Redux + React provide an amazing system which has the potential to facilitate well developed progressively enhanced websites. So, for discussion sake, here are some of my specific questions:

1. Do you think advanced progressive enhancement in a React/Redux system is possible? (I do)
2. What do you think about this proposal?
3. Would this make a good `rackt` module? (likely containing a server and client component)
4. Any other ideas on facilitating progressive enhancement?

**Comment by gaearon** [comment]
Yeah I guess you can do this. Feel free to experiment!
We don't plan to add any new Redux-related modules to `rackt` but please publish your findings :-).

**Comment by calebmer** [comment]
I've been doing some expirementing for a while now and opened this issue to hear other people's ideas. Is there a chat or something I could use to discuss this with some people?

**Comment by gaearon** [comment]
Yeah, we link to the [Discord chat](https://discord.gg/0ZcbPKXt5bZ6au5t) from the front page.

I'm happy to reopen this when there is some code example to discuss. Experience shows that purely theoretical discussions don't help anyone and just generate noise in notifications without jumping to any sort of conclusion. :-)

**Comment by calebmer** [comment]
Ok, most of my experiences have been non-redux specific. I'll message back when I have something.
