### ISSUE TITLE
Fetching data before performing route transitions

### ISSUE THREAD

**Issue by inchr** [rackt/redux#1141]
From the docs I've read this:

> As if this wasn’t bad enough, consider the new requirements becoming common in front-end product development. As developers, we are expected to handle optimistic updates, server-side rendering, fetching data before performing route transitions, and so on. We find ourselves trying to manage a complexity that we have never had to deal with before, and we inevitably ask the question: is it time to give up? The answer is no.

This is pretty interesting...but I've looked for all the docs and examples and I've not found any example about fetching data before performing a route transitions...how I should do it ? should I do a sync ajax call on the ```onEnter``` react-router ? (but then I don't understand why this was written in the redux app)

**Comment by gaearon** [comment]
Please ask this as a StackOverflow question.
We use the issues for discussing bugs and feature requests.

**Comment by gaearon** [comment]
http://stackoverflow.com/questions/32846337/how-to-fetch-the-new-data-in-response-to-react-router-change-with-redux

**Comment by inchr** [comment]
@gaearon sorry and thanks.
