### ISSUE TITLE
Poll: Which routing library should we use in examples and documentation?

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#1145]
I'm running a poll on Twitter about which routing library you prefer for your Redux apps.

We need to use something for Real World example, but people have been having some issues with Redux Router, and I was wondering whether you think we should recommend Redux Simple Router instead.

**Please [vote in the poll!](https://twitter.com/dan_abramov/status/676918906729144325)**
**You can also [read this thread](https://github.com/rackt/redux-router/issues/172) for more context.**

Feedback on all of these libraries is welcome in this issue, especially if you switched from one to another and can share the experience.

(Please stay polite ;-)

**Comment by acdlite** [comment]
I say let's go with Redux Simple Router. @jlongster is committed to maintaining it and it Just Works, whereas in retrospect I think Redux Router was misguided — I've come to realize that the only way to accomplish what I set out to do is to go lower-level into the router itself. (I'm experimenting with that here: https://github.com/acdlite/router **Not a library, just an experiment I'm using in a side project**)

**Comment by davezuko** [comment]
:+1: for redux-simple-router, it doesn't try to reinvent the wheel and encourages the use of react-router's original API which most people are already familiar with. Also, it's _way_ easier to grok what it's doing by reading the source since the added surface area is so minimal.

**Comment by sai-prasanna** [comment]
redux-simple-router (y)

**Comment by smashercosmo** [comment]
Using redux-simple-router in examples means that you encourage people to use it in their apps. While it's absolutely unnecessary. In our app we simply inject history object into action creators along with dispatch and getState and that's absolutely enough for 99% of cases. So I would go for just plain react-router.

**Comment by dlong500** [comment]
@smashercosmo redux-simple-router is not complex at all (a little over 100 lines of code) and doesn't abstract away react-router like redux-router does, so I don't really see the problem.  Maybe your solution of injecting history into action creators works for you but I don't think it is really more simple.  Is it possible your comments were directed toward the older redux-router module?

**Comment by kurtharriger** [comment]
One thing I don't like about redux-router is that it adds non-serializable objects to the state. 
This makes it more difficult to serialize and restore the application state with middleware such as https://github.com/elgerlambert/redux-localstorage.  

It also doesn't work with devtools (I've not looked into why, but perhaps due to non-serializable state.)

**Comment by gaearon** [comment]
We are using react-router-redux (aka redux-simple-router) now.
It has more community support and better support for server rendering.

https://github.com/rackt/redux/pull/1276
