### ISSUE TITLE
webpack -p 的时候出错

### ISSUE THREAD

**Issue by hqxluoyang** [rackt/redux#1148]
当用 webpack -p 时页面加载出现问题  “uncaught SyntaxError: Unexpected token <”

**Comment by chentsulin** [comment]
Please use English in issue tracker 在這裡請使用英文
-----
This should be a your routing issue, so webpack serve html file as js file. Nothing is related to redux.
這是應該路由 (routing) 問題導致 js 載入到 html 檔案，跟 redux 無關

**Comment by hbrls** [comment]
I guess you forgot to install a right `jsx` loader.

**Comment by gaearon** [comment]
You probably forgot to enable Babel loader for JS or JSX files in your Webpack configuration.
