### ISSUE TITLE
real-world example: middleware is not applied to browser back

### ISSUE THREAD

**Issue by timaschew** [rackt/redux#1149]
I realized that clicking on a `<Link>` and navigating via browser back and forward does not trigger the custom middleware in __middleware/api.js__.

So it will not be called for actions like `@@reduxReactRouter/routerDidChange`.
I would like to interact also on these kind of actions.

How can I achieve this? 
Using `store.subscribe` doesn't give me the action.
Using a reducer for this doesn't give me access to the whole state.

**Comment by gaearon** [comment]
Why should it trigger that middleware? That middleware has an explicit check for whether action object has a special field on it. If you write a custom middleware without this check, you'll intercept all actions.

**Comment by timaschew** [comment]
No it doesn't.  I added a conole.log at the very first line and it doesn't output it in the described cases.

**Comment by gaearon** [comment]
Please show how you apply the middleware and the Redux Router. Maybe you apply middleware before it, and thus middleware doesn't see the actions it generates.

**Comment by gaearon** [comment]
In particular, in real world example you can see that we apply middleware twice exactly for this reason. You want your middleware after the router so that it sees its actions, just like we currently have the logger there.

**Comment by timaschew** [comment]
Thanks, the order was wrong.
So this way it's working

_configureStore.dev.js_
```
const finalCreateStore = compose(
  applyMiddleware(thunk, api),
  reduxReactRouter({ routes, createHistory }),
  applyMiddleware(createLogger()),
  applyMiddleware(foobar),
  DevTools.instrument()
)(createStore)
```

_foobar.js_
```
export default store => next => action => {
  // do stuff
  return next(action)
}
```

**Comment by gaearon** [comment]
It should work this way too:

```js
  applyMiddleware(thunk, api),
  reduxReactRouter({ routes, createHistory }),
  applyMiddleware(foobar, createLogger()), // do your stuff, then log
  DevTools.instrument()
)(createStore)
```

**Comment by timaschew** [comment]
Yep, this looks better :)
