### ISSUE TITLE
Use combineReducers can't pass state to the smart component

### ISSUE THREAD

**Issue by leaven** [rackt/redux#1150]
I defined a smart component named `Main` as below:

```
/**
 * @des 详情页主入口组件
 */
import Map from '../components/map/map.jsx';
import ToolBar from '../components/toolbar/toolbar.jsx';
import React from 'react';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import * as Actions from '../actions/actions.es6';

class Main extends React.Component {
	render() {
		console.log(this.props);
		let {getLineList, lineList} = this.props;
		return (
			<div className="map-main">
				<Map />
				<ToolBar lineList = {lineList} actions={getLineList}/>
			</div>
		);
	}
}

//将state转化为props传给主入口组件
function mapStateToProps(state) {
	return {
		lineList: state.lineList
	}
}

//将actions转化为props传给主入口组件
function mapDispatchToProps(dispatch) {
  	let actions = bindActionCreators(Actions, dispatch);
	return actions;
}

let App = connect(
    mapStateToProps,
    mapDispatchToProps
)(Main);

export default App;
```

And a reducer named `line` likes this,

```
/**
 * @des reducer接收从action过来的type值，根据type值去更新state对象
 */
import * as types from '../constants/actionTypes.es6';

const initState = {
	personPos: {},
	busPos: {},
	lineList: []
}


export default function getLineList(state=initState, action) {
	switch(action.type) {
		case types.GET_LINE_LIST: 
			return Object.assign({}, state, action.data);
		default:
			return state;
	}
}
```

However，when I use `combineReducers` to combine `line reducer` instead of importing the `line reducer` directly, the `Main Component` can't get the  props of `lineList`, the `lineList` in  `Main` is **undefined**. If I use `line` as rootReducer directly, it comes to be right.
		 
	import { combineReducers } from 'redux';
	import  line from './line.es6';	
	export default combineReducers({
		line
	});
What's the reason?

**Comment by gaearon** [comment]
`combineReducers` gives the state keys the same names as the object you pass to it. You passed `line` so it will be available as `state.line` in `mapStateToProps`. However you're reading something else there. Please consult documentation for `combineReducers()`.

Also, please ask questions on StackOverflow rather than on the issue tracker.

**Comment by leaven** [comment]
Thank you
