### ISSUE TITLE
Should you not return a copy of the state?

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [rackt/redux#1166]
Apologise if this has been discussed before. If redux promotes pure functions and a strict directional flow with actions only having the ability to manipulate the state of your app, would it not make sense to return a copy of the stores state?

So instead of the following:

    function getState() {
      return currentState;
    }

We would have the following:

    function getState() {
      return Object.assign({}, currentState);
    }

This would prevent the following:

    store.getState().someObj.someValue = "Changing the state of the application";

Therefore you cannot change the state of the app without an Action trigger.

**Comment by travisperson** [comment]
It actually wouldn't

```javascript
> var someObj = {}
undefined
> var state = {a: 1, someObj: someObj}
undefined
> var copy = Object.assign({}, state)
undefined
> copy === state
false
> copy.someObject === state.someObject
true
```

You'd have to due a deep object assign to truely destroy all references and we wouldn't want to do that, as you wouldn't be able to compare if a particular part of your state tree changed, which is incredibly useful in React via `shouldComponentUpdate`.

**Comment by TYRONEMICHAEL** [comment]
Ok makes sense. Thanks for pointing that out.

**Comment by aikoven** [comment]
@TYRONEMICHAEL you can use `Object.freeze()` instead. I'm using a helper that does deep freeze after every dispatch when not in production.

**Comment by gaearon** [comment]
You can use `deep-freeze` NPM package in development. You may also want to look into using a specialized immutable library like `seamless-immutable` or `immutable`.
