### ISSUE TITLE
Question: Best Practice for Arrays of Reducers

### ISSUE THREAD

**Issue by dexwiz** [rackt/redux#1174]
I often find I have multiple copies of a Component/Reducer pair one a page that exist in an array. This often happens on forms with lists. To differentiate actions on different components, I have to manually attach some sort of Id or Index parameter to all action creators. This just ends up polluting my action creators and reducers

Simple Duck

```js
const FOO = 'FOO'
export function foo(bar) {
  return {type: FOO, bar}
}

export function fooReducer(state={bar: null}, action) {
  switch(action.type) {
    case FOO:
      return {...state, bar: action.bar}
    default:
      return state
  }
}
```

Duck with ID

```js
const FOO = 'FOO'
export function foo(bar, id) {
  return {type: FOO, bar, id}
}

export function fooReducer(state={bar: null, id: null}, action) {
  switch(action.type) {
    case FOO:
    	if(action.id === state.id) {
    		return {...state, bar: action.bar}
    	}
    	else {
    		return state;
    	}
    default:
    	if(state)
      return state
  }
}
```

While this isn't difficult, it adds a lot of boilerplate, especially when the Id ends up being something like ```form.fooList[1]```. It essentially means all action creators and reducers need to be aware that they are in a list.

One option would be to wrap action creators and reducers with functions that add the Id to the action, and reads it back, respectively. But then you are just repeatedly serializing and deserializing paths in the state tree. 

Another option, and one that would to attach a hash to the reducer state, and wrap all action creators with a function that inserts the hash into the action. But then you loose the strength of a structured tree. 

I looked at redux-forms, and it goes with the first option. I didn't know if this was common across all redux apps, or if there was another method. I feel like there should be some way to leverage to the state tree without having to serialize into a string.

**Comment by gaearon** [comment]
You might be interested in https://github.com/erikras/multireducer.
