### ISSUE TITLE
rafScheduler middleware example could potentially issue actions twice

### ISSUE THREAD

**Issue by savvopoulos** [rackt/redux#1178]
Let's say our store has a subscriber, that, for some state S, triggers two actions, A1 and A2:

1. subscriber() => { S=store.getState(); dispatch(A1); dispatch(A2); }
2. dispatch(A1) will call the rafScheduler, which will queue A1, and schedule loop() for the next animation frame (let's say it'll happen in the next tick)
2. dispatch(A2) will also call the rafScheduler, and queue A2 (but not schedule another loop())
3. at this point rafScheduler.queuedActions == [A1, A2]
4. loop() will call next(a1); at this point, rafScheduler.queuedActions == [A2]
5. redux will then call subscriber(S'); let's say that this will retrigger A2
6. rafScheduler.queuedActions == [A2, A2];

Thoughts?

**Comment by savvopoulos** [comment]
I just realized this is more generally an issue with how subscribers work. I guess there must be some guidelines on how to write subscribers that I'm missing, so I'll close this issue.

Here's a toy example that will execute action B twice, no middleware needed:

var redux = require('redux');

var store;

function app(state, action) {
  console.log('triggered action', action.type)
  if (state === undefined) {
    state = { a: false, b: false};
  }
  var newState = Object.assign({}, state);
  if (action.type === 'A') {
    newState.a = true;
  }
  if (action.type === 'B') {
    newState.b = true;
  }
  return newState;
}

function subscriber() {
  var state = store.getState();
  if (!state.a) store.dispatch({type: 'A'});
  if (!state.b) store.dispatch({type: 'B'});
}

store = redux.createStore(app);
store.subscribe(subscriber);
subscriber();
/* prints
triggered action @@redux/INIT
triggered action A
triggered action B
triggered action B
*/

**Comment by gaearon** [comment]
Without the rAF, you can fix the example just by calling getState() again before the second condition. It's expected that the state can change after dispatch.

With rAF, you are opting into indeterminism if you check state right after dispatch. I think this is expected behavior.

**Comment by savvopoulos** [comment]
Thank you @gaearon
