### ISSUE TITLE
Precompile tests and ship them with NPM package

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#1179]
Just had an interesting discussion on Twitter about how [not shipping tests breaks `npm explore`](https://twitter.com/ljharb/status/680090399122145284). Maybe we should precompile tests and make sure they don't depend on Babel by the time `npm test` executes inside a published package. I wonder if any lib does that, and whether it's worth doing something similar.

**Comment by gaearon** [comment]
The current concern is that running `npm install` and `npm test` inside the NPM package folder (not the GitHub clone!) won't work because it doesn't contain the Webpack config, babelrc, etc. But we don't want to include babelrc because of issues like #1032.

**Comment by ljharb** [comment]
Basically, this is only problematic because the presence of configs inside node_modules breaks some *broken* tools - in other words, anything that delves inside `node_modules` is broken, because it's supposed to be a black box. The need to work around this exists, but it's still very frustrating that it impacts the entire ecosystem just because some people didn't want to transpile before publishing :-/

**Comment by gaearon** [comment]
@ide What's the official React Native stance on this? Do you plan to encourage people to publish ES6 RN modules? Or is the plan to go back to treating node_modules as ES5 black boxes?

**Comment by ide** [comment]
@gaeron it's been really good to have people publishing ES6/7 code. It's probably a little late to ship Babel with Node but if it were a possibility I think I would want to try it because it's mostly been a success for RN -- it's really good that people don't need to learn how to set up Babel for each project and source maps just work. So for React Native (and soon generic React components once RN is refactored to depend on the React package) I think we'll encourage, or at least support, publishing of ES6/7 code to npm.

**Comment by gaearon** [comment]
Haha I'm so ambivalent about this. Probably going to be good long term, but painful for non-RN-exclusive maintainers today.

**Comment by ljharb** [comment]
I don't think it will be good long term. Until the community settles on a convention where "main" is ES5, and "something else" is ES6, it's user-hostile to publish non-ES5.

**Comment by ide** [comment]
Some thoughts: 
- Babel should provide an option that RN can use to tell Babel to ignore .babelrc files under node_modules. We still want Babel to pick up .babelrc files in the user's project though, so we don't want to ignore all .babelrc files. This is the only scalable solution that currently comes to mind. We don't want every package author to have to omit .babelrc.
- RN can and should continue to work with ES5 packages.
- My sense is that it'd be good for everyone to publish ES6, for many of the same reasons why it's awesome that npm has generally been a way to distribute source code (as opposed to package managers that distribute binaries/byte code). So I like that RN has been an experiment in this direction.
- But that's a long way off so for today I think we want just a way for Redux to either ship compiled code or to include .babelrc and not break RN. I think it is likely a combination of RN and Babel's fault here that Redux can't ship .babelrc.
- FB directs RN and Babel -- if there is a way to get this on the roadmap of one or two engineers who care about open source, that could be a good way to get this issue resolved. Doesn't have to be you @gaearon - I think that FB is the best entity to make progress on this front though.

**Comment by timdorr** [comment]
From @ljharb's [tweet](https://twitter.com/ljharb/status/680088793936887808)

>  `npm explore foo && npm install && npm test` should always work.

Can I ask why? What we're downloading from NPM is a executable distribution package, not the full source environment. We don't include documentation or examples for similar reasons; they're not required to use the module in our code. If you do need that stuff, you can find it in the `repository` field or just `npm repo` (really handy command, btw!) to start browsing.

Perhaps I'm missing something, but this seems like a non-issue to me.

**Comment by gaearon** [comment]
Interesting. I just realized these commands weren't actually part of `npm explore` :-D There's some value in being able to run tests on dependencies to diagnose local potentially environment-specific issues. However I agree it's not a must.

**Comment by ljharb** [comment]
@timdorr I recommend absolutely including documentation or examples. For server assets, unused files are ignored, and just sit harmlessly on disk - for browser assets, your build pipeline picks up only the used code and ignores the rest. I shouldn't have to go to the git repo unless I want to make changes to the module.

**Comment by aikoven** [comment]
Agree with @ljharb. I would stand for including sources as well, esp. in transpilers era. I don't understand why having sources at hand is so underestimated. In my opinion it is even more important than tests / docs. I would include everything that has to do with lib usage — so basically everything except build pipeline stuff etc.

**Comment by timdorr** [comment]
@ljharb If you run `npm docs`, it opens your browser to the docs tree on github. Other than `npm explore`, there is no command that even directs you towards node_modules. It's all built around hiding that aspect of the package manager. Hence, it's not really a place you should be interacting with. 

If you want to hack on the code, you should be cloning the repo and using `npm link` to test against your changes. I really don't want to encourage users to mess around with what should be an immutable artifact from npm. There's a reason everyone stopped checking in node_modules a while ago :smile:

**Comment by ljharb** [comment]
yes, i agree with you - i'm saying i should be able to explore the module, including its tests. The instant I want to make changes, I should be cloning the repo, but anything I can do prior to that step, I should be able to.

**Comment by just-boris** [comment]
Sometimes you don't have access to internet. I really like when npm-modules are shipped with docs. Once I have installed a package, I can open docs, at least Readme and figure something out. 
As for tests. I have never have to run it for installed modules. 
I hope my point makes sense for you

**Comment by gaearon** [comment]
We do include README and the source.

**Comment by gaearon** [comment]
I think at this point it's not worth the hassle. I understand the initial argument and I agree it's not ideal, but I won't work on this. If you feel like submitting a PR to fix this I'd be happy to consider it. Overall I don't think it's a very common use case.
