### ISSUE TITLE
Documentation - recipe for resetting state between tests

### ISSUE THREAD

**Issue by oveddan** [rackt/redux#1183]
Add a recipe in Writing Tests that shows how to reset the state of the store between each test.  This is often desired when you don't want to have the results of one test affecting another.

The way to easily do this is to have the store created in each test by invoking the reducer action without a previous state (but this is not clearly documented).

**Comment by gaearon** [comment]
Would you like to make a PR? We just suggest creating a new store in beforeEach() function.

**Comment by oveddan** [comment]
Yeah exactly - creating the new store in that hook is ideal. Sure, I'll create a PR!

**Comment by gaearon** [comment]
I'll close the issue as non actionable for us—happy to receive a PR though.
