### ISSUE TITLE
real-world example with nextLink

### ISSUE THREAD

**Issue by alaksana** [rackt/redux#1184]
examples/real-world/middleware/api.js

In the function getNextPageUrl(), when it couldn't find 'rel="next"',
it returns null so I guess this is to replace previous nextPageUrl but that one is still remaining.
When I change null to "", it remove nextPageUrl and doesn't show "Load more" button anymore.

I'm new to Redux and still learning JS, so not sure until I learn more.
Is it intended?

**Comment by timdorr** [comment]
It may simply be a small UX oddity with the example app. If you want to submit a PR changing this behavior, I'd gladly take a look!

**Comment by gaearon** [comment]
Is this a bug report though? I'm not sure. Does this mean that we always show "Load more" even when on last page? We'd want to fix that.

**Comment by gaearon** [comment]
I think the example works as designed. I don't see any weird behavior. Indeed `nextPageUrl` is `null` if there is no next page, in which case we show no "Load More" button. So I don't see a problem.
