### ISSUE TITLE
Immutable.js with redux not working?

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/redux#1185]
Hello,

I'm currently in the middle of building an application using `react v0.14.3`, `redux v3.0.5`, `react-redux v4.02`, and` immutable v3.7.6`. I ran across an issue when trying to wire together a redux store to react components when using `immutable`.  I read in a stackoverflow that as of `redux 3+` that the combineReducers now works with `immutable`. However as I was wiring the redux store and react components I kept receiving an issue when attempting to access the state using Immutable method `getIn()`. 

```js
import React from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import DashCartTable from './DashCartTable.jsx';
import * as DashCartActions from './../../actionCreators/Dashboard/DashShoppingCart.js';
import I from 'immutable';

function DashCart (props) {

  var checkOut = () => props.actions.checkout(props.cartSneakers);

  return (
    <div className="DashCart">
      <DashCartTable cartSneakers={props.cartSneakers} actions={props.actions}></DashCartTable>
      <button onClick={checkOut} className="checkout btn btn-default">CheckOut</button>
    </div>
  );
}

function mapStateToProps(state) {
  return {
    cartSneakers: state.getIn(['dashboard', 'shoppingCart'])
    //cartSneakers: state.dashboard.get('shoppingCart')
    //cartSneakers: state.dashboard.shoppingCart
  }
}

function mapDispatchToProps(dispatch) {
  return {
    actions: bindActionCreators(DashCartActions, dispatch)
  }
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(DashCart);

```

I posted to [StackOverFlow](http://stackoverflow.com/questions/34501129/react-redux-not-connecting-store-to-react-component) about the issue to see if anyone could understand where I may have gone wrong. None were able to solve so maybe the issue with combineReducers returned?

Here are the other components that get props passed down in case you are wondering:

```js
import React from 'react';
import DashCartItem from './DashCartItem.jsx';
function DashCartTable (props) {

  var DashCartItemsList = props.cartSneakers.map((sneaker) => {
    <DashCartItem sneaker={sneaker} remove={props.removeSneakerFromCart}></DashCartItem>
  });

  return (
    <div className="DashCartTable">
      {DashCartItemsList}
    </div>
  );
}

export default DashCartTable;
```

```js
import React from 'react';
function DashCartItem (props) {

  var remove = () =>  props.actions.removeSneakerFromCart(props.key) ;

  return (
    <div className="DashCartItem">
      <div className="pull-left">
        <img className="itemImg"src="./../../../assets/images/creator.jpg" />
      </div>
      <div className="content pull-left">
        <h3 className="itemTitle">{props.sneaker.sneakerName}</h3>
        <p>Condition: {props.sneaker.condition}</p>
        <p>Size: {props.sneaker.size}</p>
        <p>Re-release: {props.sneaker.reRelease}</p>
      </div>
      <div className="content pull-right">
        <p>${props.sneaker.price}</p>
        <p>Quantity: {props.sneaker.quantity}</p>
        <button onClick={remove} className="btn btn-default">Remove</button>
      </div>
    </div>
  );
}

export default DashCartItem;

```

**Comment by gaearon** [comment]
[This answer](http://stackoverflow.com/a/34501948/458193) is correct, you are accessing `props.sneaker.sneakerName` but you probably meant `props.sneaker.get('sneakerName')` inside `DashCartItem`.

**Comment by kennetpostigo** [comment]
@gaearon unfortunately that didn't seem to work when I implemented it. I'm looking over my code to check for errors but nothing stands out.

**Comment by gaearon** [comment]
There's a lot of code there, it's hard to keep all in the head.
Please provide a runnable example and we can take a look.

**Comment by kennetpostigo** [comment]
ok will do @gaearon

**Comment by gaearon** [comment]
My guess would be that you're incorrectly importing `dashShoppingCartReducer`.

I see you're using `export function` rather than `export default function`.
This means you're using a *named* export.

Therefore to `import` it you need to use a *named* import (with braces):

```js
import { dashShoppingCartReducer } from './dashShoppingCartReducer';
```

If you are importing it as a *default* import (no braces):

```js
import dashShoppingCartReducer from './dashShoppingCartReducer';
```

you will get `undefined`, and it will be passed to `combineReducers` and filtered out.

If this is your problem, you need to either change your `import` to be named (include the curly braces), or change your `export` to be `default`.

**Comment by gaearon** [comment]
(Never mind my previous comment—it was wrong and I deleted it. `combineReducers()` wouldn't take `undefined` as a valid value under any key so you must be exporting things correctly.)

**Comment by gaearon** [comment]
OK, there was another update to that answer which I believe should solve your problem.
Arrow functions with a block don't have implicit return: http://stackoverflow.com/a/34501948/458193

**Comment by kennetpostigo** [comment]
Yes indeed it did!
