### ISSUE TITLE
`next` is undefined in middleware

### ISSUE THREAD

**Issue by rhys-vdw** [rackt/redux#1188]
I've created a simple middleware function, but it being given an undefined `next` argument. Is this a situation that should ever arise? I suspect I've done something subtly wrong here, because I have a working middleware elsewhere in the same app using what appears to be the same pattern.

This is my middleware and store initializer pruned back to the relevant sections.

```js
// ./middleware/flash-message-timeout.js

import { hide } from '../action-creators/flash-message';

let currentTimeoutId = null;

const middleware = store => next => action => {

  console.log({ store, next, action });
  // logs store and action as expected, but next is `undefined`.

  const previous = store.getState().flashMessage;
  const result = next(action);
  const next = store.getState().flashMessage;

  if (previous.messageId !== next.messageId) {

    // Clear any existing timeout.
    clearTimeout(currentTimeoutId);
    currentTimeoutId = null;

    // Start new timeout to clear this message.
    if (next.hideAt != null) {
      const delay = next.hideAt - Date();
      currentTimeoutId = setTimeout(() => store.dispatch(hide), delay);
    }
  }

  return result;
};

export default middleware;
```

```js
// ./initialize-store.js

// ...
import rootReducer from './reducers/root';
import flashMessageTimeout from './middleware/flash-message-timeout';

// ...
function createInitialState(data, { isDocked, isExtension }) {
  return { /* ... */ };
}

export default function initializeStore(data = {}, { isDocked, isExtension }) {
  const initialState = createInitialState(data, { isDocked, isExtension });
  const createStoreWithMiddleware = applyMiddleware(
    ReduxThunk, ReduxLogger(), flashMessageTimeout
  )(createStore);
  return createStoreWithMiddleware(rootReducer, initialState);
}
```

Any guidance here would be greatly appreciated.

**Comment by rhys-vdw** [comment]
I should also not that changing the order of middleware in `applyMiddleware` seems to have no effect.

**Comment by rhys-vdw** [comment]
Oh my god - double definition of `next` - not sure why my linter didn't pick this up!

**Comment by travisperson** [comment]
Just an FYI

> Oh my god - double definition of next - not sure why my linter didn't pick this up!

Because they are in two different scopes. If you want your linter to not allow this you should use [no-shadow](http://eslint.org/docs/rules/no-shadow)

**Comment by rhys-vdw** [comment]
Ah right of course, cheers. Kind of obscured by providing a 'curried' function signature like this.

**Comment by rhys-vdw** [comment]
Nonetheless I would have thought that using a `const` instance before declaration was illegal...
