### ISSUE TITLE
Docs are inconsistent on whether middleware is required for async data flow

### ISSUE THREAD

**Issue by sbichenko** [rackt/redux#1195]
[Async Actions](http://rackt.org/redux/docs/advanced/AsyncActions.html):
> Thunk middleware isn’t the only way to orchestrate asynchronous actions in Redux ... It is up to you to try a few options, choose a convention you like, and follow it, whether with, or **without the middleware.**

[Async Data Flow](http://rackt.org/redux/docs/advanced/AsyncFlow.html)
> Without middleware, Redux store only supports synchronous data flow. 

It seems to me that Redux does support async data flow out of the box. I can call `dispatch` actions in my component's methods at will.

Imagine, that I need to fetch some data. I then:
1. Dispatch an action indicating that we're fetching data (UI shows a spinner or something).
2. Make an async call.
3. When async call finishes, dispatch an action whose payload contains the fetched data (UI stops showing the spinner and shows the fetched data).

Am I missing something? Why do docs so strongly suggest using middleware and even go as far to say that async data flow is not supported without it?

**Comment by sbichenko** [comment]
See also: [discussion on StackOverflow](http://stackoverflow.com/questions/34570758/why-do-we-need-middleware-for-async-flow-in-redux/).

**Comment by gaearon** [comment]
I replied on SO: http://stackoverflow.com/a/34599594/458193
Thanks for asking.

**Comment by gaearon** [comment]
Regarding the documentation:

>Without middleware, Redux store only supports synchronous data flow.

That's right. It says **Redux store** only supports synchronous data flow. So anything asynchronous happens outside the store, just like you described (for example, in components). With middleware, the asynchronous work happens as a part of `store.dispatch` call which is different.

So I believe docs are still accurate.

**Comment by sbichenko** [comment]
Thank you so much for the answer! 

I've been thinking about this, and, yes, "orchestrating asynchronous actions" is not exactly the same as "synchronous data flow" wrt Redux store. But they are quite close, and for someone learning Redux this might be a problem. Maybe this

> Without middleware, Redux store only supports synchronous data flow.

can be changed to something like

> In Redux, asynchronous data flow can be implemented without middleware. However, it is more convenient to use middleware such as Redux Thunk, Redux Promise or Redux Saga. Such middleware allows you to treat asynchronous action creators just like regular action creators. 

Otherwise, I think it's not quite clear *why* the docs insist on using middleware. Also, many readers at this point probably won't understand what "support of synchronous data flow by Redux store" means.

If you think its a direction worth investigating, I can provide a pull request.

**Comment by gaearon** [comment]
Please send a PR, this looks great.

**Comment by sbichenko** [comment]
Working on it.
