### ISSUE TITLE
timebased updates

### ISSUE THREAD

**Issue by buhl** [rackt/redux#1196]
Hi all,

I have been spending Christmas with react and found Redux this weekend.
I come from angular and ember but have bought the redux single-immutable-state way and reacts separation-of-concerns completely these past few days.

After reading the guides and examples I decided to implement an overview/dashboard in redux-react.
The dashboard has a configuration view and and a display view. The configuration view has user interaction and there I have no problem using the redux way of thinking. But the display view only updates on timebased action.

I have this async action: 
```javascript
const asyncAction = () => {
    return (dispatch, getState) => {
        const { timerId } = getState();
        if (timerId === undefined) {
            const timerId = setInterval(() => {
                dispatch({type: TIMER_TICKED})
            }, ONE_SECOND);
            dispatch({type: TIMER_STARTED, timerId});
        }
    }
} 
```
that I dispatch as the last thing on the page load.
My problem is I would like to fire the following actions
* TIMER_TICKED_ONE_MINUTE (when the clock minute changes)
* TIMER_TICKED_ONE_HOUR (when the clock hour changes)
* TIMER_TICKED_ONE_DAY (when the day changes)

but I am unsure where to do this. Should I do it in my asyncAction? since there is nothing really to be reduced here I don't think I should handle this in the store?

Also I have two dump components that display the time and date.
The one that display the time should update evert minute and the one displaying date should update once a day. I guess this should be handled by reducers f.ex. setting {time: .. } and {'date': .. } in the state on TIMER_TICKED_ONE_HOUR and TIMER_TICKED_ONE_DAY actions. Only it is stated in the [documentaion](http://rackt.org/redux/docs/basics/Reducers.html) that you should never call functions like Date.now() in reducers - so I guess that's not the way to go.

Any help on this is much appreciated.
Thanks in advance
/mgb

**Comment by sai-prasanna** [comment]
1.You are correct , its not recommended to dispatch actions in reducers, reducers should not know about anything other than state, action(ie they should be functionally pure). Hence cannot know about dispatch function. 

So you can dispatch them in the action creator itself.

2. For updating dumb components in the redux way, you  store the date, time to be shown in the store using reducers (not react states). You can update them with current time be updated in reducers when you receive TIMER_TICKED_ONE_HOUR action

for example
    function dateTimeReducer(state, action) {
      switch(type) {
      case TIMER_TICKED_ONE_HOUR:
        return Object.assign({}, state, {
         dateTimeToDisplay: action.dateTime
       })
      default:
        return state
    }

Date, Time to be displayed should be ideally single object (if you store only current date and time in them), as you can derive current time, date from same object.

**Comment by gaearon** [comment]
This is a usage question, so please ask it on StackOverflow.
We try to keep issues for discussion of bugs and feature requests.
