### ISSUE TITLE
Selectors as a first-class Redux concept

### ISSUE THREAD

**Issue by acjay** [rackt/redux#1200]
Selectors seem like a concern of the Redux store, and not the consumer of the store. The Redux guide [recommends](http://rackt.org/redux/docs/basics/Reducers.html) normalizing the layout of the store and [portrays selectors](http://redux.js.org/docs/basics/UsageWithReact.html) as an auxiliary concept for mapping the normalized store to React `props`. But after much reflection, it seems that there's no reason `store.getState` should only return the normalized store. Instead, it could return the materialized view of the store, which would decouple Redux consumers from the normalization concern.

In working on [react-redux-controller](https://github.com/artsy/react-redux-controller), I wanted my controller methods to have access to the selector layer for derived data. That library executes some gymnastics to make this work out, but it struck me as kind of weird for this to be a concern of the React side of the React/Redux connection. I think I have a better idea now.

**Proposed solution**: create a `createStore` decorator called `denormalize` that takes the selector bundles and overrides `getState` with a new version that returns the raw store, with the selector outputs merged in. With this changes, all tools that operate on the output of `getState` would have access to the benefits of selectors, including views (as they do now), action creators, middleware, and so forth. Potentially even reducers.

**Enhancement**: create another `createStore` decorator called `denormalizedPropTypes` that would take the selector bundles, as annotated in this library, and add a method called `getStatePropTypes` that would return a map of state property name to `PropType`. This would allow prop types to live in the selector modules, as they do in [react-redux-controller](https://github.com/artsy/react-redux-controller/blob/master/example/selectors/index.js).

As explained above, both of these things could be implemented as `createStore` decorators, or "store enhancers", as they are [sometimes called](http://redux.js.org/docs/api/applyMiddleware.html) in the guide. I separate these into two decorators, because the second decorator would be specific to usage with React.

Neither of these changes would require any modifications to Redux core. But I'm posting as an issue here for 2 reasons. First, I'd appreciate feedback from Redux contributors and users. Maybe I'm missing some caveats. Secondly, if it's just a Good Idea, then once it's implemented, it could make sense to update the guide to make selectors a concept that's more general than React integration.

**Comment by umphy** [comment]
I am new to redux and have been playing with it via a small application. My comments may be way off, so please bear with me.

I like the idea of the materialised view of the store. But how about when subscribing to the store, we pass in a selector. That way, in the listener callback we can filter the getState() via that selector and only return the materialised view, and thus multiple components subscribing to the same store can see different parts of the store.

**Comment by kurtharriger** [comment]
I would prefer that denormalize be lazy.  I don't want to unnecessarily compute properties that are not used.  I do however think it's useful to for composability for a parent component to alter the structure of the state what passing it to a child component.  mapStateToProps works for synchronous code, but not so much for aync code that uses getState.

**Comment by acjay** [comment]
I've got several thoughts, and I'll just put them all out there, rather than censoring myself, because I think there's a 50/50 chance they could be promising or problematic.

@umphy Hmm, that seems like a really good idea. I suppose it would increase the memory `subscribe` requires, because it would have to create a `getState()` per subscriber that closes over the selector bundle used. But realistically, how many subscribers would the store ever have in a realistic application? 

My first thought is that this could still be implemented as a store enhancer, by augmenting it with a `subscribeWithSelectors` method. Perhaps the React-specific enhancement could adapt this pattern for compatibility with the API `react-redux` expects.

@kurtharriger If performance is a concern, one could still use [reselect](http://github.com/faassen/reselect)) for memoization. But with the other suggestion, one would also have granular control over the selector bundle on a case-by-case basis. This wouldn't apply to usage with react-redux, since it only `subscribe`s once, but one could pass something like [`R.pick(props...)`](http://ramdajs.com/0.19.0/docs/#pick) as `mapStateToProps` to narrow down to the desired properties in specific usages of `connect`. That might sidestep the [identity map](https://github.com/rackt/react-redux/blob/master/docs/api.md#inject-dispatch-and-every-field-in-the-global-state)

Or perhaps another combination of these ideas would be to have one global bundle of selectors, taken by the store enhancer, and then let each subscriber set a filter upon subscription.

I think for full generality, at the level of the store, one could provide the following options:

- Denormalize the result of `getState`
- Filter for a given subscriber (and perhaps narrow the scope of when the listener callback is invoked, accordingly)
- Denormalize for a given subscriber
- For practical react-redux usage, filter before converting passing to `connect`, for optimal [change detection](https://github.com/rackt/react-redux/blob/master/src/components/connect.js#L169-L181)

**Comment by umphy** [comment]
Here is a [quick hack] (https://github.com/umphy/redux/blob/ef0c2291d18be5dea3f5e7c1e18e9e698fb8f31e/src/createStore.js) (i.e. not tested at all) of what `createStore.js` might look like. The methods of interest are: `subscribeWithSelector` and `dispatch`.

I didn't pass the filtered `state` into the callback as I don't know whether that is the `redux` way or not. You can see that it filters the `state` with the given `selector`, and it also invokes the callbacks only if the filtered `state` have changed.

**Comment by kurtharriger** [comment]
Also, I'm not sure the benefit of defining proptypes with selectors, this seems react specific and probably doesn't belong in redux core.

**Comment by acjay** [comment]
@umphy Cool stuff! Looks like your example is specifically for Point 2? As mentioned, I'll probably try to do it as a decorator, simply because I don't really know what the appetite is for core changes, especially if API expansions aren't strictly required or beneficial for other reasons, like performance. I'm thinking it would live outside of this repo altogether (re: @kurtharriger's question, too), so that it would be strictly optional and not increase the maintenance surface. I just raised as an issue here, since it seems to be a central spot for feedback on auxiliary ideas, and it would lay right on top of the core code.

**Comment by acjay** [comment]
I think this is more like what I had in mind (totally untested):

```
// global denormalization
function denormalizer(selector) {
  return (createStore) => {
    return (reducer, initialState) => {
      const initialStore = createStore(reducer, initialState);
      function getState() { return selector(initialStore.getState()); }
      return Object.extend({}, initialStore, { getState, selector });
    };
  };
}

// per-subscription filtering/denormalization
const withSubscriptionFiltering = (createStore) => {
  return (reducer, initialState) => {
    const initialStore = createStore(reducer, initialState);
    function subcribeWithFilter(selector) {
      function filteredGetState() {
        return selector(initialStore.getState());
      }

      // Unlike the regular `subscribe`, this injects the custom `filteredGetState`
      // This would probably be augmented with the logic to only trigger the listener on state changes
      return initialStore.subscribe(() => listener(filteredGetState));
    }
    return Object.extend({}, initialStore, { subcribeWithFilter });
  };
}

const enhancedCreateStore = compose(
  applyMiddleware(...), 
  denormalizer(selector),
  withSubscriptionFiltering
)(createStore)
```
(named functions used haphazardly, where I thought a user might be likely to see them in devtools)

Assuming you used something like https://github.com/artsy/react-redux-controller/blob/master/src/selector_utils.js, denormalizer would propagate `propTypes`, if your `selector` had them. (Although, it occurs to me that only react-redux-controller needs propTypes *going in*, since it uses them for `childContextTypes`, so I might be the only one who'd care.)

**Comment by gaearon** [comment]
Thank you for the suggestions! The approach we take is to shift this logic to the consumer. Both views, middleware, and anything else can use the existing selectors. This sounds simpler than creating some kind of representations beforehand. You can use [redux-watch](https://github.com/jprichardson/redux-watch) as a utility function that recomputes a specific selector on change if that's what you're after.

**Comment by umphy** [comment]
I just realised that my idea is very similar to the `observeStore` from [this thread] (https://github.com/rackt/redux/issues/303#issuecomment-125184409).

Thanks @gaearon!
