### ISSUE TITLE
redux and immutable.js

### ISSUE THREAD

**Issue by viswaug** [rackt/redux#1202]
I am working with redux and immutable.js. I have written the following combineReducers method to reduce the state into an immutable Map. I just wanted to get a sanity check on if this makes sense
```
export const combineReducers = (reducers) => {
  return (state = Immutable.Map(), action) => {
    return Object.keys(reducers).reduce((nextState, key) => {
      return nextState.set(key, reducers[key](state.get(key), action));
    }, state);
  };
};
```

**Comment by gaearon** [comment]
Looks sensible although I'm not very well versed in Immutable API.
Check out https://github.com/dustinspecker/redux-immutable-combine-reducers too.
In the future please use StackOverflow for questions like this.
