### ISSUE TITLE
Description/ explanation for examples

### ISSUE THREAD

**Issue by tnguyen14** [rackt/redux#1203]
I find the examples provided in this repo to be very informative. However, I find some of them to be a little confusing, because I lack a higher level understanding of what they are/ do.

I wonder if it might be useful to have a quick description of what the example is in each of the example's folder, perhaps just a `README.md` file for each of them.

It would also be useful to have a demo of how they work. They don't need to be hosted, just a few gifs of how they work would do as well. As a more visual person, I find it easier to understand what the app is supposed to do before reading the source code.

Apologies in advance if this topic has been brought up before.

**Comment by gaearon** [comment]
If you want to own this, please feel free to contribute.
I can assure you it will be very much appreciated!

I'm closing because I don't have the time to actively work on it, and if somebody (you?) wants to help, they are free to open a PR. I'll be glad to review it!

**Comment by tnguyen14** [comment]
Thanks @gaearon. I could make a stab at it. Glad to hear that it's a valid idea.

**Comment by gaearon** [comment]
It's probably a good idea to add descriptions to examples' individual READMEs, and add summaries to http://redux.js.org/docs/introduction/Examples.html.
