### ISSUE TITLE
"Usage with React" has a rendering inefficiency

### ISSUE THREAD

**Issue by camjackson** [rackt/redux#1207]
In the docs, this example is given for usage with react: 

```js
class App extends Component {
  render() {
    // Injected by connect() call:
    const { dispatch, visibleTodos, visibilityFilter } = this.props
    return (
      <div>
        <AddTodo
          onAddClick={text =>       //This line
            dispatch(addTodo(text)) //and this line
          } />
        <TodoList
          todos={visibleTodos}
          onTodoClick={index =>
            dispatch(completeTodo(index))
          } />
        <Footer
          filter={visibilityFilter}
          onFilterChange={nextFilter =>
            dispatch(setVisibilityFilter(nextFilter))
          } />
      </div>
    )
  }
}
```

There's a small problem on the lines I've commented above. Every render of the `App` component will create a new anonymous function to be given for the `onAddClick` prop. This means that any state change for the whole application (because that state is passed to `App` as props) will cause all three sub-components  (`AddTodo`, `TodoList`, and `Footer`) to be re-rendered.

What you want to happen is that a subcomponent only re-renders if a relevant prop has really changed, e.g. `TodoList` re-renders if `visibleTodos` has changed. 

Here is one solution to this problem, I'm not sure if it's the right one:

```js
class App extends Component {
  constructor(props) {
    // Injected by connect() call:
    const { dispatch } = props;
    this.onAddClick = text => dispatch(addTodo(text))
    this.onTodoClick = index => dispatch(completeTodo(index))
    this.onFilterChange = nextFilter => dispatch(setVisibilityFilter(nextFilter))
  }
  
  render() {
    // Injected by connect() call:
    const { visibleTodos, visibilityFilter } = this.props
    return (
      <div>
        <AddTodo onAddClick={this.onAddClick} />
        <TodoList
          todos={visibleTodos}
          onTodoClick={this.onTodoClick} 
        />
        <Footer
          filter={visibilityFilter}
          onFilterChange={this.onFilterChange}
        />
      </div>
    )
  }
}
```

I'm not sure whether the example in the docs needs to be changed (or whether the above would be the correct change). Obviously performance is not a big concern for such a simple todo app. However, I think at the very least the docs should mention the problem, otherwise people (like me :smiley:) have to discover the hard way that creating a fresh callback on every render call will cause child components to re-render unnecessarily.

**Comment by winstonewert** [comment]
Since the subcomponents don't implement a shouldComponentUpdate, aren't they going to re-render regardless?

**Comment by gaearon** [comment]
This example is meant to explain how Redux works together with React. It's not meant to have the best performance. For best performance, pass action creators as the second argument to `connect()` as described in [React Redux](https://github.com/rackt/react-redux) detailed documentation.

**Comment by gaearon** [comment]
>However, I think at the very least the docs should mention the problem

Feel free to contribute to the docs!

**Comment by thinkloop** [comment]
Isn't the comment by @winstonewert also accurate? Barring any shouldComponentUpdate it doesn't make a difference?
