### ISSUE TITLE
In async example fetch request is disallowed

### ISSUE THREAD

**Issue by jadhavajay** [rackt/redux#1209]
When I ran the 'async' example, I got following error in chrome.

https://github.com/rackt/redux/tree/master/examples/async

Error - "XMLHttpRequest cannot load http://www.reddit.com/r/reactjs.json. The request was redirected to 'https://www.reddit.com/r/reactjs.json', which is disallowed for cross-origin requests that require preflight."

![asyncapp-error](https://cloud.githubusercontent.com/assets/1891293/12173226/94b99fae-b57b-11e5-9225-f5291f0671e6.png)

**Comment by jadhavajay** [comment]
I restarted my browser with following command, and it accepts the request now.

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir="C:/Chrome Insecure Session" --disable-web-security

**Comment by gaearon** [comment]
It used to work :-/
Is there anything we can do on our side?

**Comment by jadhavajay** [comment]
Nothing :). As you figured out.. I am new to JavaScript.

**Comment by gaearon** [comment]
Should be fixed now.

**Comment by pke** [comment]
Still doesn't work: 
> Fetch API cannot load https://www.reddit.com/r/reactjs.json. The request was redirected to a URL 
> ('about:blank') which has a disallowed scheme for cross-origin requests.

**Comment by gaearon** [comment]
@pke Try disabling browser extensions: https://bugs.chromium.org/p/chromium/issues/detail?id=360583#c9

**Comment by pke** [comment]
Ups! Disconnect was interfering! Thanks!

**Comment by pavilion2t** [comment]
I wonder how to solve...  I used the create-react-app to rebuild the reddit  example  and encountered this error: 

Failed to load https://wwww.reddit.com/r/reactjs.json: Redirect from 'https://wwww.reddit.com/r/reactjs.json' to 'https://www.reddit.com/r/wwww/r/reactjs.json' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3001' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
