### ISSUE TITLE
[Question] Is it ok to load and store data from reducers to local storage

### ISSUE THREAD

**Issue by mcdonnelldean** [rackt/redux#1212]
Hi Folk,

Great lib, I've gone through all the video's and most of the tutorials. So far I think I get it. The only part I'm a little stuck with is storage of particular pieces of data.

For instance, I am building a login using react router and redux simple router. When the app first starts I have a token or not in local storage. If I have this token I skip the login section, if not I force the user to login.

My thinking was I should have the token sent to the store via initial state and then have a reducer manage it from there via dispatched actions. The reducer will clear or update the token as needed.

Is the correct place to do the persistence in the reducer itself?

**Comment by gaearon** [comment]
No, reducer shouldn't be aware of persistence.

The solution I would suggest is:

1) Read state from storage before creating the store and pass it as a second argument to `createStore()`
2) Save data to storage in a denounced `store.subscribe()` callback.

You can save/restore just the parts you need if you filter the state before serialising.

**Comment by mcdonnelldean** [comment]
@gaearon Awesome, that makes much more sense actually! Realistically I only need the persistence for the initial new read as it will be in memory otherwise so this makes much more sense :D Thanks for a fast reply!

**Comment by mukeshtivari** [comment]
is it safe to store the redux store data in `localStorage` because anyone with little technical knowledge can modify it easily and those changes will be reflected in app on reload

please, suggest me a better & secure way to persist store data locally.
