### ISSUE TITLE
Overwrite entire application state

### ISSUE THREAD

**Issue by heydemo** [rackt/redux#1214]
I would like to be able to overwrite the entire Redux store state, outside of the using reducers so that I can log the state of the application when a user experiences a bug and then load that state to reproduce the problem

Is there anyway to do this outside of modifying every reducer to listen for an overwrite everything action?

**Comment by SimenB** [comment]
You do have import state in the devtools already.

https://github.com/gaearon/redux-devtools/commit/b4da7aaa4840843f6e1eac433745ec504d9cd8a9
https://github.com/gaearon/redux-devtools/blob/master/src/instrument.js#L11

Not sure how to use it though

**Comment by gaearon** [comment]
Please see discussion in https://github.com/rackt/redux/pull/658.
Yeah, DevTools also technically support this, and there are even some PRs attempting to add this to default UI but I haven't gotten around to reviewing them yet.
