### ISSUE TITLE
[Question] Websockets and dispatching

### ISSUE THREAD

**Issue by mcdonnelldean** [rackt/redux#1216]
I'm looking to convert over some websocket code (using Hapi + Nes) to use Redux. I'm thinking of doing this via thunk actions similar to how it's done with the reddit api example. Nes uses a subscription model so the actions would be similar to:

- SOCKET_SUBSCRIBE
- SOCKET_HANDLE_UPDATE
- SOCKET_UNSUBSCRIBE

My only concern is the handle update method would dispatch indefinitely (once per second) until the subscribe action is fired. Is this ok to do? It seems using the thunk stuff would make this possible.

**Comment by mcdonnelldean** [comment]
I'm thinking something like this would work fine with indefinite dispatch (leaving aside handling socket errors).

```
'use strict'

import {SOCKET_SUBSCRIBE, SOCKET_UPDATE, SOCKET_UNSUBSCRIBE} from '../actions'

const subState = {
  isSubscribing: true
  isSubscribed: false,
  data: null
}

function sub (state = subState, action) {
  switch (action.type) {
    case SOCKET_SUBSCRIBE:
      return Object.assign({}, state, {
        isSubscribing: true
        isSubscribed: false,
      })
      
    case SOCKET_UPDATE:
      return Object.assign({}, state, {
        isSubscribing: false
        isSubscribed: action.isSubscribed,
        data: action.isSubscribed ? action.data : null
      })

    case SOCKET_UNSUBSCRIBE:
      return Object.assign({}, state, {
        isSubscribing: false
        isSubscribed: false,
        data: null
      })

    default:
      return state      
  }
}

export default function Socket (state = {}, action) {
  switch (action.type) {
    case SOCKET_SUBSCRIBE:
    case SOCKET_UPDATE:
    case SOCKET_UNSUBSCRIBE:
      return Object.assign({}, state, {
        [action.sub]: handleSub(state[action.sub], action)
      })
    
    default:
      return state      
  }
}
```

**Comment by gaearon** [comment]
This looks reasonable.
I'll close as this is not an actionable issue or bug report.
Please feel free to share your experience here later!

**Comment by rossipedia** [comment]
This feels like it'd be a good fit for https://github.com/yelouafi/redux-saga
