### ISSUE TITLE
Dev-tools in real world example are broken

### ISSUE THREAD

**Issue by leonprou** [rackt/redux#1217]
Runing the real world example on my Mac, dev-tools on the right side seems to be broken. I've found some info that the time travelling features don't work so good with react-router, so maybe that's the reason. Clicking on one of the buttons I'm getting this error:
```
TypeError: null is not an object (evaluating 'state.router.params')
mapStateToProps
computeStateProps
updateStateProps
handleChange
handleChange
(anonymous function)
forEach
dispatch
handleRollback
handleRollback
onClick
onClick
onClick
dispatchEvent
invokeGuardedCallback
executeDispatch
executeDispatchesInOrder
executeDispatchesAndRelease
executeDispatchesAndReleaseTopLevel
forEach
forEachAccumulated
processEventQueue
runEventQueueInBatch
handleTopLevel
handleTopLevelWithoutPath
handleTopLevelImpl
perform
batchedUpdates
batchedUpdates
dispatchEvent
(anonymous function)
````

**Comment by gaearon** [comment]
Please make sure to use the search before reporting an issue.
This has already been reported several times before:

* https://github.com/rackt/redux/issues/1110
* https://github.com/gaearon/redux-devtools-dock-monitor/issues/10
* https://github.com/rackt/react-redux/issues/171

This is a problem with how `redux-router` is implemented.
We will switch to `redux-simple-router` soon to fix this.
