### ISSUE TITLE
Server Side Guide & Redux Store Clarification

### ISSUE THREAD

**Issue by startupthekid** [rackt/redux#1219]
In the [server rendering guide](http://rackt.org/redux/docs/recipes/ServerRendering.html) (which is fantastic by the way), it states:

> Redux’s only job on the server side is to provide the initial state of our app

and that makes perfect sense, especially if you need to dispatch actions based on query parameters and whatnot.

However, this:

```
 const html = renderToString(
    <Provider store={store}>
      <App />
    </Provider>
  )
``` 

seems to be in direct conflict with that statement as now the redux store created on the server side is being passed and rendered into the response, as seen here:

```
function renderFullPage(html, initialState) {
  return `
    <!doctype html>
    <html>
      <head>
        <title>Redux Universal Example</title>
      </head>
      <body>
        <div id="app">${html}</div>
        <script>
          window.__INITIAL_STATE__ = ${JSON.stringify(initialState)}
        </script>
        <script src="/static/bundle.js"></script>
      </body>
    </html>
    `
}
```

And then on the client side:

```
// Grab the state from a global injected into server-generated HTML
const initialState = window.__INITIAL_STATE__

// Create Redux store with initial state
const store = createStore(counterApp, initialState)

render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('app')
);
```

Aren't the react components getting double rendered? Once on the server side when it's injected using `${html}` inside `renderFullPage` and then again on the client side in the `render` call. 

I did a little test where I changed `const html` to a simple html element with an easily searchable string:

```
<div id="app">${<h1>YEAH IM THE BEST</h1>}</div>
```

and I was surprised to find that it in fact isn't anywhere inside my html, probably be the render on the client side overrides what was in there initially. I changed the target element that my client side components are rendered into and then I saw the `YEAH IM THE BEST`.

Side note: In the Server Rendering guide, in `fullPageRender`, the div is given an id of `app` but then in `client.js`, the elements are rendered into an element with an id of `root`. Shouldn't it be `app` not `root`?

This leads me to ask, is it even necessary to inject the `Provider` and sub-components into the rendered html? Especially since the store shouldn't be used for anything except the initial state.

Continuing on a bit, if someone were to inject `<Provider store={store}><App /></Provider>` right into the rendered html, that leads to a whole other host of issues. When `App` is required inside a node js environment, all the other requires (css, images, other libraries) are run but not by webpack, by the node js require system which doesn't have the same magic behind it as webpack does. 

What I might suggest is perhaps a clarification in the docs that you don't need to inject components into the rendered html and if you absolutely need to, use something like webpack-isomorphic-tools.

I may be totally off base here because my guess is there's probably a reason for requiring the react components inside the server code, even if I can't immediately see it.

**Comment by gaearon** [comment]
Thank you for the writeup!

>Aren't the react components getting double rendered? Once on the server side when it's injected using ${html} inside renderFullPage and then again on the client side in the render call.

This doesn't seem like a question about Redux; it's a question about React server rendering. If you check the React docs, you will find that React uses checksums generated on the server to compare client and server markup. If the markup matches, it will reuse the DOM without destroying it. If the markup doesn't match, React will warn you in the console, and re-create DOM from scratch.

>Side note: In the Server Rendering guide, in fullPageRender, the div is given an id of app but then in client.js, the elements are rendered into an element with an id of root. Shouldn't it be app not root?

That's a mistake in the docs, feel free to correct. We tend to use `root` in examples I think so you can use that.

>Continuing on a bit, if someone were to inject <Provider store={store}><App /></Provider> right into the rendered html, that leads to a whole other host of issues. When App is required inside a node js environment, all the other requires (css, images, other libraries) are run but not by webpack, by the node js require system which doesn't have the same magic behind it as webpack does.

This also has nothing to do with Redux. It's a widely discussed problem of how to organize React server rendering in a Node environment. This is not something we will provide support for; please use StackOverflow and React discussion forums to find different answers to this question.

>What I might suggest is perhaps a clarification in the docs that you don't need to inject components into the rendered html and if you absolutely need to, use something like webpack-isomorphic-tools.

It's a guide about server rendering. If you don't need it, don't do server rendering. :-) What is the point of server rendering if you don't render the actual components? (Well, technically preloading JSON is useful, but this guide is about a more advanced technique—you're right to cherry pick what you need from it.)

I'm closing as this doesn't appear actionable but please feel free to help out with docs if they are wrong or misleading. I'll be happy to give my comments on PRs.

**Comment by startupthekid** [comment]
Yeah that's all fair. I was mostly just curious about why the store was being rendered if the only point was to grab the initial state. Thanks for the clarifications!

**Comment by gaearon** [comment]
>Yeah that's all fair. I was mostly just curious about why the store was being rendered if the only point was to grab the initial state. Thanks for the clarifications!

I'm not sure what you mean by "store being rendered".

We prepare the store on the server to preload some data. Then we render our React app with that store into an HTML string, so we can send it to the client, and it displays immediately without waiting for JavaScript. This is great for SEO and for mobile connections.

Later, when JavaScript is loaded on the client, we create a store with the same data, and render the app on the client. React will figure out that the markup hasn't changed and magically "attach" to existing DOM. Now our app is interactive again, powered by client-side JS.

**Comment by startupthekid** [comment]
I was just referring to the fact that the `Provider` and store were being rendered into an html string, when the docs said the only purpose of the server side store was to grab the initial state. It all makes sense now though.

**Comment by gaearon** [comment]
`<Provider>` is just a thing to inject the store into your app. It's not being "rendered" per se.
What's being rendered is your app.

```js
 const html = renderToString(
    <Provider store={store}>
      <App /> {/* <--------------- the important part */}
    </Provider>
  )
```

So the only purpose of the store on the server *is* to grab the initial state. Maybe we can add "and provide that state to the components use it as they are rendered to an HTML string."

**Comment by startupthekid** [comment]
Yeah perhaps. But then an important caveat to include is that if you import a react component like `import App from 'components'` on the server, anywhere something other than a node module is required, it will fail simply because it's using the node require function, not the one with webpack/browersify/whatever magic.

**Comment by gaearon** [comment]
Many people don't use any Webpack magic so it's really a caveat of that particular tool. But I see your point. We just meant this as a guide to using Redux with server rendering React, and not as an intro to server rendering React itself. So we assumed that reader is familiar with how server rendering generally works and with its caveats. Please send a PR if you have specific suggestions how to clarify this and other matters in the guide!

**Comment by krystianjj** [comment]
Actually I have problem with store in SSR app. 
My steps:
- creating store on server side - OK
- sending to the client by window.initialState - OK
- create new store on client side - OK
- some dispatch action on client - OK
- try to get store by store().getState() - WRONG - I always get initial store from server.

It is possible to create store on client side and use it by dispatch and getState() in other component like normal react app ?
