### ISSUE TITLE
How to store list/single element in Redux?

### ISSUE THREAD

**Issue by michalg42** [rackt/redux#1222]
I'm using Redux for some time now but still I'm not sure how data in reducers should be stored.

For instance I would like to have list of users, from where I can choose one of them and get additional data.

Information needed for list is only id and name, and showing details of one user I need more info like city, phone number, etc.

I begin with reducer that store list:
```javascript
    UsersReducer:
    [{id: 1, name: 'John'},
    {id: 2, name: 'Will'},
    {id: 5, name: 'George'}]
```

Then I load details for one of the users and here is my question: how and where should I put them?

Should I expand UsersReducer, so it would look like:
```javascript
    UsersReducer:
    [{id: 1, name: 'John'},
    {id: 2, name: 'Will', city: 'London', phone: 123456789},
    {id: 5, name: 'George'}]
```
And in React extract from an array this one user?

Or perhaps I should leave old reducer and create new one for storing single user:
```javascript
    UsersReducer:
    [{id: 1, name: 'John'},
    {id: 2, name: 'Will'},
    {id: 5, name: 'George'}]
    UserReducer:
    {id: 2, name: 'Will', city: 'London', phone: 123456789}
```
And in React extract data from UserReducer?

Or both ways aren't correct and there is other idea to store data in Redux?

**Comment by smastous** [comment]
You could make a userDetailsById reducer that handles the details.  Then just get the pieces of data you need in your smart component.

**Comment by gaearon** [comment]
What @smastous described is the approach we suggest.

**Comment by qk0106** [comment]
Grouping the following into 1 object would improve the readability and maintainability.

positionTypes
positions
projectDetailTab
projectForm
projectGraphView
projectLoading
projectTabGraphView
projects
projectsGraph
