### ISSUE TITLE
Provide more minimal export

### ISSUE THREAD

**Issue by ashaffer** [rackt/redux#1223]
This isn't a huge deal because redux is pretty small, but i'm working on [vdux](https://github.com/ashaffer/vdux), which currently wraps redux and only uses a small portion of the bundled API. At the moment, redux is my single largest dependency, and i'm only really using `applyMiddleware` and `createStore`.

Requiring only those files, like this:

```javascript
import applyMiddleware from 'redux/lib/utils/applyMiddleware'
import createStore from 'redux/lib/createStore'
```

Reduces the size of the redux dep to about 1/4 of what it is normally. I can just do this for now, but it feels sort of unsupported and like something that may break in the future, unannounced. What i'd like is to be able to have an official thing like:

```javascript
import {applyMiddleware, createStore} from 'redux/core'
```

So that people like me who aren't using the other helper functions can avoid the bloat.

**Comment by gaearon** [comment]
What we should do is move all top-level exports to src from src/utils. We will support importing from lib/ folder directly for top-level exports. Want to make a PR for that?

**Comment by ashaffer** [comment]
PR'd: https://github.com/rackt/redux/pull/1224
