### ISSUE TITLE
Add createStoreWithMiddleware function

### ISSUE THREAD

**Issue by gajus** [rackt/redux#1236]
Most of the real life examples (and the official [documentation](http://rackt.org/redux/docs/api/applyMiddleware.html#example-custom-logger-middleware)) introduce an extra and unnecessary step of having to use `applyMiddleware` to create a function that is often named `createStoreWithMiddleware` (not to mention the awkward, variadic `applyMiddleware` syntax in the first place).

It would make sense to have a function `createStoreWithMiddleware` with API:

```js
createStoreWithMiddleware(middlewares: Array<Function>, reducer, [initialState]): Object
```

that is equivalent to calling:

```js
createStoreWithMiddleware = applyMiddleware(logger)(createStore);
store = createStoreWithMiddleware(todos, [ 'Use Redux' ]);
```

**Comment by gaearon** [comment]
How do I add a store enhancer like Redux DevTools here?

**Comment by rossipedia** [comment]
IMO this is not the responsibility of the library. Redux API surface is small, tight, and focused, and keeping it that way affords the most flexibility.

**Comment by gajus** [comment]
Agree with @rossipedia. It is indeed an unnecessary abstraction that belongs in a utility of some sort, if such is needed at all. @gaearon example further illustrates the limitations that such an abstraction introduce.

**Comment by gaearon** [comment]
I believe this is now addressed by https://github.com/rackt/redux/pull/1294. Please let me know whether you like the solution.
