### ISSUE TITLE
Question: Where does my SDK instance go?

### ISSUE THREAD

**Issue by elado** [rackt/redux#1237]
Let's say I have an SDK client instance in `index.js`:

```js
const client = new SDKClient()
```

with some functions like:

```js
client.signIn(email, password)
client.sendMessage(recipient, text)
client.on('message', message =>
  console.log(`new message from ${message.sender}: ${message.body}`)
)
```

I also have these action creators:

```js
export function signIn(email, password) {
  return dispatch => {
    client.signIn(email, password)
      .then(user => dispatch({ type: 'USER_SIGN_IN_SUCCESS', user })
      .catch(err => dispatch({ type: 'USER_SIGN_IN_ERROR', errorMessage: err.message }))
  }
}
```

What's the best approach to have that `client` in there?

I could create **action creators factory** (dependency injection style), still not sure it's the 'right' way:

```js
export default function (client) {
  function signIn(email, password) {
    return dispatch => {
      client.signIn(email, password).then(/*...*/)
    }
  }

  // ...

  return { signIn, ... }
}

// importing actions would be:

const userActions = require('./actions/users')(client)
```

**And why is it so important for me to not have it global or imported into the actions file?**

Because these action creators are in a separate module, so technically I import them into my app with `import * as userActions from 'blah-js-sdk-redux/lib/actions/users'`, that `blah-js-sdk-redux` doesn't know about the client instance, but the containing app does.

In a more opinionated flux library I would imagine actions as a part of a class that is instantiated with its dependencies. I haven't worked with other libraries though.

Thoughts?

**Comment by edvinerikson** [comment]
Personally I would keep the action creators within the app and make the module export the action types.
That should work, right?

**your-app/actions/users.js**
```js
import client from '../index.js';
import { USER_SIGN_IN_SUCCESS, USER_SIGN_IN_ERROR } from 'module/actions/users';
export function signIn(email, password) {
  return dispatch => {
    client.signIn(email, password)
      .then(user => dispatch({ type: USER_SIGN_IN_SUCCESS, user })
      .catch(err => dispatch({ type: USER_SIGN_IN_ERROR, errorMessage: err.message }));
  }
}
```

**module/actions/users.js**
```js
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';
// or ...
export function userSignInSuccess(user) {
  return { type: USER_SIGN_IN_SUCCESS, user };
}
export function userSignInError(error) {
  return { type: USER_SIGN_IN_ERROR, error };
}
/*
 * Then do this:
   .then(user => userSignInSuccess(user))
   .catch(err => userSignInError(err.message));
 */
```

**Comment by elado** [comment]
@edvinerikson The actions are in a separate module because that module is used in more apps.

My apps structure is this:

- `js-sdk` (the sdk client)
- `js-sdk-redux` (common reducers and actions such as `signIn`, `sendMessage`)
- `blah-react-toolkit`
   - Shared components between all apps
   - Included in an app under a `<Provider store=..>`, so any component can potentially `@connect` to store
- Each app:
   - Includes `js-sdk`, `js-sdk-redux` and `blah-react-toolkit`
   - Creates a client sdk instance
   - Creates its own store and has `<Provider>`
   - Store has reducers from `js-sdk-redux` but also app specific reducers
   - Components dispatch actions imported from `js-sdk-redux` and app specific actions

Putting the same action creators in each app would result in a lot of code duplication.

Starting to think the factory is the nicest solution. Then, the actions are not duplicated, but each containing app calls those factories with `client` and calling the factories would be the only duplication.

**Comment by edvinerikson** [comment]
Ah okay. Maybe you can have some sort of init step that takes the sdk as a argument and then the action creators can import the sdk locally. This is kind of what you said but it reduces the boilerplate even more.
**module/index.js**
```js
let sdkInstance;
export function init(sdk) {
  sdkInstance = sdk;
}
export function getSdkInstance() {
 // maybe throw if the consumer hasn't called the init method.
  return sdkInstance;
}
```

**module/actions/users.js**
```js
import { getSdkInstance } from '../index.js';
export function signIn(email, password) {
  const client = getSdkInstance();
  return dispatch => {
    client.signIn(email, password)
      .then(user => dispatch({ type: USER_SIGN_IN_SUCCESS, user })
      .catch(err => dispatch({ type: USER_SIGN_IN_ERROR, errorMessage: err.message }));
  }
}
```

**Comment by elado** [comment]
Thanks. I wouldn't wanna limit myself to a single client. I might wanna write a test of two clients talking to each other, and that case would probably have 2 sets of action creators.

**Comment by gaearon** [comment]
A function that takes a client and returns action creators sounds reasonable.

**Comment by elado** [comment]
Found a better solution using a middleware:

```js
// middleware/createClientMiddleware.js
export default function createClientMiddleware(client) {
  return ({ dispatch, getState }) => next => action => {
    if (typeof action === 'function') {
      return action(dispatch, getState, client)
    }

    return next(action)
  }
}
```

```js
// configureStore.js
export default function configureStore(initialState, client) {
  const finalCreateStore = compose(
    applyMiddleware(
      createClientMiddleware(client)
    ),
    ...storeEnhancers,
  )(createStore)

  const store = finalCreateStore(rootReducer, initialState)
  return store
}
```

and in an action:

```js
export function signIn(email, password) {
  return (dispatch, getState, client) => {
    client.signIn(email, password)
      .then(user => dispatch({ type: USER_SIGN_IN_SUCCESS, user })
      .catch(err => dispatch({ type: USER_SIGN_IN_ERROR, errorMessage: err.message }));
  }
}
```

Using this middleware instead of `thunk`. That way, I don't have to use factories. It allows me to import actions anywhere and I don't need to pass all over the place "client bound" actions anymore. It does mean that I use a single client within the store but it's totally fine in my case.

**Comment by elado** [comment]
`redux-thunk` just added `withExtraArgument`: https://github.com/gaearon/redux-thunk#injecting-a-custom-argument

**Comment by nvartolomei** [comment]
@elado this change is, kinda, meh. When you need to use multiple apis, sdks you will start to feel pain because of this change IMHO.

To me look like `redux-api-middleware`'s route is better for things like this.

**Comment by gaearon** [comment]
>When you need to use multiple apis, sdks you will start to feel pain because of this change IMHO.

What do you mean? You can pass multiple things in that argument if you’d like.

**Comment by elado** [comment]
@nvartolomei how is `redux-api-middleware` simpler? And as @gaearon says - the argument passed is whatever you want it to be. It could be an object with multiple clients/sdks/apis (`thunk.withExtraArgument({ myAPI, theirAPI, godsAPI })` and action `return (dispatch, getState, { myAPI, godsAPI }) { ... }`)

**Comment by nvartolomei** [comment]
@elado I didn't say `redux-api-middleware` is simpler, I just said it is a better fit in my opinion.

It looks natural to route api calls, return values, via actions, when using redux. The main argument is that using `redux-api-middleware` I can chain other middlewares, hook in to every every call, dispatch other actions, handle in reducers common cases like request, response and error, without having to dispatch these by hand every time I use third argument, or actually forget to dispatch an error. Isn't `redux-api-middleware` more DRY?

If I am right, then adding `withExtraArgument` encourages a bad practice, this is why I said **meh**.

Hope we will not see anyone passing store later to object passed with `withExtraArgument`, so that extra argument can dispatch actions on store and subscribe to state changes :)

**Comment by gaearon** [comment]
>Hope we will not see anyone passing store later to object passed with withExtraArgument, so that extra argument can dispatch actions on store and subscribe to state changes :)

Shouldn’t be possible directly because the store is not created by the time you define middleware. Sure, you could put `getStore()` on it but at this point it’s super hacky anyway.

**Comment by artem-alek** [comment]
@elado @nvartolomei @gaeron resurrecting this thread. What do you do with a SDK that gets initialized async? Are you still able to pass it as `thunk.withExtraArgument` or what was proposed and only have 1 instance of the SDK for the whole session? I seemed to be blocked in what to do in initializing the store to pass a sdk that needs to be resolved before passing it.

**Comment by markerikson** [comment]
@artem-alek : you'd need to either delay the store creation process until that SDK instance has been created, or I suppose you could pass an object as `extraArgument` synchronously right away and then mutate it with the SDK instance later (sketchy, but doable).

**Comment by artem-alek** [comment]
@markerikson Thanks! Ill give the delay a go! Didnt think about that. About the latter, I feel the same way!
