### ISSUE TITLE
Question: Where to handle server pushed events?

### ISSUE THREAD

**Issue by elado** [rackt/redux#1239]
I'm working on a chat app. After signing in, a socket of incoming messages should open.

Where would it make sense to listen to it?

I thought I'll start listening after sign in, but is it OK/clean to reuse the same `dispatch` in the listener?

```js
// actions/users.js
export function signIn(email, password) {
  return dispatch => {
    client.signIn(email, password)
      .then(user => {
        listenToMessages(dispatch)
        dispatch({ type: 'USER_SIGN_IN_SUCCESS', user })
      })
      .catch(/*...*/)
  }
}

function listenToMessages(dispatch) {
  client.on('message', message => {
    dispatch({ type: 'MESSAGE_RECEIVED', message })
  })
  client.openSocket()
}
```

I also saw this example that listens to new messages **on the component** by passing the `socket` object as a prop:

https://github.com/raineroviir/react-redux-socketio-chat/blob/master/src%2Fcommon%2Fcomponents%2FChat.js

It feels wrong to me that the component does this kind of work.

Thoughts? What's the best practice here?

**Comment by elado** [comment]
Also, what if I don't have the `dispatch` from a previous action and I just want to start a listener when page loads? Does it have to involve being fired from a component?

**Comment by gaearon** [comment]
It doesn't really matter. This is about how you choose to organize your code. Both approaches are fine, and there is no big difference between them. You can call `dispatch` from anywhere, it's the same function whether you call it from the component or directly on the store.
