### ISSUE TITLE
I want to get the current action from store.

### ISSUE THREAD

**Issue by whatifif** [rackt/redux#1243]
store has "subscribe" method to notify "the change of state" to all the subscribing clients.

It will be convenient if the current action is able to be sent to the clients in 'subscribe' method.

Current state can be obtained from store.getState().
But there is no such method to get the current action from store 
( for example, store.getAction() which will return the current action dispatched to the store ) 

Any idea is appreciated.

**Comment by gaearon** [comment]
Please see https://github.com/rackt/redux/issues/1057, this is the same request.

**Comment by gaearon** [comment]
Also https://github.com/rackt/redux/issues/1091, https://github.com/rackt/redux/pull/622.

**Comment by whatifif** [comment]
< I found an exact solution to this issue. So I leave the link below.>

Strong advantage: Action can be controlled before acting on store.

# Sending Actions To The Server Using Redux Middleware
[http://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html]

<code>
-----------------------------------------------------
src/components/index.jsx

import {createStore, applyMiddleware} from 'redux';
import io from 'socket.io-client';
import remoteActionMiddleware from './remote_action_middleware';

const socket = io(`${location.protocol}//${location.hostname}:8090`);
socket.on('state', state =>
  store.dispatch(setState(state))
);

const createStoreWithMiddleware = applyMiddleware(
  remoteActionMiddleware(socket)
)(createStore);
const store = createStoreWithMiddleware(reducer);

----------------------------------------------------------
src/remote_action_middleware.js

export default socket => store => next => action => {
  if (action.meta && action.meta.remote) {
    socket.emit('action', action);
  }
  return next(action);
}

-----------------------------------------------------------
src/action_creators.js

export function vote(entry) {
  return {
    meta: {remote: true},
    type: 'VOTE',
    entry
  };
}
--------------------------------------------------------------
</code>
