### ISSUE TITLE
Can `currentReducer` be exposed?

### ISSUE THREAD

**Issue by dashed** [rackt/redux#1246]
Can `currentReducer` be exposed?

https://github.com/rackt/redux/blob/c5d9a8a11897ea558c348e02eaf76038563d57b9/src/createStore.js#L38

I have a usecase where I have some "Higher-Order redux store" that wouldwrap a store's `currentReducer` via a custom `combineReducers` and then replace the new reducer through the store's `replaceReducer`.

**Comment by gaearon** [comment]
I'm not sure I understand the problem. Higher order store (aka "store enhancer" in our docs) takes a `createStore` and returns a `createStore`. This means it has full access to `createStore` arguments (including the reducer) and can wrap it before passing to the next function. You can look here for an example (at the very end of the file is a store enhancer that wraps the reducer): https://github.com/gaearon/redux-devtools/blob/master/src/instrument.js
