### ISSUE TITLE
Dispatch action from deep component

### ISSUE THREAD

**Issue by vitalets** [rackt/redux#1247]
hi. I have deep component structure:
```html
<Container>
  <RightColumn>
    <Content>
      <Form>
        <Button>
```
Now I want to dispatch some action when user click on button.
Container is connected to redux store (as top level component, by docs recomendation) and have `dispatch` method in props.

**Solution 1**: pass `dispatch` down to button:
```html
<Container>
  <RightColumn dispatch={this.props.dispatch}>
    <Content dispatch={this.props.dispatch}>
      <Form dispatch={this.props.dispatch}>
        <Button onClick={this.props.dispatch('some_action')}>
```
Looks ugly.

**Solution 2**: pass `handleClick` up to container:
```html
<Container>  // let handleClick = function () { this.props.dispatch('some_action'); }
  <RightColumn handleClick={this.handleClick}>
    <Content handleClick={this.props.handleClick}>
      <Form handleClick={this.props.handleClick}>
        <Button onClick={this.props.handleClick}>
```
Also ugly.

Could anybody show what is the best way to deal with it?

**Comment by just-boris** [comment]
Just add `@connect` to `Button` and it will get `dispatch` in its own props.

It is okay to have Container components (also known as "Smart") deeply in your app if it really needed by your requirements.

**Comment by gaearon** [comment]
Please ask this on StackOverflow. This is an issue tracker and not really a support forum. Thanks!

You might want to check out the last 10 videos in my Egghead course (https://egghead.io/series/getting-started-with-redux) as they deal with this problem.

**Comment by vitalets** [comment]
Thank you @just-boris 
Found similar question http://stackoverflow.com/questions/33244324/how-to-dispatch-actions-from-child-components-three-level-down
