### ISSUE TITLE
Nested Entities Note on tutorial 3.1 Async Actions

### ISSUE THREAD

**Issue by landabaso** [rackt/redux#1260]
Hi @gaearon (& others),

I'm a bit confused about the Note on Nested Entities in the tutorial-> 3.1 Async Actions.
You mention to consider normalizing data as in:

Example1:
```javascript
entities: {
	posts: {
		42: {id: 42, title: 'A title'},
		100: {id: 100, title: 'Other title'}}
},
postsByReddit: {
	reactjs: {
		items: [ 42, 100 ]
	}
}
```

vs.:

Example2:
```javascript
postsByReddit: {
	reactjs: {
	items: [ { id: 42, title: 'A title'}, { id: 100, 'Other title'} ]
	}
}
```

This is fine. However, after I read it, I thought some of the magic was lost. From my limited understanding (newbie here) one of the nice aspects about Redux is how you can easily make a change in state to automatically update components that depend on it in React (using connect & select).
Also, updates are efficient for using an immutable state which boosts state change comparisons.

So, say I have a component that is connected to postsByReddit. Now imagine I update id:100 title to 'Yet another title'. If I do so in Example2, then a new object will be set on the second position of the items' array and the component will be rendered.

However, I believe some extra stuff has to be done when using Example1. Say I change entities->posts->100. The second element in the array postsByReddit->reactjs->items is still a scalar (the id) which does not change.

I guess the question is: what is the preferred method to inject entities's dependencies to different parts of the state?

Is it part of the "select" to convert id's to object pointers?

**Comment by gaearon** [comment]
>Is it part of the "select" to convert id's to object pointers?

Yes, please check out `shopping-cart` in this repo for an example of that.

The reason we encourage you to normalize your data is to avoid duplication. When data is duplicated in several places of the state tree, it's no longer easy to edit it locally. How do you update a title of item that may be deeply nested in several places of the state graph?
