### ISSUE TITLE
how to handle login user 

### ISSUE THREAD

**Issue by fortunebubble** [rackt/redux#1261]
I apologize first if this is a repeated question. Let say I have userId and verifiedUser these two fields that I got back from sever after the user successfully login, should I store the user fields in the global store? or how should I handle it. Thanks in advance

**Comment by gwind** [comment]
@fortunebubble I've completed a project use redux. My login : 

1. `<Route>` go a onEnter

   ```javascript
      <Router history={this.props.history}>
        <Route path="/login" component={Login} />
        <Route path="/" component={Base} onEnter={Base.onEnter}>
          <Route path="home" component={Statistics} />
          { other_routes }
        </Route>
      </Router>
   ```

2. Base.onEnter

   ```javascript
class Base extends React.Component {
    static onEnter(nextState, transition) {
      let sid = localStorage.getItem('sid');
      if (!sid) {
        transition(null, '/login');
      }
    }
    // others ...
}
```

3. on your Login

    ```javascript
localStorage.setItem('sid', YOUR_SID);
    ```

I hope this would be help for you.

**Comment by fortunebubble** [comment]
Thanks @gwind

**Comment by gaearon** [comment]
Closing as not an issue.
@gwind Thank you for chiming in!

**Comment by gaearon** [comment]
For future reference, you might want to check out https://github.com/andrewngu/sound-redux as it implements authentication. Also see https://github.com/rackt/redux/issues/1068, https://github.com/rackt/redux/issues/826.

**Comment by fortunebubble** [comment]
Thanks for the references @gaearon
