### ISSUE TITLE
Request Feedback: Server-Side Redux Store

### ISSUE THREAD

**Issue by tracker1** [rackt/redux#1265]
I had an interesting thought, and would appreciate some response/comments...

The thought is, that it might be interesting to establish a socket.io/sockjs, or similar connection to a server, where the current state is persisted, as well as passed back to the client, per some sort of session token... when an action is dispatched on the client, it is sent to the server, processed, and the new state is shipped back to the client.  More interestingly, a backing storage such as RethinkDB could subscribe to the session and all updates push/persist through the dbms...

My reasoning is that this would allow for slightly more security in terms of state checking, as well as keeping decision logic away from the client... as long as the state doesn't get *too* big (stays under a few KB), it could work pretty well.  By keeping the store/state on the server, it would mean more memory overhead, this could be offset with Redis or similar, but was thinking it would be an interesting solution to a slight technical issue of requiring slightly more structured security over the event lifecycle.

There would also be some need for notification as the socket/internet connection to the server may go up/down... Maybe that part alone, a property on the final state could be managed client-side.

**Comment by rossipedia** [comment]
There's really nothing preventing you from doing this using something like `redux-thunk` or `redux-promise`. However, you'd probably end up having state on the server as well as the client, and that always introduces complexity when you have to make sure that data in both locations is the same. Redux is just plain javascript, so it can be used on the server as easily as the client.

**Comment by gaearon** [comment]
You might be interested in http://codepen.io/elierotenberg/post/flux-over-the-wire.
Indeed this pattern can be implemented for Redux.
I'm closing as this is something out of scope for the core but please feel free to discuss.

**Comment by tracker1** [comment]
@rossipedia I was thinking that the reducers would all exist on the server (or mostly), so that actions would dispatch on the server (similar to redux-thunk) where state is server-managed, and the result is updated on the client.

**Comment by sompylasar** [comment]
@tracker1 You would anyway have to have a browser-side cache of the state so that getState can be made synchronous. You can make an API that implements Redux architecture of (state, action) => nextState -- and the browser-side store that updates upon receiving the next state from the server.

**Comment by stevenyap** [comment]
@tracker1 I share the same thought as you and this is worth a few more thoughts.

Even if the state is big, we can send state diff (like react) so that the data in the wire is kept small.
Server rendering will be a breeze since the server has the entire state.
Async operations from the client may not be needed at all since the frontend will simply react based on new states from server.
Keeping reducers and actions on server also open up new possibilities such as redux on Ruby/Python/PHP/etc since it is now a server-side coding and also removed the coupling between redux and react.

Of course, end of the day, this is resting on a WebSocket connection to communicate changes.

**Comment by tracker1** [comment]
Looks like `deep-diff` would be a decent library for this...

* server sends initialState to client
* clientStore is created with websocket connection to server
* dispatch(action) serializes action to server, no async/thunks on client
* server listener treats "action" as an rpc signal to an action-creator dispatched on the server
* server-side "store" sends the diff for the dispatch(es) to the client
* client applies diff to local state tree
* client raises listener notifications
* client re-renders against new state tree

It would create a little bit (and depending on network, lot bit) of lag...  But it might be a decent option in the case of certain types of games, or secure systems.  Someone at the NodeAZ user group actually demonstrated this concept in practice a few months back (within a month of my last comment)

I'm not sure that it would necessarily work as-is with react, and would probably need some special care for wiring up with react and react-router in particular.

**Comment by markerikson** [comment]
There's several libraries that implement this sort of thing already, in various ways.  See https://github.com/markerikson/redux-ecosystem-links/blob/master/store.md#store-persistence .  Also, don't think it's in that list, but this looks like that "synced action" approach: https://github.com/lapanoid/redux-remote

**Comment by stevenyap** [comment]
@markerikson thanks for the links! We may be exploring this in a new project of ours and I will update this thread again if we have any findings.

**Comment by dannyharding10** [comment]
I would love to see this! It would be great if multiple clients could share the same store and all be updated on a state change.
