### ISSUE TITLE
[question] how to clean up store

### ISSUE THREAD

**Issue by xiaodid** [rackt/redux#1268]
Hi,
we are facing a problem and we are glad that your help.
the problem is that:
we are using combineReducer({route, reduer1, reducer2, reducer3}) to combine multiple reducers. and each part saves some business data. then when user logout, we want to clean up entire store, set the store to initial state. 

how can I do so, thanks.

**Comment by gaearon** [comment]
Please see https://github.com/rackt/redux/pull/658#issuecomment-136478950.

**Comment by susan-github** [comment]
This url is 404 @gaearon , could you provide another one？ Thanks.
@xiaodid How to resolve this question at last, I have the same confusion as you~~~

**Comment by didierfranc** [comment]
😉

```js
const appReducer = combineReducers({
  oneReducer,
  another,
  ...
})

const rootReducer = (state, action) => {
  if (action.type === 'CLEAR') {
    state = undefined
  }
  return reducers(state, action)
}
```

**Comment by susan-github** [comment]
@didierfranc Thanks for you help~
