### ISSUE TITLE
Sharing functionality between containers

### ISSUE THREAD

**Issue by madshargreave** [rackt/redux#1282]
Hi

I have multiple containers which all use the same callback to fetch the currently authenticated user.

What is the best way to share such code between container components?

```
componentDidMount () {
    this.fetchCurrentUserFromLocalStorage();
  }

  fetchCurrentUserFromLocalStorage () {
    const user = JSON.parse(localStorage.getItem('user'));
    const token = JSON.parse(localStorage.getItem('token'));

    if (user && token) {
      this.boundActions.fetchUserApps({ token });
      this.boundActions.userSignedIn({ user, token });
    }
  }
```

**Comment by Sigmus** [comment]
This article may help you: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.7hff2vgf8

I think this would make a nice Stackoverflow question.

**Comment by svnlto** [comment]
Have a look at [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example/)'s `fetchData` implementation. That should give you a good idea on how to handle that.

[getDataDependencies](https://github.com/erikras/react-redux-universal-hot-example/blob/f22f8becee294a752b61539b73cf8fbc5b0284ec/src/redux/middleware/transitionMiddleware.js)
[fetchData](https://github.com/erikras/react-redux-universal-hot-example/blob/f22f8becee294a752b61539b73cf8fbc5b0284ec/src/helpers/getDataDependencies.js#L17)

**Comment by tracker1** [comment]
Load this in your store creation, or reducer as part of initial/default state, not in your components.

**Comment by sompylasar** [comment]
The "fetchCurrentUserFromLocalStorage" looks like an "initApp" action creator which can be either  simple and create an INIT_APP action to handle in both "apps" and "auth" reducers (assume you have them), or can be a redux-thunk function to read localStorage and dispatch these two actions you dispatch in your example.

**Comment by gaearon** [comment]
Seems like a generic question that can better be answered on StackOverflow. Nothing actionable for us here, so closing. Thank you for the discussion!
