### ISSUE TITLE
Non pure function in reducer used in redux example

### ISSUE THREAD

**Issue by fusionstrings** [rackt/redux#1284]
I see use of impure function as reducer in redux example, which contradicts with recommendation.

https://github.com/rackt/redux/blob/master/examples/async/reducers/index.js#L49
I understand these are just examples but want to understand if this is something might be practiced in production world.

Or does it not count as impure function.

**Comment by BerkeleyTrue** [comment]
The `post` function is itself a reducer and a pure function making `postsByRedit` function a pure function.

**Comment by gaearon** [comment]
Both functions are pure. Is there a misunderstanding?

**Comment by markerikson** [comment]
Not sure why you would say that it's impure.  The reducer receives a state and an action, and returns a result solely based on those.  No other outside behavior is done, and the original state is not mutated.  Looks like a pure function to me.

**Comment by fusionstrings** [comment]
I said so because it does not receive `post` is not passed to reducer as argument but being called. I under stand it's a reducer as well. Probably my understanding of pure function was incorrect.

**Comment by gaearon** [comment]
Still not sure I understand you. (But I’m glad to help!) Pure functions are functions without mutations and side effects. Do you see either?

**Comment by fusionstrings** [comment]
No Sir, that was mistake from my part I believe. I stand corrected. Thanks everyone for guiding me here. I can only hope I didn't ask unnecessary question.
