### ISSUE TITLE
[Discussion]Which state should put in redux store and how to deal with shared state cross pages?

### ISSUE THREAD

**Issue by kpaxqin** [rackt/redux#1290]
@gaearon  @acdlite 
Currently the most thing confused me is which state should put into the redux single-state and which should not.

In SAP, we often have multiple pages, and there are two kinds of state:

1. `Page state`: states `only need in a few screens` , like array of user in user list page, or value of a form field,  they're rarely reused in other pages. 
2.  `Shared state`: states shared between pages, like login state. Or [form data in a low](https://github.com/rackt/redux/issues/297#issuecomment-173612158)

One fact is actually the `Shared state` is just a very small part in hole project when compared with `Page state` : we have lots of pages, and just a few data need to be shared.

So, which one should put in redux state tree ?
If we say it's `Page state` , how we manage those things between pages ?

If it's `Shared state` , since redux state lives in memory, how we deal with page refresh ? And should we put page states back to components (that looks like a huge step back)?

I see the community goes in mixed way, and this kind of unclear might making things hard to figure out in complex situations, just like [this issue](https://github.com/rackt/redux/issues/297).

For me, I would say the `Page state` seems to be the right answer: let redux manage page states making things uni-directional in most cases. 

Libs like `redux-form` also follow this way and go one more step forward: extract some shared parts of page state and related logics for reuse. The key is: they're handling things `only need in a few screens` with redux.

But I still don't know what is the correct way to manage those `Shared state` since there is no pattern for it. I've try some ways like [fake api](https://github.com/rackt/redux/issues/297#issuecomment-174160592) but want to see more discussions and solutions.

How do you guys think about it ?

**Comment by timdorr** [comment]
Any multi-page or router app needs to be able to recover from a page refresh. This can be done entirely on the client side or with server side rendering in a universal app. In either case, the page you're on needs to be able to tell what state it should request to be fetched from external sources (normally your server API). 

There are numerous ways of doing this, but you'll normally use the same mechanism for fetching that state whether you're coming from another page or a refresh. The fetching logic can look at the state fetched so far and determine if it needs to fetch more (either because the data isn't there or it's old). You can look into some different libraries to make this easy, such as async-props and react-refetch. 

But there is no distinction in redux between the so-called page and shared state. It's just one single state object at all times. That's redux's best feature: the simplicity.

**Comment by kpaxqin** [comment]
@timdorr 
Thanks for your reply and I totally agree with you that page should fetch the external sources they need.

The problem is in some cases like [a long flow](https://github.com/rackt/redux/issues/297#issuecomment-173612158). The external sources might come from other pages, not server. 

My suggestion is to build `fake api` in client side to act like server-api as external resource, but there're some voice in our team said we can put those shared data into redux store then retrieve it in other pages.

And in the issue #297 , it seems lot of people agree that we should treat shared things as application state and those things `only need in a few screens` should stay in component state.

I don't agree with that personally, but would like to hear more voice about it.

**Comment by timdorr** [comment]
You can certainly serialize parts of your state to local storage or something like that. You'll still need to handle recovering that state, but it should be the same code that handles a navigation back or forward, or a page refresh. 

You shouldn't care how the user ended up on the page, just that you know how to request the state needed for display.

**Comment by frostymarvelous** [comment]
"array of user in user list page" -> state
"value of a form field" -> non-state

The user list can technically be shared with other pages without a problem, therefore it makes sense to find them in the state.
The value of a form field not only belongs in that single page, but is even transient to that page. It's not meant to survive e.g. a page refresh (except in the rare case). If using react, use initial state and persist it locally to be restored when remounted.

Personally, I share data like form field values with other pages using query string parameters, just like traditional web pages work.
