### ISSUE TITLE
Redux is great but major feature is missing...

### ISSUE THREAD

**Issue by born2net** [rackt/redux#1300]
Redux is a great modeling pattern that I am sure will continue and grow...
I have been using a single source of truth type models for many years and I am happy yo see its becoming popular in the JS eco system.

However Redux is missing a critical part as currently it focuses more on the producer and less on the consumer.
Let me explain, I am talking about the:

```
let unsubscribe = store.subscribe(() =>
  console.log(store.getState())
)
```

currently when an action is produced, all subscribers will receive the callback, however if you ever developed a large application, or worst yet, had to jump into someone else's code you know that the biggest issue is finding your way around. And so if I look at a reducer which is switching on some list of action, I would like to be able to see all the places in the code base that "cares" about a particular (like we always do with events), just right click on the action in your favorite IDE and select find usage.

now I understand that with reducers you can divide the application to multiple smaller reducers to so its easier to find things... BUT, if you are going to refactor a line of code, you want to make sure all subscribers that rely on it will not explode... 

The cleanest way to get that is simply to pass the action to the subscriber as in:

```
let unsubscribe = store.subscribe((typeAction:string) =>
  if (typeAction === Consts.FOO)
    console.log('found foo'); 
 console.log(store.getState())
)
```
and we can find all places in the code that refer to Consts.FOO when we refactor...

It will be much easier to reason about how changes propagate in a large application if we can get the action to be passed to the subscribers.

The second point (which may or may not be valid) is why isn't the store reference passed as well just to save a single line of code: store.getState();

so instead wouldn't that be better:

```
let unsubscribe = store.subscribe((store:Redux.store, typeAction:string) =>
  if (typeAction === Consts.FOO) {
      console.log('I got my store);
  }
)
```

If we already have a subscriber we might as well use it to pass relevant parameters.

Thanks for a great framework and hope we can get it even better,

regards

Sean - founder of http://DigitalSignage.com

**Comment by gaearon** [comment]
>It will be much easier to reason about how changes propagate in a large application if we can get the action to be passed to the subscribers.

Can you please explain on a specific scenario how that would make code easier to understand? In Redux you should re-render UI based on *current state*, not the action. By the time the state is returned from the reducer, the action doesn't matter anymore. For debugging, you can use [redux-logger](https://github.com/fcomb/redux-logger):

![](https://camo.githubusercontent.com/56edb558c8fc5d80607d9868a0458536ba274f15/687474703a2f2f692e696d6775722e636f6d2f4c4467763474702e706e67)

Also this has been discussed in quite a few issues:

#251
#347
#580
#622
#1057
#1091
#1243

>The second point (which may or may not be valid) is why isn't the store reference passed as well just to save a single line of code: store.getState();

Please see #303.

In general it’s best to search for issues first :wink:

**Comment by born2net** [comment]
I think you may have missed the point, this is not for better coding, but safer refactoring as you can find the places that care about the result of an action,

regards

Sean

**Comment by gaearon** [comment]
>I think you may have missed the point, this is not for better coding, but safer refactoring as you can find the places that care about the result of an action,

I don't understand what kind of code you are refactoring. If subscribers can't know about the action in the first place, how does passing it help refactoring? Some specific real-world examples will help.

**Comment by markerikson** [comment]
@born2net : isn't that the point of using named constants in your actions and reducers?

**Comment by born2net** [comment]
not really, since any store changes are propagated everywhere... regardless...

**Comment by ffxsam** [comment]
I stumbled upon this and also found a situation where I want a component to react to action, *not* state.

http://stackoverflow.com/questions/35930677/is-there-a-way-to-have-a-react-container-respond-to-a-redux-action

The list of members in an organization is nothing I want to store in the global state, doesn't make any sense. However, I want my component to know when the thunk dispatches a "success" action so it can do something (force a re-render).

**Comment by johnsoftek** [comment]
Why does the component need to re-render if state has not changed?

**Comment by mbensch** [comment]
@ffxsam From what I understand is that you want to have a component react directly on the response of an async action rather than storing that data in the state and having the component react to a state change?

That would break the idea of a unidirectional data flow because you'd be bypassing the reducers and have a component tightly coupled to an external entity (your API responses). This kind of defeats the purpose of using redux (or a single state atom). If it's a whole lot of data you can look into paging, memoizing etc. Or just clean up the state when you leave the module/page and don't need the data anymore and then refetch from server or cache on next visit.

Just a couple of ideas :)

**Comment by ffxsam** [comment]
I think actually this is a sign of poor architecture on my part. :) I went back through my code, and I'm passing a container's state object rather than actual live data. I think I need to do some serious refactoring.
