### ISSUE TITLE
Missing loose-envify dependency

### ISSUE THREAD

**Issue by dereklieu** [rackt/redux#1304]
Hey, thanks for the awesome work on redux.

Just installed 3.1.1. `package.json` calls for a [`loose-envify`](https://github.com/rackt/redux/blob/master/package.json#L87) transform, but it's not listed as a dependency anywhere and so is breaking my build.

**Comment by gaearon** [comment]
Argh :-(

I [thought](https://github.com/rackt/redux/pull/1301#issuecomment-176245718) this might be a problem but didn't verify. Can you make a PR to add it please? Same for React Redux.

**Comment by gaearon** [comment]
I'm in a car now but I'll be able to release a fix in about half an hour.

**Comment by timdorr** [comment]
@gaearon I'll get things together short of the npm publish for you.

**Comment by gaearon** [comment]
Thanks!

**Comment by dereklieu** [comment]
Thanks @timdorr @gaearon!

**Comment by timdorr** [comment]
Should this be a regular dependency or devDep?

**Comment by gaearon** [comment]
It seems like it should be a regular dep. I think React does it that way.

**Comment by timdorr** [comment]
Because this is our first and only regular dependency, which seems a little odd. \*shrug*

**Comment by gaearon** [comment]
Fixed in 3.1.2.

**Comment by gaearon** [comment]
I deprecated the faulty versions of `redux` and `react-redux`.
Please verify whether the fixes worked!

**Comment by dereklieu** [comment]
Not using `react-redux` in this project so can't speak to that, but built successful with `redux@3.1.2`. Thanks for turning this around so speedily.
