### ISSUE TITLE
Thick clients applications

### ISSUE THREAD

**Issue by anri-asaturov** [rackt/redux#1314]
Hi, I just started to learn about redux and I like it a lot and thinking about switching our apps(Peerio) to it. But my apps are 'thick clients', they sync with server, store their data locally in sqlite database and only have loaded in RAM data subset that is needed for rendering. Is there any success stories/patterns of usage of redux with thick clients?

**Comment by hnordt** [comment]
You can use Redux whenever you have local state to be handled.

In my experience, Redux works great even with simple state. Handling state inside React components is a pain.

In my opinion Redux will be good for your use case.

**Comment by robertknight** [comment]
To some extent, if you have a situation where you have some subset of data loaded and available synchronously and the rest stored elsewhere and accessed via async APIs, it doesn't matter whether the "elsewhere" is a local database accessed via IndexedDB or SQLite or a much larger DB accessed via an API provided by a web server - you can treat them the same way.

**Comment by gaearon** [comment]
I’ll close because there doesn’t seem to be anything specifically actionable here but please feel free to continue the discussion.
