### ISSUE TITLE
DOM Manipulation

### ISSUE THREAD

**Issue by MarkMurphy** [rackt/redux#1317]
Can someone elaborate on this comment in the Explore component:

https://github.com/rackt/redux/blob/master/examples/real-world/components/Explore.js#L23-L25

> // Generally mutating DOM is a bad idea in React components,
    // but doing this for a single uncontrolled field is less fuss
    // than making it controlled and maintaining a state for it.
    this.refs.input.value = val  

I'm somewhat new to react and redux and I'm just trying to understand why you chose not to use `setState` in this particular case.

**Comment by gaearon** [comment]
We also want to react to changes in routing (e.g. as result of back button) so we would have to implement `componentWillReceiveProps` too. In fact this is how we had it in the beginning but people were confused by the example and started using `componentWillReceiveProps` and `setState` in their own code for every connected component because they thought this is necessary for connecting components to Redux. To eliminate confusion we just don’t show this pattern anymore :-)

**Comment by MarkMurphy** [comment]
@gaearon 

It makes me nervous when I see comments in code which basically say something along the lines of "You probably shouldn't do this.". I think the React docs also state something similar regarding using refs in this way. 

> To eliminate confusion we just don’t show this pattern anymore :-)

Well, almost... :confused: 

> We also want to react to changes in routing (e.g. as result of back button) so we would have to implement componentWillReceiveProps too.

But you **did** implement `componentWillReceiveProps`: [here](https://github.com/rackt/redux/blob/master/examples/real-world/components/Explore.js#L12-L16)

If `setState` was used (making the input a controlled input) wouldn't you actually be writing less code because the `setInputValue` and `getInputValue` methods would be replaced by a `handleChange` method? *i.e.* 

```js
handleChange(e) {
  this.setState(value: e.target.value)
}
```

> In fact this is how we had it in the beginning but people were confused by the example and started using componentWillReceiveProps and setState in their own code for every connected component because they thought this is necessary for connecting components to Redux.

So why not just add a comment which documents this in the `componentWillReceiveProps` method? Maybe even provide link to a discussion on Github which would elaborate further if necessary.

**Comment by MarkMurphy** [comment]
I should also state that I too was confused when I saw a redux component using `setState`. I thought that with redux state should only be set using actions. After some searching around I came across several Redit posts which explained this:

* [Using setState with Redux](https://www.reddit.com/r/reactjs/comments/3ogz52/using_setstate_with_redux/)
* [When using redux, when should react components use this.setState (or should they not)?](https://www.reddit.com/r/reactjs/comments/3mpc0e/when_using_redux_when_should_react_components_use/)

The answers found there might be helpful to put in front of new comers to redux.  It seems to me it's inevitable they will find an example somewhere that uses setState.

**Comment by gaearon** [comment]
Wanna send a PR with setState() and better comments?
