### ISSUE TITLE
replaceReducer() should throw if argument is not a function 

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#1318]
This is an easy one, please feel free to send a PR.
We want to add a `typeof` check in `replaceReducer` just like we have when the store is created.

**Comment by Andersos** [comment]
Hello @gearon, I tried making a pull request in #1320 . Do you want me to also try and make a test for the case?

**Comment by gaearon** [comment]
Thank you! Yes, tests are necessary.

**Comment by gaearon** [comment]
This is now fixed by #1321, thanks @dzhiriki!
