### ISSUE TITLE
Feature request, subscribe to only a portion of the store...

### ISSUE THREAD

**Issue by born2net** [rackt/redux#1328]
I think it will be awesome if we could subscribe only a portion of the store...
i.e.:
```
    store.shopping.subscribe(() => {
        console.log('cart is active');
    });
}
```

this will reduce a lot of the change detection changes that angular2 has to do now if I start spreading these subscribes all over my components...

thoughts,

regards,

Sean.

**Comment by gaearon** [comment]
Please use https://github.com/jprichardson/redux-watch for this.
Alternatively you can use https://github.com/wbuchwalter/ng2-redux which handles subscriptions for you.

**Comment by born2net** [comment]
you just made my weekend... that is EXACTLY what I was after .... now I can filter per component's reducer... TX!!!!!!!!!!!!
