### ISSUE TITLE
setInterval is not defined for execsjs

### ISSUE THREAD

**Issue by justin808** [rackt/redux#1335]
See comment here:

https://github.com/rackt/redux/commit/e2e14d26f09ca729ae0555442f50fcfc45bfb423#diff-1fdf421c05c1140f6d71444ea2b27638

Copied here:

@gaearon This change of referencing `setInterval` broke server rendering for https://github.com/shakacode/react_on_rails/ as  running this code through execjs fails because setInterval is not defined, per this [FAQ for execjs]( (https://github.com/sstephenson/execjs#faq).

I'll polyfill this for now, but I recommend that you change the line to:

```
setInterval && setInterval.name === 'setInterval'
```

References:

* https://github.com/shakacode/react_on_rails/issues/246#issuecomment-177457388
* https://github.com/shakacode/react_on_rails/pull/244
* https://travis-ci.org/shakacode/react_on_rails/builds/106071431

**Comment by justin808** [comment]
I polyfilled this here: https://github.com/shakacode/react_on_rails/commit/59f1e68d3d233775e6abc63bff180ea59ac2d79e

**Comment by gaearon** [comment]
Fixed in 3.1.7, thanks for reporting.
