### ISSUE TITLE
Usage With React - Containers

### ISSUE THREAD

**Issue by hnordt** [rackt/redux#1337]
Hello.

In: http://rackt.org/redux/docs/basics/UsageWithReact.html

I think that in Container and Presentational Components table, the location of Container Components should be changed. Container Components are not always top level.

When a newcomer read the Presentational and Container Components article (https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0), then come back to the docs and read that Container Components location is top level it can lead to a dogma or a miss conception.

Maybe changing Container Components location to "Top level, middle and/or route handlers" solves the problem.

Toughts?

**Comment by gaearon** [comment]
Yes, this is already updated in https://github.com/rackt/redux/pull/1285.
