### ISSUE TITLE
Reducers definition in docs

### ISSUE THREAD

**Issue by samsch** [rackt/redux#1344]
There was some confusion for a new user about what a reducer is, with the user referring to reducer functions as *action handlers*. The confusion seems to have stemmed from the heading **Handling Actions**, and that the term *reducer* doesn't seemed to be defined in section 2.2, with the docs just assuming that you caught on to what they are referring too.

I think it would be great to have *reducer* more clearly defined in section 2.2, to help against this type of confusion in the future.

**Comment by gaearon** [comment]
Mind sending your proposed changes as a PR to the docs? That would be easier to discuss!

**Comment by samsch** [comment]
Actually, I'm not sure this issue is valid. It seems there was more confusion in the chat... The user was using the term *action handler* to refer to the snippets that handle an individual action type within a reducer.

This can be closed. Sorry for the trouble.
