### ISSUE TITLE
3.2.0 Global not defined with in isPlainObject

### ISSUE THREAD

**Issue by jayzawrotny** [rackt/redux#1346]
![screen shot 2016-02-01 at 4 55 12 pm](https://cloud.githubusercontent.com/assets/590297/12732647/95dd906a-c904-11e5-9fbd-0411bc7192ce.png)

I'm building our app files with browserify, babel 6.4, envify, react-redux, react 0.14 and the bundles are throwing this error that global is not defined. I take it envify or loose envify is not factoring out the globals?

For now I have reverted to 3.1.7 of redux and 4.1.2 of react-redux but of course it would be nice to see a real fix.

**Comment by gaearon** [comment]
Thank you for reporting. What bundler do you use? We should definitely fix this but a temporary workaround would be to enable `global` polyfill in your bundler (e.g. Webpack does this by default). 

cc @jdalton: this means libraries can't depend on Lodash modules using `global` without making assumptions about bundlers in browsers.

**Comment by gaearon** [comment]
Another option would be to temporarily switch to UMD build (`redux/dist/redux.min`) which shouldn't have this problem.

**Comment by gaearon** [comment]
The way I see it, unless Lodash agrees to fix it on their end reasonably quickly by removing dependency on `global` in CommonJS modules, we have to do the following:

1. Release 3.2.1 and 4.2.1 that back out of using Lodash
2. Either wait for Lodash to fix this or...
3. Bump the major and tell CommonJS consumers we expect `global` to be polyfilled by their bundler when they use CommonJS build in the browser

I don't know how to enable `global` polyfill with Browserify but I assume it shouldn't be difficult.

**Comment by phated** [comment]
@gaearon browserify is supposed to pick up whether the `global` variable is reference and place it into the arguments list.

**Comment by gaearon** [comment]
Maybe `detectGlobals` Browserify option isn't true in your config? See https://github.com/lodash/lodash/issues/915#issuecomment-73019176 which is about the same exact issue.

**Comment by phated** [comment]
^ was just going to post that - the other thing that might be wrong is having `noParse` set on Redux or all node_modules or something

**Comment by phated** [comment]
@gaearon in relation to https://github.com/rackt/redux/issues/1346#issuecomment-178232500 - see https://github.com/rackt/redux/pull/1339#issuecomment-177691574 where JD mentions he will be releasing isPlainObject on npm without the global reference in the next version.

**Comment by jdalton** [comment]
I can release the update this evening.

**Comment by gaearon** [comment]
Awesome, thank you for quick response!
I'll leave this open then, and when you're ready ping us, and I'll update the minimal version.

**Comment by jdalton** [comment]
You'll also be able to drop the `global` webpack plugin addition too.

**Comment by jdalton** [comment]
> Awesome, thank you for quick response!

No problem, third-party integration, like Redux, is our top priority.

**Comment by jayzawrotny** [comment]
Oooh awesome! Glad a fix is on the way. Anyway, that is a good catch I do have detect globals off and while enabling it would fix the immediate error it wasn't needed before so it seemed worth reporting.

**Comment by vwochnik** [comment]
I'm still having the issue of the missing `global` for this dependency. I'm using `rollup` with `rollup-plugin-node-resolve`, `rollup-plugin-babel` as well as `rollup-plugin-commonjs`.

**Comment by gaearon** [comment]
Have you updated Redux? This shouldn't be an issue with newer versions of Lodash.

**Comment by vwochnik** [comment]
I have tried the whole thing yesterday and it is having this issue. May I provide a minimal test repository?

**Comment by vwochnik** [comment]
Well, I have just created a [test repository][https://github.com/vwochnik/rollup-redux-example] with the issue. Note that after compilation, the `dist/main.js` file contains code referring to the `process` global variable.

**Comment by gaearon** [comment]
>Well, I have just created a test repository with the issue. Note that after compilation, the dist/main.js file contains code referring to the process global variable.

So is it `global` or `process` that you’re having issues with?

Redux uses `process.env.NODE_ENV` under expectation that your bundler will replace it with `"production"` or `"development"` during envification. Browserify and Webpack can do this. Is this something Rollup doesn’t do?
