### ISSUE TITLE
How to test shopping-cart actions?

### ISSUE THREAD

**Issue by cwei-bgl** [rackt/redux#1348]
I just wonder how to test [shopping-cart actions](https://github.com/rackt/redux/blob/master/examples/shopping-cart/actions/index.js)? as actons file directly imports shop api object, It looks the shop api object can not easily be mocked for testing. One way to replace the shop api object for testing i can think of is to import it into tests also and modify its content. Then after the tests completion, restore the shop api object to its original state.

**Comment by gaearon** [comment]
Please see https://github.com/rackt/redux/blob/master/docs/recipes/WritingTests.md#async-action-creators
