### ISSUE TITLE
Small improvement to readability of the middleware section of docs

### ISSUE THREAD

**Issue by mkarajohn** [rackt/redux#1355]
**The following is my personal feedback, as a newcomer to redux, reading the docs for the first time.**

While going through the docs, I finally reached the section about middleware. 

Since the middleware section is probably the 'hardest' to grasp, as someone who is completely new to redux, I would gladly take any simplifications that it could give me. 

One such 'simplification', that I think could help, is having the `next(action)` named something more descriptive, e.g. `providedDispatcher(action)` or something along those lines. 

I am sure there must be a reason as to why it is named `next()`, that at this time goes over my head, but truth is I always had to keep a 'manual' mental reminder for what `next()` actually represents, every time I encountered it in the doc, in order to help me keep track of what I was reading.

**Comment by gaearon** [comment]
“Next” means `dispatch` of the next middleware in chain. Maybe we can call it `nextDispatch`?

It’s a convention from server side frameworks that would yield control to the next middleware by calling `next` argument.

**Comment by gihrig** [comment]
@gaearon Coming from a server-side background, I would vote for keeping the API unchanged. Consistency is important, it's one of the compelling reasons in favor of JS everywhere.

Your explanation above is clear and should be added to the docs for those not familiar with the middleware concept.

**Comment by mkarajohn** [comment]
I find `nextDispatch` to be an improvement over `next` as far as clarity-at-first-glance is concerned.

In the end of the day, try to see it from the perspective of someone who, yours trully, is oblivious of that naming convention from server side frameworks. Descriptive names for such things are probably going to help keep with the flow. That's just my opinion.

**Comment by sompylasar** [comment]
@mkarajohn It's not always `nextDispatch`, it's either `nextMiddleware` or `dispatch`. This could be clarified in the docs.

**Comment by gaearon** [comment]
>Your explanation above is clear and should be added to the docs for those not familiar with the middleware concept.

Happy to accept a PR doing this. Since leaving an issue hanging here is not very productive, I’ll close it, but I’m happy to continue the discussion in a PR that adds an appropriate note.

Thanks!
