### ISSUE TITLE
Problems unit testing controllers and ngRedux 

### ISSUE THREAD

**Issue by Erik099** [rackt/redux#1365]
I recently posted a question on stackoverflow regarding issues i have unit testing controller in an angular/ES6/Redux app. Unit testing actions and reducers is well documented, and quite simple to implement. However, I am having trouble with controllers - specifically with class constructors, DI and connect functions binding of my actions to lexical 'this', etc. 

http://stackoverflow.com/questions/35188646/angular-redux-es6-unit-testing-controllers

To keep this brief, I am wondering if one of you could post an example of testing a controller with ngRedux as a constructor param. I would like to mock redux in this scenario, but I am hitting a wall doing this with an ES6 constructor. I dont see this as an issue per se, but it would definitely help those like me that need to ramp up on Redux (and things that are also new like ES6/modules). Any help would be greatly appreciated.

**Comment by Erik099** [comment]
to be clear, this is not a Redux specific issue/question, it pertains more to ngRedux and angular.

**Comment by timdorr** [comment]
I would post this over on the ng-redux issue tracker: https://github.com/wbuchwalter/ng-redux This isn't really relevant here.

**Comment by gaearon** [comment]
Yeah, unfortunately most of us don’t have the knowledge to answer this.
