### ISSUE TITLE
Clean Architecture and Redux

### ISSUE THREAD

**Issue by DjebbZ** [rackt/redux#1367]
Hi,

I'm getting more and more interested in what Uncle Bob calls [The Clean Architecture](http://blog.8thlight.com/uncle-bob/2012/08/13/the-clean-architecture.html). It's a very nice software architecture that decouples the application from the outside world, from frameworks of any kind etc.

I'm wondering if it's possible to use Redux as an event sourcing engine and make a Redux configurable so that it takes interactions with the outside world as dependencies. To make myself more clear : the key principle from this archi is the Dependency Inversion Principle. In Redux, dispatching synchronous actions already decouples the app from the outside world. Just call `store.dispatch` from anywhere (be it the UI, a CLI app...) and the state handled by Redux will change according to the business rules handled by the reducer(s). In a "true Clean Architecture" way this already couples the app to Redux, but I'm fine with this in my experiments. The problem comes from async actions. The async logic is hardcoded in the action itself, like "fetching data from this Web API", or "Interacting with some Browser API". This couples tightly the app and the outside world.

My goal (and question here) is to make this configurable at app initialisation. I'm wondering how to implement the Dependency Inversion Principle with Redux. I imagine that all async actions should be provided at app initialisation, so that different implementations of the app just have to provide these actions. The only place I see where "initialisation/configuration" may happen is when creating the store, especially when applying the middlewares. But I can't wrap my head about how to write a middleware that would handle all the implementation specific details of the connexion between the app and the outside world.

... As I'm writing this, I realise it should be enough to separate sync and async actions. If I package a Redux app with the reducers and the sync actions only (with tests and checks of any kind), maybe with the middlewares too, could I just import this app and use it in, say, a React implementation ? An Angular implemenation ? A Node CLI implementation ? The side-effecty async action would come with implementation. Does it make sense ?

Which leads to another question : how to manage state in the implementation ? I suppose I should manage it separately from the app state in Redux. In the case of a React implementation for instance, some state would live in React components (the minimum UI state necessary to track display/hidden widgets state for example), but the rest of the state... Should it live in Redux too ?

I think I should tinker with the idea and and try to implement a basic Todo App with Redux, one time with say React, another time as a Node CLI. But before I do that, I'd love your input on this discussion.

Please forgive me if the discussion is out of place here, and for the tone used. I've been scratching my head with this problem and couldn't resist trying to formulate my thoughts here.

**Comment by gaearon** [comment]
Have you looked at [Redux Saga](https://github.com/yelouafi/redux-saga) yet? I think it does what you describe. There are no “async actions” with this approach. Actions dispatched by your components are like commands. Special daemons called “sagas” can take them, do some work, and output other actions, until they reach the store, and can implement async control flow with generators.

**Comment by gaearon** [comment]
>If I package a Redux app with the reducers and the sync actions only (with tests and checks of any kind), maybe with the middlewares too, could I just import this app and use it in, say, a React implementation ? 

Unless I misunderstand you, I think so:

```js
import reducer, { increment, decrement } from 'redux-counter'

class App extends Component {
  constructor() {
    super()
    this.state = reducer(undefined, {})
  }

  dispatch(action) {
    this.setState(state => reducer(state, action))
  }

  render() {
    return (
      <Counter
        value={this.state}
        onIncrement={() => this.dispatch(increment())}
        onDecrement={() => this.dispatch(decrement())}
      />
    )
  }
}
```

This is Redux pattern in React without Redux, but with your existing code. Similarly, you could translate this to Rx with `scan()` operator, or to other view libraries.

**Comment by haihappen** [comment]
Please please add this to the official docs!

**Comment by DjebbZ** [comment]
Thanks for your quick feedback. I had indeed already looked at Redux Saga, and re-read the whole README to make sure I understand. I don't understand how it could help me, since I don't see how I can 

> configure which sagas run, and what IO they use, depending on the specific environment.

to quote you.

But, your second answer is really helpful. Thanks a lot. I'll try to implement something a will keep you informed. In the meantime, closing this issue to avoid pollution.

**Comment by Vanuan** [comment]
Here's an example that might help:
https://hackernoon.com/keep-your-ui-clean-with-redux-middleware-752383016c50
