### ISSUE TITLE
[Question] Initialize State Asynchronously

### ISSUE THREAD

**Issue by hnordt** [rackt/redux#1368]
I'm wondering how to initialize state asynchronously.

Something like:

```js
myAsyncStorage.getItem('state').then(initialState => createStore(rootReducer, initialState))
```

Any ideas?

**Comment by gaearon** [comment]
Either don’t create a store yet or do that via a special action. See discussion in https://github.com/rackt/redux/pull/658 for an example.

**Comment by hnordt** [comment]
Thank you!
