### ISSUE TITLE
[todomvc] todomvc-app-css/index.css

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [rackt/redux#1373]
Hi,

I'm so sorry to ask a stupid question, but I don't get how styles are dealt with.

In the **index.js** I see

`import 'todomvc-app-css/index.css'`

...which confuses me a lot. Could you please give me a hint?

Thanks.

**Comment by gaearon** [comment]
We are using Webpack for bundling in examples. Webpack lets us configure “loaders” (compile-time transformations). We are using `style-loader` which turns CSS into JS applying that CSS to the page.

See https://webpack.github.io/docs/stylesheets.html.

Note that this is unrelated to Redux. You can use a different bundler, or a different way of applying CSS, if you like.

**Comment by DFallas** [comment]
If someone is still struggling with this you need to
1. add another module loader in the webpack.config.js
`const ExtractTextPlugin = require('extract-text-webpack-plugin');`
`      {
        test: /\.(css|scss)$/,
        loaders: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'css-loader?!sass-loader!postcss-loader'
        })
       },`
2. add the respective plugin:
`    new ExtractTextPlugin('index.css'),`
3. include file as follows in index.js:
`import 'style-loader!css-loader!sass-loader!./index.scss';`
