### ISSUE TITLE
Calling next middleware more than once?

### ISSUE THREAD

**Issue by svrcekmichal** [rackt/redux#1379]
Hi,

I' m building quite a big application, and what i want to ask is, is it anti-pattern or is there some cons in calling next in middleware twice? Or more times? To give you example, i'm using jsonapi.org on my api backend so data will be in some form received by my application. so there is simple middleware which will fetch data, but then i want o call next twice.

first time it will by action, which will have request and response, for better handling which page of some entities was fetched and for better handling frontend

second time it will be new action with own type and this one will be handled by json api middleware, and it will create flat structure of relations end entities in my store

The question is simple, is there any cons against calling next middleware twice from previous action, with different actions, or to create new action in middleware? Or is there some better solution to my problem?

**Comment by svrcekmichal** [comment]
Now i think about it, json api can be reducer which will manage response from action, but is it wise to make reducer not checking type, but checking if response payload is certain form?

**Comment by gaearon** [comment]
This sounds sensible to me.

**Comment by sompylasar** [comment]
I think it's OK to call "next" multiple times, because "next" is expected to behave like the "dispatch" function (and the last middleware gets exactly it behind "next").
