### ISSUE TITLE
npm install fails on Windows

### ISSUE THREAD

**Issue by jkells** [rackt/redux#1380]
Here is the output.

C:\projects\thirdParty\redux\build\use-lodash-es.js:4
      ImportDeclaration(path) {
                       ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\projects\thirdParty\redux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:204:20
    at Array.map (native)
    at Function.normalisePlugins (C:\projects\thirdParty\redux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:182:20)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:es"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! redux@3.3.1 build:es: `cross-env BABEL_ENV=es babel src --out-dir es`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux@3.3.1 build:es script 'cross-env BABEL_ENV=es babel src --out-dir es'.
npm ERR! This is most likely a problem with the redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_ENV=es babel src --out-dir es
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\thirdParty\redux\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! redux@3.3.1 build: `npm run build:commonjs && npm run build:es && npm run build:umd && npm run build:umd:min && node ./build/es3ify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux@3.3.1 build script 'npm run build:commonjs && npm run build:es && npm run build:umd && npm run build:umd:min && node ./build/es3ify'.
npm ERR! This is most likely a problem with the redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:commonjs && npm run build:es && npm run build:umd && npm run build:umd:min && node ./build/es3ify
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\thirdParty\redux\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! redux@3.3.1 prepublish: `npm run clean && npm run check:src && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux@3.3.1 prepublish script 'npm run clean && npm run check:src && npm run build'.
npm ERR! This is most likely a problem with the redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run check:src && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\thirdParty\redux\npm-debug.log

**Comment by jkells** [comment]
Looks like I had an old version of NodeJS install disregard!! <3

**Comment by gaearon** [comment]
The underlying problem is that you are processing node_modules with Babel. Please don’t do this. We make no guarantees that Redux will work if you compile it again with Babel.

When you use Babel, please disable it for node_modules.

**Comment by gaearon** [comment]
Hmm. Disregard my previous comment. I see now you ran npm install in the project itself.

**Comment by jkells** [comment]
Hey gaeron,

I was running an old version of NodeJS. Updating to the latest version fixed it for me. 

Thanks.

**Comment by jdalton** [comment]
This is because [build/use-lodash-es.js](https://github.com/reactjs/redux/blob/master/build/use-lodash-es.js) uses the ES6 method shorthand and is not being transpiled. If the goal is not to be transpiled then it can simply be written in the ES3/5 flavor. If it is to be transpiled then it needs a config tweak.

@gaearon Which one are you wanting?

**Comment by gaearon** [comment]
We should amend Contributing guide to say that we expect Node >= 4 for contributors. If Node 4 doesn’t support the shorthand notation I am happy to accept a fix to use the ES5 syntax.

**Comment by jdalton** [comment]
Cool. cool. Though it seems like that file is the the only stickler at the moment.

Stats:
<table>
<tr>
<th>count	</th><th>feature_version</th><th>%age</th>
</tr>
<tr>
<td>558088794</td><td>0.12</td><td>29.9%</td>
</tr>
<tr>
<td>483561869</td><td>4</td><td>25.9%</td>
</tr>
<tr>
<td>227270007</td><td>5</td><td>12.2%</td>
</tr>
</table>
https://twitter.com/seldo/status/672569831565078528

<img src="https://cloud.githubusercontent.com/assets/4303/13094825/24c93d10-d4c2-11e5-8384-81180b013d7f.png" width=50%>
https://twitter.com/JavaScriptDaily/status/677741377745240064

**Comment by gaearon** [comment]
My guess is it’s more common on developer machines than in production. Individual contributors are also likely to have something like `n` or `nvm`. Also React requires Node 4 for contribution (because [Jest](https://facebook.github.io/jest/) wants it), and they’re pretty conservative :smile: .

Mainly I just don’t want to break people when something changes in build process because I don’t plan to test the build on Node 0.12 and such.

**Comment by jdalton** [comment]
> Mainly I just don’t want to break people when something changes in build process because I don’t plan to test the build on Node 0.12 and such.

Travis makes that p easy. It's your call though, no worries.

**Comment by gaearon** [comment]
What versions do you think is reasonable to support? I’m not sure if tests in examples would run in 0.12 because they use `jsdom` and I’m not sure which version of Node it requires.

**Comment by jdalton** [comment]
Ah, if it's a mega pain then don't worry about it.
If it was just a line in a travis.yml and using ES5 then I'd say go for it. I support back to Node 0.10 because it's painless. If I ran into roadblocks though I'd start dropping.

**Comment by jdalton** [comment]
On the topic of jsdom would you dig a browser runnable version?

**Comment by gaearon** [comment]
We only use jsdom to help React not crash when initializing but this really has to be fixed in React. We don’t *really* require jsdom in tests, and I want to drop it when related React issues are fixed (might even be in master).

The reason I like Node-only testing is it’s easier to set up, run on Travis, and people are usually happier with it than with setting up something like Karma.

**Comment by sompylasar** [comment]
I personally had troubles with Webpack + Babel 6 on Node 0.12 -- it just hanged on a large app build. Resolved after updating to Node 5.

**Comment by gaearon** [comment]
Babel 6 is known to be slow with npm@2. Not sure if any Nodes currently include npm@3 as a default.

**Comment by jdalton** [comment]
@gaearon 
> The reason I like Node-only testing is it’s easier to set up, run on Travis, and people are usually happier with it than with setting up something like Karma.

Once you no longer need jsdom I'll hook you up [with cross browser testing](https://saucelabs.com/u/lodash).

**Comment by sompylasar** [comment]
> Not sure if any Nodes currently include npm@3 as a default.

Node 5 comes with npm@3

**Comment by gaearon** [comment]
Browser testing sounds great for the core. (To make sure we don’t regress on something silly.) Not sure it makes as much sense for examples. One of the benefits of using React and Redux is you can test both your logic and UI without the browser.
