### ISSUE TITLE
react redux calling async method and dispatch on loop

### ISSUE THREAD

**Issue by aaeronn** [rackt/redux#1381]
Lets say I am calling a dispatch method in my actions :

```js
return dispatch(add_data(data)).then(function(response){console.log("Done")}
```

and my `add_data` method looks like:

```js
export function add_data(data){
  return (dispatch, getState) => {
    for(var i in data){
      var data = {'url': data[i]}
      return dispatch(myApi({url: "some_url", method: "POST", data: data,}
        )).then(response => {
        console.log(response)
        return response.json()
      }).then(response => {
        console.log(response)
        return dispatch({response, type: types.ADD_DATA})
      })
    }
  }
}
```
It is working for only first data. Only first data is dispatched. It is inside loop and I expect it to dispatch for all the data from loop.

If I dont user `return` in my dispatch it does not wait for function to complete

How can I achieve this ?

Thank you

**Comment by danielepolencic** [comment]
I guess you need to wait for all the promises to be resolved before calling the `return`. At the moment, once you're in the first iteration of the loop you hit `return` and immediately get out of the function.

You can fix your code by using `Promise.all`:

```javascript
return (dispatch, getState) => {
  var allPromises = new Array(data.length);

  for(var i in data){
    var data = {'url': data[i]}
    allPromises[i] = dispatch(myApi({url: "some_url", method: "POST", data: data,}))
    .then(response => {
      console.log(response)
      return response.json()
    }).then(response => {
      console.log(response)
      return dispatch({response, type: types.ADD_DATA})
    })
  }

  return Promise.all(allPromises);
}
```

**Comment by aaeronn** [comment]
Thank you I will try this out

**Comment by aaeronn** [comment]
Thank you that was so much helpful
