### ISSUE TITLE
Question: Retry failed action in single flow

### ISSUE THREAD

**Issue by tristangodfrey** [rackt/redux#1383]
How would one implement the following flow?

Dispatch API action > API middleware executes request > Request fails (401, auth token needs to be refreshed) > Refresh auth token (refresh token action called from middleware) > Re-execute original action

Is it possible to do this all in the flow of a single action? I can post code if necessary, hope my question is clear enough.

**Comment by gaearon** [comment]
I would say that I recommend https://github.com/yelouafi/redux-saga for async control flow like this.

**Comment by tristangodfrey** [comment]
Thanks @gaearon I'll check that out.
