### ISSUE TITLE
Minification warning on other environments not called "production"

### ISSUE THREAD

**Issue by dsteinbach** [rackt/redux#1384]
Is it necessary to warn users that they are running a minified version of redux? I am just wondering because our production env var is called "prod", and we also would prefer not seeing this warning in our integration or staging environments.  Maybe it should only warn for "dev" or "development"?

**Comment by gaearon** [comment]
>I am just wondering because our production env var is called "prod", and we also would prefer not seeing this warning in our integration or staging environments. 

Which means that you are currently running a development build of Redux (and probably React too, which is pretty slow compared to the real production build).

This has been discussed before, so please take a look through the discussion in https://github.com/rackt/redux/pull/1075, including the inline comments at the bottom.
