### ISSUE TITLE
https://ngva-test.synxis.com/

### ISSUE THREAD

**Issue by saitejareddy07** [rackt/redux#1386]
its not working in IE11 please help me on this qucik on i dont know how to fix
https://ngva-test.synxis.com/

**Comment by gaearon** [comment]
Unfortunately we can’t guess what the issue is without details about the error and the relevant source code.

**Comment by saitejareddy07** [comment]
Thanks for Reply, i fixed it

<td>{hotel.HotelName}<a onClick={this.props.renderHotelDetailsModal.bind(this, hotel)}><i style={{float:'right'}} className="fa fa-info-circle" style={{'cursor' : 'pointer'}}></i></a></td>

<td>{hotel.HotelName}<a onClick={this.props.renderHotelDetailsModal.bind(this, hotel)}><span  className="fa fa-info-circle" role= 'view hotel details in new window' style={{'cursor' : 'pointer',float:'right'}}></span></a></td>
   <td>Not Implemented</td>
