### ISSUE TITLE
incorrect code in documentation?

### ISSUE THREAD

**Issue by benny856694** [rackt/redux#1387]
see my question on SO: [Spread operator on object in redux doc](http://stackoverflow.com/questions/35340408/can-spread-operator-be-applied-to-object/35340448#)

**Comment by gaearon** [comment]
Good point. We need to fix this to use `Object.assign` because our docs should be ES2015 and should not depend on future proposals. Would you like to send a PR?

**Comment by benny856694** [comment]
@gaearon , ok, no problem
