### ISSUE TITLE
Clear all listeners

### ISSUE THREAD

**Issue by sickDevelopers** [rackt/redux#1389]
Hello, is it possible to remove all listeners from a store while keeping the state untouched?

That would be helpful within an Angular application: keeping the store as a separate module is useful to have the application state available everywhere. But everytime a controller that calls a subscription is istantiated, the listener stack grows with the same listener (e.g. after a logout/login)

Right now the methods exposed by the Redux engines are getState, subscribe, dispatch and replaceReduce, IMHO it would be useful to have a method like clear

```
function clear() {
    listeners = [];
}

...

return {
    ...
    clear: clear
}
```

Thank you
Cheers

**Comment by gaearon** [comment]
> But everytime a controller that calls a subscription is istantiated, the listener stack grows with the same listener (e.g. after a logout/login)

Whatever piece of code is calling `subscribe()` is responsibly for unsubscribing later.

```js
const unsubscribe = store.subscribe(() => { ... })

// later
unsubscribe()
```
