### ISSUE TITLE
Is bounded actions example ok?

### ISSUE THREAD

**Issue by mauron85** [rackt/redux#1391]
Hi, I've just jumped into Redux and like it very much so far.
Not sure if I understand completely how it works, but in [Actions](http://redux.js.org/docs/basics/Actions.html) there is section about bounded action creator

>
  Alternatively, you can create a bound action creator that automatically dispatches: 
  const boundAddTodo = (text) => dispatch(addTodo(text))
  const boundCompleteTodo = (index) => dispatch(completeTodo(index))

If I understand correctly that is possible because of redux-thunk which has to be registered as middleware. And if so, shouldn't it be then be:

```
const boundAddTodo = (text) => (dispatch) => dispatch((addTodo(text)))
```
[Babel try it](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=const%20boundAddTodo%20%3D%20%28text%29%20%3D%3E%20dispatch%28addTodo%28text%29%29%0Aconst%20boundAddTodo2%20%3D%20%28text%29%20%3D%3E%20%28dispatch%29%20%3D%3E%20dispatch%28%28addTodo%28text%29%29%29)

**Comment by gr0cks** [comment]
This has nothing to do with Redux Thunk. The term 'bound action creator' refers to the result of composing dispatch and an action creator. When this function is called it automatically dispatches the action creator. Passing this function to components allows them to be decoupled from dispatcher and actions.

It would look like this:
`
const boundAddTodo = (text) => dispatch(addTodo(text))
<Todo onClick={boundAddTodo}  />
`

**Comment by gaearon** [comment]
This is an example from early version of docs and isn’t very relevant today.
Maybe we should just remove it as it confuses people.

Yes, the original point was to show that `addTodo()` by itself doesn’t do anything and you need to call `dispatch(addTodo())` to actually cause the action to happen. At which point you can “bind” it to a certain `dispatch` function so you can just `addTodo()`. You can do this by hand, with `bindActionCreators()`, or you can use React Redux which does this for you.
