### ISSUE TITLE
Browser bundle

### ISSUE THREAD

**Issue by vipulnsward** [rackt/redux#212]
Any plans for a browser bundle for use?

**Comment by gaearon** [comment]
I think that the NPM package should include the browser bundle.

**Comment by valscion** [comment]
Yes the NPM package contains `dist/redux-react.js` and `dist/redux-react.min.js` files which are usable in browsers directly

**Comment by gaearon** [comment]
I don't want to put compiled dist into the repo, but I'd like to add it to cdnjs instead.
Will do by 1.0 I guess.

**Comment by gaearon** [comment]
Submitted as https://github.com/cdnjs/cdnjs/pull/5371.
