### ISSUE TITLE
Example request: a login form for a protected resource with routing

### ISSUE THREAD

**Issue by sintaxi** [rackt/redux#279]
Hey there, I'm new to redux so I'm not yet aware of it capabilities/limitations. However, I'm finding the usefulness of todo lists have seriously run its course and most Flux libraries &/OR example projects I have seen fall flat on their face once you start to handle very common use cases. Here are a few things I would like to see in at least one example project.

I understand that there is no one true way to approach these tasks. I just want to see one example that successfully incorporates these paradigms.

- **authentication** - most applications have a dramatic change in UI when the user is authenticated. Show how to go from splash page, to login screen, to main application for authenticated user?

- **session handling** - seems reasonable to store access token in localStorage so the user remains logged into the app when they return. What layer is responsible to store the token. When should the token be read/removed (logout).

- **speaking to an API** - what part of the application should make API calls? How does that layer fetch the access token to send along in the API request? If the token is missing or invalid how do you change the state of the application to clear the session and prompt the user from credentials? Can this be done without losing the action of the user? How about when the user makes several login attempts?

- **validations** - How to handle validation messages coming back from an API? Where should the state live. How should it be accessed? How/when should it be cleared and by what part of the application?

- **routing** - general URL stuff. Linking to a protected resource which would prompt the user to login, then show the resource if/when authenticated/authorized.

- **form handling** - How to capture data from a form and do something useful with it. FWIW - this seems to be the main thing that most example projects cover (eg. the infamous TODO list).

To me all these things are pretty much essential use cases for a front-end project and it would be super valuable if this was either demonstrated in an example project or at least spoken to so that it is implied how to do it.

Hope this helps.

**Comment by theaqua** [comment]
I agree. It are common use cases (especially auth, because everything else can be solved by correct response handlers) and small examples will be very helpful. It doesn't hard solve those problems independently, but if community or maintainers can make small solid demos, why not.

**Comment by godcore** [comment]
I think it would be better if we had demo that shows all of this features playing together, as most of the apps have them all.

**Comment by emmenko** [comment]
It's a good point, thanks for pointing it out!
If you look at some of the [full examples](https://github.com/gaearon/redux#async-and-universal-examples-with-routing) if you will find most of those parts implemented, so it's a good starting point. 

I guess those use cases should also be well-documented in the [new documentation](https://github.com/gaearon/redux/pull/140).

**Comment by sintaxi** [comment]
Thanks @emmenko. I have an opportunity to dig further into this today.

Do you know of any examples where you have two different stores sharing data or one store calling another?

**Comment by phated** [comment]
@sintaxi I liked [this gist](https://gist.github.com/gaearon/d77ca812015c0356654f) on how to compose stores that need extra information - also, it is the reference gist on how to avoid `waitFor` which I see as a flux anti-pattern

**Comment by gaearon** [comment]
Seems like all of these would be addressed by an example with a login form and a protected resource.

**Comment by eXtreme** [comment]
https://github.com/erikras/react-redux-universal-hot-example
this one is pretty awesome and I leaned a lot from but it lacks "session handling" so storing token in browser *storage, not in session cookie

**Comment by FalloutX** [comment]
I guess It might be better to store tokens in localStorage than to keep them in session. That way user can keep being logged in even after a month or more. That might be a bad also. 

I once used a browser-based attendence system to keep track of which days the user used the app, and then invalidate the token when he's absent for a month or so. I might have sidelined security though.

**Comment by eXtreme** [comment]
@FalloutX  Well that's not the case when your token expires on the server side after like 1 hour. And that's another case to cover - where to put periodical token refresher which is able to get auth data from store and dispatch getToken action. I'm fighting with it right now and any advice would help. :)

**Comment by FalloutX** [comment]
@eXtreme I don't know exactly what you can do right now about it, since I personally store things in localStorage and manage auth token and refresh tokens in there. So if the token is expired, I can still make requests with refresh token.(not a pro)

But @xgrommx has collected a lot of resources on redux here: [awesome-redux](https://github.com/xgrommx/awesome-redux), I guess you can find something useful there for session management.

**Comment by gaearon** [comment]
Most of this is covered by https://github.com/erikras/react-redux-universal-hot-example.
