### ISSUE TITLE
Update Flux Comparison example with Redux 1.0RC

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#369]
Here it is: https://github.com/voronianski/flux-comparison/blob/master/redux

**Comment by rwillrich** [comment]
I'll take a look at this.

**Comment by gaearon** [comment]
Thanks!

**Comment by rwillrich** [comment]
@gaearon should I only use Babel stage 2 on here too?

**Comment by gaearon** [comment]
@rwillrich Yes, please!

**Comment by rwillrich** [comment]
Ok

**Comment by rwillrich** [comment]
I've submitted a PR to the project -> https://github.com/voronianski/flux-comparison/pull/53/files

**Comment by gaearon** [comment]
Thank you!
