### ISSUE TITLE
Call listeners asynchronously to debounce updates

### ISSUE THREAD

**Issue by wmertens** [rackt/redux#381]
Suppose you have 20 listeners, and you get a bulk update in from the server and dispatch a bunch of actions all at once. Then those listeners will each be called once for each applied action.

I think it would be nice to debounce this with a setTimeout 0 and a dirty flag so they only get called once after the JS event loop clears.

The code in question is at https://github.com/gaearon/redux/blob/848bb8e175715bedaccd10bbcbe62b1dbbe09ffa/src/createStore.js#L109

**Comment by wmertens** [comment]
So the problem is, how to intercept the listener chain using a store enhancer, since the core version will remain as-is.

Alternatively, debounce actions and bulk-update state with before passing an action with the complete new state to a wrapped store with a single reducer?

**Comment by wmertens** [comment]
Explanation about why to keep core version pure:
![screen shot 2015-07-31 at 15 05 58](https://cloud.githubusercontent.com/assets/54934/9007854/b4adc088-3795-11e5-8d10-9a600ed86a01.png)

**Comment by gaearon** [comment]
This is where I chime in and advertise how fun our Slack channel is and how you should totally join it

**Comment by wmertens** [comment]
Seconded - http://reactiflux.com, channel #redux

**Comment by tappleby** [comment]
I just published a package [redux-batched-subscribe](https://github.com/tappleby/redux-batched-subscribe) which allows for debounced subscribe notifications (or using `batchedUpdates` from react)

**Comment by gaearon** [comment]
redux-batched-subscribe appears to solve this problem.
