### ISSUE TITLE
New docs have bad UX for flaky internet connection

### ISSUE THREAD

**Issue by valscion** [rackt/redux#383]
First of all, I want to say there has been excellent work going on with the new docs (#349). It works great on mobile, too!

It's only now that I'm reading the new docs via a flaky 3G connection that I find it very difficult to navigate those gitbook pages due to there being **no loading spinner** (or similar) whatsoever! I end up accidentally swiping through many pages due to page load times being large.

Could there be something showing the loading state in the docs if e.g. loading a page takes more than 500ms or something?

**Comment by gaearon** [comment]
I'd appreciate somebody helping out: https://github.com/gaearon/redux/issues/345

Ideally I want a lighter theme that is less fancy and more like a simple static website. Maybe @AaronO could suggest something?

Ideally I'd prefer a look and feel closer to this: http://gaearon.github.io/react-dnd/docs-overview.html.

**Comment by gaearon** [comment]
Closing in favor of #345.
