### ISSUE TITLE
Redux / Flux tutorial

### ISSUE THREAD

**Issue by happypoulp** [rackt/redux#385]
Hi,

I don't know if it may be of some help to anyone but I am trying to write a kind of tutorial about flux and redux. It's still a WIP and is accessible here: https://github.com/happypoulp/redux-tutorial

I am writing this tutorial to show as simple as flux is when using redux (and totally thanks to redux) and using my own words. It targets audience that maybe struggle a bit about flux concepts and may have been lost through numerous other flux implementations.

If you think that this is interesting enough and can turn somehow into a contribution to Redux, let me know!

Thanks.

**Comment by EJIqpEP** [comment]
I just started learning redux and it's difficult for me to understand all methods and flow of it. I understand that docs for 1.0 version are not ready yet but as for me they are very short. 
Thanks for your repo I read all your guides. They are very simple and clear. As for me it's a good idea to merge them somehow to official redux docs.

**Comment by theaqua** [comment]
@EJIqpEP did you see [new docs](http://gaearon.github.io/redux/)? It's incomplete, I agree, but I started a new project from scratch with this documentation and it was very helpful.

**Comment by happypoulp** [comment]
@EJIqpEP , I don't mean to replace official documentation. I am sure that coming documentation for Redux 1.0 (http://gaearon.github.io/redux/) will answer lots of question that I had, when trying to learn Flux through various implementations.
My initial intention was more to tell a story that could take someone from almost no knowledge about Flux and to have him walk step by step, introducing one concept after another to finally show him that Flux is not that much of a mystery.

To be honest I hadn't read new docs when starting my tutorial and now that I just browse them I think that they will fulfill the same contract in a more structured way. It's mandatory for official documentation to follow a structure that is easily browsable and that can provide in an instant technical answers. My tutorial is not written in the same spirit and would not be of much help in that perspective.

I will probably continue writing tutorial since I found out that it is a good training exercise to confirm my understanding of Flux and Redux. However I'll close this issue since it's probably not a good place to have them within Redux as it would be interpreted as a documentation duplicate.

Thanks!

**Comment by sapegin** [comment]
It would be nice to have a readable version too.

**Comment by gaearon** [comment]
I really like your tutorial. We'll link to it from the docs. I'll keep it open so I don't forget to.

**Comment by happypoulp** [comment]
@gaearon I am glad to here that, thanks!

**Comment by gaearon** [comment]
Done in https://github.com/rackt/redux/commit/a9aaebb70c45e3913d0c6430bfb3739e6ad42e94.

**Comment by happypoulp** [comment]
Thanks! New docs are awesome!
