### ISSUE TITLE
How to clear app state?

### ISSUE THREAD

**Issue by yanivtal** [rackt/redux#423]
I want to reset the app state before every test run but I cant seem to do it.

I've tried:
* Creating a new store
* Dispatching a RESET_APP_STATE action which the root reducer handles and returns an empty state for

Neither of these seem to work. Whenever I call reducer() without passing in a state, I get back the previous state. I would expect to get back the initial state for each reducer. What am I doing wrong?

What's the best practice for resetting app state between test runs?

**Comment by iclanzan** [comment]
Would help if you pasted some code here so we could give some meaningful advice.

**Comment by yanivtal** [comment]
It's quite simple.
```
import * as reducer from './reducer';

// At some later time I want to reset the state to the initial state so I try
function getInitialState() {
    return reducer(); // Calling this with undefined state and action
}
```
getInitialState() returns the current state, not the initial state as I would expect..

**Comment by HeyImAlex** [comment]
If your `reducer` function is pure then that shouldn't be possible.

So maybe your reducer function isn't pure? I'd need more code to tell you what's happening.

**Comment by goatslacker** [comment]
Chances are you're mutating an object reference somewhere, make sure you copy things whether it's arrays or objects rather than mutating them.

**Comment by yanivtal** [comment]
They are pure. So if that's the case I can look elsewhere for bugs.

I guess conceptually though, I'd still like a good answer to the right way to structure this since it's a very common operation. Hopefully everyone's testing, so everyone needs a way to quickly reset the whole app state.

How would you recommend doing that? I don't like my solution of wrapping the root reducer and handling a global action to RESET_APP_STATE. Any other suggestions?

**Comment by mindjuice** [comment]
> They are pure.

As much as I'd like to believe you... :smile:... I can't ignore the fact that calling a function with no arguments (your ``reducer()``) and having it return something that was not either passed to it or defined within it, means that it is not pure.  It's also acceptable to access ``const`` data, as recommended for [Redux reducers](http://gaearon.github.io/redux/docs/basics/Reducers.html) to set the default argument for state.

My best guess would be that you are overwriting your ``initialState`` with your current state somehow, either within your reducer or elsewhere.  Is your ``initialState`` declared ``const``?

**Comment by knowbody** [comment]
how does your reducer look like?

**Comment by gaearon** [comment]
This is hard to discuss without a real example. Please provide us with an example so we can figure out a solution.

**Comment by yanivtal** [comment]
Sorry for dropping the ball y'all. My problem was actually rendering directly into the DOM instead of using the TestUtils.renderIntoDocument. Thanks!
