### ISSUE TITLE
Links to dev tools & slider monitor?

### ISSUE THREAD

**Issue by ericelliott** [rackt/redux#434]
I was about to add Redux to the [Essential JavaScript Links collection](https://github.com/ericelliott/essential-javascript-links#react) when I noticed something. I don't really consider this a complete solution without both the devtools and the [slider monitor](https://github.com/calesce/redux-slider-monitor) (which I just learned about today).

Those are critical features of Cerebral, and I'm not going to swap out Cerebral without them, even though I really like the "everything is a pure function" approach of Redux (a lot).

Maybe it would be handy to include links to recommended companion libraries in the README? =)

**Comment by gaearon** [comment]
Feel free to revisit in a couple of months then. :-)

Redux is stable. DevTools (and different monitors) are experimental.

People started using Redux so fast that I *have to* focus on fundamental stuff first. This means "writing docs about AJAX request" or "integrating with React Router" has a much higher priority than "teaching people to use DevTools".

DevTools are still experimental. Early adopters know where to look for them. Gradually, as they mature, we will talk about them more, and have official integration guides. Right now this is just not a priority compared to other things.

**Comment by ericelliott** [comment]
Sure. =)

**Comment by gaearon** [comment]
We link to DevTools from README now, as well as from “Ecosystem” doc page.
We link to the slider from DevTools' README.

**Comment by ericelliott** [comment]
:guitar: :notes:
