### ISSUE TITLE
Add “Contributing” doc

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#443]
* Describe expected setup (e.g. https://github.com/gaearon/redux/issues/438#issuecomment-129225126)
* Describe npm tasks (linting, etc)
* Something else?

**Comment by knowbody** [comment]
add this https://github.com/gaearon/library-boilerplate/pull/6 as how the PR should look like :smile:

**Comment by hedgerh** [comment]
Not sure if anyone has started on this yet, but I'm working on a draft now.   Going to describe a basic setup, describe the npm tasks, and refer to the code of conduct.  I'm not exactly sure what needs to be added based on https://github.com/rackt/redux/issues/438#issuecomment-129225126 , but I'll open the PR for feedback when a draft is ready. :octopus:

**Comment by ellbee** [comment]
Closed by #1124
