### ISSUE TITLE
How redux project managed to have an integration test?

### ISSUE THREAD

**Issue by leonli** [rackt/redux#469]
http://gaearon.github.io/redux/docs/recipes/WritingTests.html

I just read the new document, it's great and it points out that how we can test the `redux` project for each of its component (`React components` / `actions` / `reducers`), but my question would be how could we have the integration test for the entire project if we are using `redux`, or is that even possible?

**Comment by knowbody** [comment]
I want to answer this question properly, so I'll update my answer when I find more time. For now just want to add this video which may be useful. @gaearon maybe we can add it to the doc itself?

Property Testing with React:
https://vimeo.com/122070164

**Comment by gaearon** [comment]
This doesn't appear to be a Redux-related question. Redux lets you test every part separately. If you want to “test everything”, you can use a traditional solution like Selenium. If you're satisfied with just testing the Redux-controlled part, you can call `store.dispatch` on a list of predetermined actions in your test, and then make assertions on DOM, but this is not specific to Redux.
