### ISSUE TITLE
Communication between components

### ISSUE THREAD

**Issue by i4got10** [rackt/redux#477]
Faced the problem, cant understand how to establish communication between components.

For example. I have a component with the map(Map), it is drawn objects. There is a list of objects(Menu) showed somewhere else. 
When user click on item in the Menu, I want show object on the Map(focus on it).

With flux, I can easily throw action LIST_ITEM_CLICK, and subscribe to this event in the Map and there it is easy to perform steps I need.
With redux, I can only write something to state. What I need to do in this case?

I really dont want to store all map state(center, bounds, zoom, etc) in App state and rerender map every application state change, cause its not matter to me when user drag the map or change the zoom

**Comment by gaearon** [comment]
Even in Flux, you subscribe to state updates, not to actions.

Have you had a chance to read the tutorial?
It shows how to build a simple app with Redux.

http://gaearon.github.io/redux/docs/basics/index.html

**Comment by gaearon** [comment]
I'm closing, as there appears to be a misunderstanding of how Redux (or Flux) works, and what problems it is supposed to solve. If you still have this question after reading the tutorials in the docs and running the examples, please provide us with a code sample so we can discuss it. It's a hard to have an abstract discussion about practical matters.
