### ISSUE TITLE
Support for coffee scripts

### ISSUE THREAD

**Issue by vojtatranta** [rackt/redux#509]
Can we add support for coffee script?
I still find it better than Babel's ES6.
Thanks

**Comment by acdlite** [comment]
CoffeeScript is just JavaScript, so it is fully supported.

```coffee
reducer = (state = 0, action) ->
  switch action.type
    when 'INCREMENT' then state + 1
    when 'DECREMENT' then state - 1
    else state

store = createStore(reducer)

store.dispatch(type: 'INCREMENT')
```

**Comment by ForbesLindesay** [comment]
What does that even mean in this context?  Nothing prevents you using the redux API from coffee script, you just have to translate the examples into the equivalent coffee script.

**Comment by vojtatranta** [comment]
And update webpack config

**Comment by acdlite** [comment]
> And update webpack config

Huh? Please be more specific.

**Comment by vojtatranta** [comment]
For all examples and for every redux template you have to update webackg.config.js so that it could compile coffee too.

**Comment by gaearon** [comment]
Well, we don't use CoffeeScript so naturally our examples configuration doesn't include it. If you want use it, it's up to you to change your configuration.

**Comment by vojtatranta** [comment]
OK, just wanted to include it out of the box.
Thanks for your time guys, great work!
