### ISSUE TITLE
middleware - Why currying rather than (store, action, next) -> 

### ISSUE THREAD

**Issue by phzbox** [rackt/redux#534]
Hi, the new docs are great. One question I had while reading the whole middleware section is why does the middleware has to be curried? Why not simply:

    var store = <..>;
    store.addMiddleware(function(store, action, next) {
      var result = next();
      // whatever
    });

Maybe a quick point explaining in the doc would be helpful.

**Comment by lapanoid** [comment]
Could be both actually (ramda)(http://ramdajs.com/0.17/docs/#curry) works that way.

**Comment by gaearon** [comment]
Sometimes we want to associate some local state with `store` and `next`, like in [rAF scheduler from middleware docs](http://rackt.github.io/redux/docs/advanced/Middleware.html):

```js
const rafScheduler = store => next => {
  let queuedActions = [];
  let frame = null;

  function loop() {
    frame = null;
    try {
      if (queuedActions.length) {
        next(queuedActions.shift());
      }
    } finally {
      maybeRaf();
    }
  }

  function maybeRaf() {
    if (queuedActions.length && !frame) {
      frame = requestAnimationFrame(loop);
    }
  }

  return action => {
    if (!action.meta || !action.meta.raf) {
      return next(action);
    }

    queuedActions.push(action);
    maybeRaf();

    return function cancel() {
      queuedActions = queuedActions.filter(a => a !== action)
    };
  };
};
```

We could have made it `(store, next) => action => ()` but I don't see a problem with just going all the way. You might want some configuration later, at which point `options => (store, next) => action => ()` looks kinda arbitrary.

**Comment by kentor** [comment]
Honestly when I read the docs, specifically this line:

> But there’s also a different way to enable chaining. The middleware could accept the `next()` dispatch function as a parameter instead of reading it from the store instance.

I had *expected* the following:

```javascript
function logger(store, next) {]
  return function dispatchAndLog(action) {
    console.log('dispatching', action);
    let result = next(action);
    console.log('next state', store.getState());
    return result;
  };
}
```

But was instead:
```javascript
function logger(store) {
  return function wrapDispatchToAddLogging(next) {
    return function dispatchAndLog(action) {
      console.log('dispatching', action);
      let result = next(action);
      console.log('next state', store.getState());
      return result;
    };
  }
}
```

I guess I am not satisfied with "I don't see a problem with just going all the way." To me, the problem is that it is neednessly complicated. The call to this in `applyMiddleware`

```
dispatch = middleware(store)(dispatch)
```

could simply be

```
dispatch = middleware(store, dispatch)
```

This also deviates from express' middleware signature: `(req, res, next) => void`.

**Comment by gaearon** [comment]
>To me, the problem is that it is neednessly complicated.

Is

```js
store => next => action => yourcode
```

more complicated to write than

```js
(store, next) => action => yourcode
```

?

I understand your concerns, maybe you're right. Maybe it breaks some use case we haven't considered. I don't know. But this feedback would have been more useful at the time middleware was designed (it was all publicly discussed: #55). Right now there is a lot of middleware in the ecosystem that uses the current signature, and unless you see a way to change it in backwards-compatible way, I don't think “remove `store =>`” is a reason compelling enough to break everyone.

**Comment by karthikiyengar** [comment]
Thanks for the question. I was starting to question my understanding of the middleware lesson by believing that the currying was absolutely necessary :smile:

**Comment by Attrash-Islam** [comment]
I think that once the redux expectation of the function is this signature

```js
const middleware = store => next => action => {
    // do something
}
```

then you can write your middleware curried version as follows:

```js
_.curry((store, next, action) => {
   // do something
})
```

then redux being calling middleware(store)(next)(action) will work with the curried version.

**Comment by ycjcl868** [comment]
Maybe this following the rules of [Lambda_calculus](https://en.wikipedia.org/wiki/Lambda_calculus), it's more functional.
