### ISSUE TITLE
Provider receiving invalid prop supplied to Route

### ISSUE THREAD

**Issue by QuietOmen** [rackt/redux#549]
So I'm not 100% sure that this is a bug or simply something I'm doing incorrect. But I went over my code 30+ times today and I couldn't find anything wrong. I then decided to copy the real-world example over line for line, and I still continued to receive an error. I then decided to do the same thing with the counter example, since it's an easier example, but still the error persisted. Here's the error I'm receiving: 

```
Warning: Failed propType: Invalid prop `component` of type `object` supplied to `Route`, expected `function`. Check the render method of `Provider`.

Uncaught Error: Invariant Violation: Provider.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

I'm not sure what `Route` it is complaining about...initially I was using react-router but then after getting this error I removed it, to help track down the bug. I'm not sure what other file configurations you'd like to see to help track down this bug?? I seriously copied the files over from counter and the other examples but I couldn't get any of them to work. I thought it might be npm cache so I ran npm cache clean, and deleted my node_modules folder. 

Some of the other main pieces I'm using are express, and webpack. Like I said, I'm not sold on the idea that it is actually a bug with redux...but after removing everything but redux and react those are the only options I see left.  Here's my package.json file: 

```
{
  "name": "redux-test",
  "version": "0.0.1",
  "description": "Initial setup for frontend",
  "scripts": {
    "start": "npm install; node server",
    "test": "test"
  },
  "dependencies": {
    "express": "^4.13.3",
    "http-proxy": "^1.11.1",
    "humps": "^0.6.0",
    "isomorphic-fetch": "^2.1.1",
    "normalizr": "^0.1.3",
    "react": "^0.13.3",
    "react-redux": "^0.8.2",
    "react-router": "^1.0.0-beta3",
    "redux": "^1.0.1",
    "redux-logger": "0.0.3",
    "redux-thunk": "^0.1.0",
    "style-loader": "^0.12.3"
  },
  "devDependencies": {
    "babel": "^5.8.21",
    "babel-core": "^5.6.18",
    "babel-eslint": "^3.1.15",
    "babel-loader": "^5.3.2",
    "babel-runtime": "^5.8.20",
    "eslint": "^0.23",
    "eslint-config-airbnb": "0.0.6",
    "eslint-plugin-react": "^2.3.0",
    "react-hot-loader": "^1.2.7",
    "redux-devtools": "^1.0.2",
    "webpack": "^1.11.0",
    "webpack-dev-server": "^1.10.1"
  }
}
```

and here's my webpack.config.js file: 
```
var webpack = require('webpack');
var path = require('path');
var appPath = path.resolve(__dirname, 'src');
var nodeModulesPath = path.resolve(__dirname, 'node_modules');
var buildPath = path.resolve(__dirname, 'public', 'build');

var config = {
  context: __dirname,
  devtool: 'eval-source-map',
  entry: {
    app: [
      'webpack-dev-server/client?http://localhost:3000',
      'webpack/hot/dev-server',
      path.resolve(appPath, 'index.js')],
    vendor: ['react', 'redux', 'react-redux']
  },
  output: {
    path: buildPath,
    filename: '[name].js',
    publicPath: '/build/'
  },
  module: {
    loaders: [
      {test: /\.jsx?$/, exclude: [nodeModulesPath], loader: 'babel'},
      {test: /\.css$/, loader: 'style!css'}
    ]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ]
};

module.exports = config;
```

Other than that, I simply copied over the files/folders from the examples.

**Comment by kirk1h** [comment]
did you forget to export your main component?
```
export default class YourComponent extends React.Component { .. }

**Comment by QuietOmen** [comment]
I was exporting it but not as default... maybe I forgot to import {default as <string>} from '<file>'

I'll double check after I get out of my meeting and let you know. If that's all it is, then I'll be embarrassed that I missed it myself and posted this bug.

**Comment by gaearon** [comment]
Closing because this is not related to Redux.
Please file in [react-redux](https://github.com/gaearon/react-redux) if it is causing the issue somehow.
