### ISSUE TITLE
Mismatch in the suggested ways on how to handle async actions

### ISSUE THREAD

**Issue by matthiasfeist** [rackt/redux#551]
In the docs it is explicitly stated that it is recommended to use the "standard" ways of doing flux actions: https://github.com/acdlite/flux-standard-action
But then in the async-section of the docs and the real world example, different types of actions (like FETCH_POSTS_FAILURE and FETCH_POSTS_SUCCESS) are used which is actively discouraged by the flux-standard-actions document.

So which is the better way to go? I feel that the docs and the examples should be more concise about this...

**Comment by gaearon** [comment]
>In the docs it is explicitly stated that it is recommended to use the "standard" ways of doing flux actions:

We should probably change the docs. I tried to convey that these recommendations are entirely optional:

>Other than type, the structure of an action object is really up to you. If you’re interested, check out Flux Standard Action for recommendations on how actions should be constructed.

“is really up to you”, “if you're interested” probably wasn't enough. :-)

Later, in “async actions”:

>Choosing whether to use a single action type with flags, or multiple action types, is up to you. It’s a convention you need to decide with your team. Multiple types leave less room for a mistake, but this is not an issue if you generate action creators and reducers with a helper library like redux-actions.

In examples, we don't want to use the simplest conventions possible. Whether FSA is a good idea for your app or not, depends on whether you want to use FSA-related middleware, and whether you're interested in such conventions at all. Redux doesn't take any stance here.

I'd welcome a PR to the docs clarifying the existing sentences to better reflect that.

**Comment by matthiasfeist** [comment]
Ah OK, I understand what you mean. It was just that the wording "Standard" suggested for me, that thas is a thing which is the very recommended way of doing things.
But I'll send in a PR
