### ISSUE TITLE
Elm and pattern matching

### ISSUE THREAD

**Issue by joaomilho** [rackt/redux#552]
I'm not sure what is stated here http://rackt.github.io/redux/docs/introduction/PriorArt.html is correct. It says "Unlike Redux, Elm is a language, so it is able to benefit from static typing for actions, and pattern matching.". But Elm doesn't have pattern matching – like in Haskell – apart from the "case" construct. To be specific it supports touples matching on functions.

Do you think it's the case to keep this assertion there?

**Comment by gaearon** [comment]
What I was trying to convey, is that in Elm, actions are typed. Can you edit to better reflect that?

**Comment by gaearon** [comment]
I'm closing but feel free to submit a PR to make this sentence better.
