### ISSUE TITLE
window.__REACT_DEVTOOLS_GLOBAL_HOOK__.on is not a function

### ISSUE THREAD

**Issue by alinz** [rackt/redux#556]
Hi,
I don't know wether this is a redux issue or react-native. As soon as I enable `Inspect Element` I get this error.

![screen shot 2015-08-17 at 11 46 45 am](https://cloud.githubusercontent.com/assets/967050/9309081/768b7bcc-44d5-11e5-8758-d58a6f9e85ef.png)

Any suggestion? Thanks!

**Comment by gaearon** [comment]
I don't see anything specific to Redux here.
