### ISSUE TITLE
Using a database like LokiJS for the Store.

### ISSUE THREAD

**Issue by fifafu** [rackt/redux#557]
Hi,

I'm currently working on a hybrid mobile application and would like to use Redux.
The mobile app needs to have data persistence and handle a lot of data. So far LokiJS (http://lokijs.org/#/ ) looks like a super performant and easy solution.

I'm very new to Redux and I'm not sure if I can make it work with LokiJS. My idea was to use LokiJS in the Reflux store to contain the whole application state. However always creating a copy of the LokiJS database is not really feasible, so I'm not sure how I should handle updating the database (because updating it would be mutating the state, which is bad as far as I understood)

Does anybody have experience with such a use-case and some tips on how to handle this? Are there alternative concepts that would allow for data persistence and similar performance?

Best,
Andreas

**Comment by mindjuice** [comment]
Using a mutative database as your store sounds like a bad idea, as you suggest.

Maybe if you wrapped it in something like Datomic?  But really, what are the features of LokiJS that you want/need to use?

Are you planning to perform a lot of complex queries that can't easily be replaced with map/reduce calls against ImmutableJS or Updeep or even plain objects?

If all you want is local persistence, there is [redux-localstorage](https://github.com/elgerlambert/redux-localstorage), although I'm not sure if this meets your performance requirements.

**Comment by fifafu** [comment]
Thanks, I'll look into Datomic! 

Well, I will have a lot of data to handle and want to keep the app as responsive as possible on all devices. I have yet to run benchmarks whether this could be done with plain javascript objects or ImmutableJS, I just thought LokiJS would be a good option because it would definitely offer the necessary performance. Also I like how easy it is to do queries in LokiJS and the fact that it offers multiple persistence adapters out of the box.

I just noticed that the LokiJS author already has "Create a flux store that utilizes LokiJS" on his roadmap, and there was a nice discussion here: https://github.com/techfort/LokiJS/issues/109

**Comment by gaearon** [comment]
I've heard about Immutable+Redux giving truly impressive performance together so you might want to try it first.

**Comment by gaearon** [comment]
Closing as inactive.
