### ISSUE TITLE
Clearing State Between Views

### ISSUE THREAD

**Issue by davezuko** [rackt/redux#562]
Howdy.

This is more of a general Flux question, but being incredibly interested and impressed with Redux I wanted to see how all of you approached the situation, since I've been wavering on it for a while.

Flux and Redux implementations are both incredibly clear to me when you have state that persists across your entire application - Facebook commonly cites the canonical Todo app or FB chat in their examples. But what do you do when you have disparate views that require entirely new sets of data? By that I mean: what is the best way to discard of the unused data that still lives inside of other stores/reducers.

Creating a global "reset" action seems like a poor (albeit easy) way of doing this, but it severely hampers the ability to create reducers that reliably persist (or don't) between views. Or do you instead have the component/route responsible for triggering the initial load action also trigger an action to clear it? Thinking about it the latter option seems the most intuitive to me, but hopefully somebody more well-versed than me can speak on the issue. Maybe it's just that simple and I'm overthinking it.

If anybody has any recommendations or could point me to some documentation I'd greatly appreciate it. Almost all of the Flux examples I've found implement fairly trivial applications, so I'm still left wondering how reducers are managed in the context of a larger application.

Thanks :)

**Comment by gaearon** [comment]
>Or do you instead have the component/route responsible for triggering the initial load action also trigger an action to clear it?

This is how I'd do it.

**Comment by davezuko** [comment]
Good enough for me, thanks.

**Comment by timwis** [comment]
Do you recommend this be done from `componentWillUnmount`? I've also seen "resetting the state" be done at the top of the action that sets the state.
