### ISSUE TITLE
Ducks, a reducer bundling style proposal

### ISSUE THREAD

**Issue by erikras** [rackt/redux#567]
I find as I am building my redux app, one piece of functionality at a time, I keep needing to add  `{actionTypes, actions, reducer}` tuples for each use case. I have been keeping these in separate files and even separate folders, however 95% of the time, it's only one reducer/actions pair that ever needs their associated actions.

What do you guys think about standardizing a recommended style for bundling action types, actions and the reducer into one file (module)?

### Example

```javascript
// widgets.js

const LOAD   = 'my-app/widgets/LOAD';
const CREATE = 'my-app/widgets/CREATE';
const UPDATE = 'my-app/widgets/UPDATE';
const REMOVE = 'my-app/widgets/REMOVE';

export function reducer(state = {}, action = {}) {
  switch (action.type) {
    // do reducer stuff
    default: return state;
  }
}

export function loadWidgets() = {
  return { type: LOAD };
}

export function createWidget(widget) = {
  return { type: CREATE, widget };
}

export function updateWidget(widget) = {
  return { type: UPDATE, widget };
}

export function removeWidget(widget) = {
  return { type: REMOVE, widget };
}
```
### Rules

A module...

1. MUST export a function called `reducer()`
2. MUST export its action creators as functions
3. MUST have action types in the form `npm-module-or-app/reducer/ACTION_TYPE`
3. MAY export its action types as `UPPER_SNAKE_CASE`, if an external reducer needs to listen for them, or if it is a published reusable library

### Name

Java has jars and beans. Ruby has gems. I suggest we call these reducer bundles "ducks", as in the last syllable of "redux".

### Usage

You can still include them all from an index. You just have to perform a "pluck" operation on each duck to get the reducers.

```javascript
import { combineReducers } from 'redux';
import * as ducks from './ducks/index';

const rootReducer = combineReducers(ducks.map(duck => duck.reducer));

export default rootReducer;
```

It _does_, however, mean that you can no longer get all your actions creators to pass to `bindActionCreators()` via `import * as widgetActions from './actions/widgetActions';`, but I have been increasingly been switching to naming them specifically, so this wouldn't be that bad:

```javascript
import { loadWidgets, createWidget, updateWidget, removeWidget } from './ducks/widgets';

...

bindActionCreators({ loadWidgets, createWidget, updateWidget, removeWidget }, dispatch);
```

### Feedback

I'm mostly just thinking aloud here, but I'd be curious to hear if and why you guys think this is a terrible or great idea.

**Comment by nhagen** [comment]
I think this a perfectly valid approach, but one wonderful feature of redux
is that you can do pretty much whatever you want. As a result there are
likely too many ways, each with its own merits, to have them in the
documentation. This idea might get more traction as a blog post when people
seek out different ways to structure their application.

I don't think saying this is the recommended way helps the redux ecosystem.
In fact, it probably hurts it because people might think it's the only way,
and it might not work for everyone.

Also, a variation of this which I've seen is having components in their own
directories with an index. This way you don't have everything in a single
file, such can get gnarly.

**Comment by gaearon** [comment]
>This idea might get more traction as a blog post when people seek out different ways to structure their application.

+1

**Comment by quirinpa** [comment]
It totally makes sense to me erikras ;)

**Comment by tacone** [comment]
Hello @erikras, I found myself doing something similar while playing with your boilerplate. I began grouping modules in their own folder (even the smart components), then declaring the actions right in the reducer file, and so on. Nice to see you went even further.
In some way, you're "separating concerns".

**Comment by erikras** [comment]
Thanks everybody. I've duckified my example repo and moved this proposal document to [its new canonical home](https://github.com/erikras/react-redux-universal-hot-example/blob/master/docs/Ducks.md).

**Comment by gaearon** [comment]
Nice! What about the more complex case where many reducers might care about the same action? Use cases I have in mind:

1. Optimistically updating different parts of the state tree in response to something that hasn't been confirmed yet
2. Generic [error handling](https://github.com/rackt/redux/blob/c6ac7ab497c570a54c3fccbb4f63fb6aef469e1d/examples/real-world/reducers/index.js#L17-L30) or [response handling](https://github.com/rackt/redux/blob/c6ac7ab497c570a54c3fccbb4f63fb6aef469e1d/examples/real-world/reducers/index.js#L6-L15)

**Comment by erikras** [comment]
@gaearon See the "MAY" rule. I suppose that exporting an action might mess up the `import *` for action creators, but tough.

**Comment by whodidthis** [comment]
In my opinion export all the action creators as default; the reducer is easily destructurable:
```js
export default { loadWidgets, createWidget, updateWidget, removeWidget }
```

**Comment by matthewmueller** [comment]
Started going down this route, but the more I think about it the more I think the reducer is application-specific, while the actions and actions creators can be shared. 

Here's an example: https://github.com/callum/redux-routing/blob/master/src/reducer.js#L4-L11

This is a module for doing routing, I found their decision to name it `href` conflicted with other state in my application. For this reason, I see the shareable part being the actions, and how you handle this stream of actions data (update state with payload, ignore payload, reformat payload) is application-specific.

Interested to get your thoughts.
