### ISSUE TITLE
error when use redux @connect and this.context.router

### ISSUE THREAD

**Issue by tlightsky** [rackt/redux#589]
I want to use it like this:

```javascript

@connect(state => state)
class MessageComposer extends Component {

  componentWillMount() {
    // send login action
    const { dispatch } = this.props;
    dispatch(checkLogin(this.context.router));
  }

  render() {
    return (
      <div>
        <h1>MessageComposer</h1>
        <Link to='/login' >GO!</Link>
      </div>
    );
  }
}

MessageComposer.contextTypes = {
  router: React.PropTypes.object,
};

export default MessageComposer;
```

but it would give me some error like this
```
Uncaught Error: Invariant Violation: Could not find "store" in either the context or props of "Connect(MessageComposer)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(MessageComposer)".
```

after I remove the decorator and change it like this 

```javascript
export default connect(state => state)(MessageComposer);
```
it would work

if i remove router context declare,it would work too

ps:
```
    "react-router": "^1.0.0-beta3",
    "react-redux": "^0.8.0",
    "redux": "^1.0.1",
```

**Comment by timdorr** [comment]
Is that component wrapped in a `<Provider>` component?

**Comment by tlightsky** [comment]
yes, if I remove contextTypes,it would work, and dispatch the action

**Comment by timdorr** [comment]
If you *remove* `contextTypes`? That's not supposed to work that way. React only passes context if you request it via `contextTypes`.

But that doesn't address what I asked. Are you wrapping this in a `<Provider>` component higher up?

**Comment by tlightsky** [comment]
yes, I wrap ```<MessageComposer> ```in a ```<Route> ```,```<Route>``` is in``` <Router>```
and I wrap the ```<Router>``` in ```<Provider>```
```javascript
  React.render(
    <Provider {...{ store }}>
      {() => <Router {...{ history }} />}
    </Provider>,
    document.getElementById('mainPage')
  );
```

If I remove contextTypes, this.context.router wouldn't work,but @connect would work,and I can get dispatch from this.props

**Comment by miafmira** [comment]
You can declare contextTypes as static class prop like this:
```
class MessageComposer extends Component {
  static contextTypes = {
    router: React.PropTypes.object,
  }
  //...
}
```

**Comment by timdorr** [comment]
Your component's own `contextTypes` won't conflict with `connect()`. It creates a higher-order component, so it has it's own context and therefore [it's own local `contextTypes`](https://github.com/rackt/react-redux/blob/d5bf492ee35ad1be8ffd5fa6be689cd74df3b41e/src/components/createConnect.js#L82-L84).

**Comment by tlightsky** [comment]
@miafmira thanks

**Comment by tlightsky** [comment]
@timdorr that's the point I want to figure out,if I use 
```
export default connect(state => state)(MessageComposer);
```
it's ok

**Comment by timdorr** [comment]
The decorator syntax is essentially desugars to the same thing. Are you using babel with at least stage 1 enabled?

**Comment by tlightsky** [comment]
after I change code to syntax @miafmira suggested before
```javascript
class MessageComposer extends Component {
  static contextTypes = {
    router: React.PropTypes.object,
  }
  //...
}
```
it would work

this syntax
```javascript 
MessageComposer.contextTypes = {
  router: React.PropTypes.object,
};
```
wouldn't work

**Comment by timdorr** [comment]
Yes, that is correct. The way `static`s desugar is slightly different than just setting a property on the class.

**Comment by gaearon** [comment]
Either use ES7 proposal syntax both for properties and decorators (dangerous: subject to change), or just use ES6.

```js
@connect(...)
class Stuff {} 

// WON'T WORK
Stuff.contextTypes = {
  router: React.PropTypes.object,
};
```

does not work because you're assigning `contextTypes` to the wrapped component returned by `connect`. It's like doing this:

```js
class Stuff {}
Stuff = connect(...)(Stuff);

// WON'T WORK
Stuff.contextTypes = {
  router: React.PropTypes.object,
};
```

**Comment by SkateFreak** [comment]
i'm getting the same issue:

    @connect(state => state)
    export default class Root extends Component {
        static contextTypes = {
            router: React.PropTypes.object,
        }        
    }

if i remove **contextTypes** it works fine...
@gaearon you mentioned using ES7 for both, am i doing it the wrong way?

**Comment by gaearon** [comment]
My advice today is **don’t use decorators at all**. They are too easy to break with Babel 6, and they are not even an official feature in it. For example, specifying [plugins in a different order](https://github.com/jsstyles/react-jss/issues/32#issuecomment-190819245) can cause decorators to work incorrectly with static properties in Babel 6, which is likely the issue you are experiencing.

Until decorators are officially supported by Babel and the plugin ordering issues are solved, just avoid them:

```js
class Root extends Component {
    static contextTypes = {
        router: React.PropTypes.object,
    }        
}

export default connect(state => state)(Root)
```

**Comment by SkateFreak** [comment]
thank you for the advice Dan
