### ISSUE TITLE
how to dereference normalized entities in child components

### ISSUE THREAD

**Issue by EatYourSpinach** [rackt/redux#592]
When passing normalized nested structures down the component hierarchy, there will be arrays filled with IDs. Somehow, child components need to be able to dereference these IDs to display the entity. One could pass getState() into components, and directly look up entities through that. Seems a bit too wide open though. For example, in flux-react-router-example, there's various lookup methods on the stores (repoStore.get(...), userStore.get(...), etc). 
Where does this lookup logic live in redux?

**Comment by ms88privat** [comment]
This is a little bit related to this topic https://github.com/rackt/redux/issues/584

What I am doing is, that you map the entities <b>before</b> you pass them down to the child components.

Example:

```javascript

entities.users = {
  id1: {user...}
  id2: {user...
}

//with the help of 'reselect' libary (https://github.com/faassen/reselect)
// selectors.js
const usersSelector = state => state.entities.users;

export const usersArraySelector = createSelector(
    [usersSelector],
    users => Object.keys(users).map(id => users[id])
);

// parentComponent.js
function mapSelectToProps(state) {
  return {
    users: usersArraySelector(state),
  };
} 

@connect(mapSelectToProps)
...
```

**Comment by srph** [comment]
// This isn't entirely related

I'm also looking for a more-detailed explanation. Thanks a bunch, @ms88privat! :heart:

**Comment by EatYourSpinach** [comment]
thank you that's helpful.
