### ISSUE TITLE
store.dispatch() from Actions

### ISSUE THREAD

**Issue by grgur** [rackt/redux#596]
I'm working on an example that makes use of async state updates. In that app I'm trying to find the best place for dispatch (e.g. as in `redux-thunk`), and it just happens to make sense to use it from Actions. 

Here's a sample action just to illustrate. 

```
import { RECEIVE_LOCATION } from '../constants/Types';
import { defaultPosition } from '../constants/Geo';
import store from '../stores';

function requestGeolocation() {
  return function(dispatch) {
    navigator.geolocation.getCurrentPosition(function(position) {
      dispatch({
        type: RECEIVE_LOCATION,
        coords: {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          inProgress: false,
        },
      });
    });
  };
}

export function getGeolocation() {
  if (!navigator.geolocation) {
    return store.dispatch({
      type: RECEIVE_LOCATION,
      ...defaultPosition,
    });
  }
  return store.dispatch(requestGeolocation());
}
```

Obviously `dispatch` didn't come from a view when firing `getGeolocation()`, which is why I'm looking to hear about your take on this approach. This kind of makes sense to me only for the agnostic components where I don't expect bound actions received through props (e.g. `<GeoButton />` that cares less about anything other than triggering that action)

So my question is, would this pattern break the basic Redux principles?

**Comment by gaearon** [comment]
>Obviously dispatch didn't come from a view

If you're grabbing `dispatch` from a singleton `store` by exporting it from some module, you're making it hard to change your app to be universal (i.e. render on the server) later. Whether you care about this or not, is up to you, but we don't encourage this pattern.

Why not just use thunk middleware to change

```js
export function getGeolocation() {
  if (!navigator.geolocation) {
    return store.dispatch({
      type: RECEIVE_LOCATION,
      ...defaultPosition,
    });
  }
  return store.dispatch(requestGeolocation());
}
```

into thunk:

```js
export function getGeolocation() {
  return function (dispatch) {
    if (!navigator.geolocation) {
      return dispatch({
        type: RECEIVE_LOCATION,
        ...defaultPosition,
      });
    }
    return dispatch(requestGeolocation());
  }
}
```

Then you can dispatch it like this:

```js
store.dispatch(getGeolocation());
```

and import `store` from your view, if that's what you prefer.

At this point, though, you should probably put `connect()` without arguments onto your view. Then you'll only get `dispatch` injected as a prop, which is all you need:

```js
class GeoButton extends Component {
  componentDidMount() {
    this.props.dispatch(getGeolocation());
  }
}

export default connect()(GeoButton); // just gives it dispatch()
```

Another option is to keep your `GeoButton` “dumb”, that is, unaware of Redux.

```
class GeoButton extends Component {
  componentDidMount() {
    this.props.fetch();
  }
}
```

Then you can bind it somewhere else:

```
let GeoButtonThatKnowsWhatToDo = connect(null, { fetch: getGeolocation })(GeoButton);
```

**Comment by grgur** [comment]
Fantastic! Thanks @gaearon 👌
