### ISSUE TITLE
Store.subscribe vs Actions firing actions

### ISSUE THREAD

**Issue by grgur** [rackt/redux#597]
Let's say that a completed async operation should fire another action based on new data. While I would prefer to do this with Store.subscribe, I think the "listener" is to raw, given that I might end up observing state diff in multiple actions ("files"), which is wasteful. On that note, it'd be kinda useful if store.subscribe would fire with an argument containing the diff in state calculated in a single place. 

My question here is again about the healthy pattern usage. Do you folks think it's viable to import an action and fire it from another action? Example below:

```
import { RECEIVE_LOCATION } from '../constants/Types';
import { defaultPosition } from '../constants/Geo';
import { fetchMeetupGroups } from './Meetup';
import store from '../stores';

function requestGeolocation() {
  return function(dispatch) {
    navigator.geolocation.getCurrentPosition(function(position) {
      const { latitude, longitude } = position.coords;

      dispatch({
        type: RECEIVE_LOCATION,
        coords: {
          latitude: latitude,
          longitude: longitude,
          inProgress: false,
        },
      });

      dispatch(fetchMeetupGroups({latitude, longitude}));
    });
  };
}

function getDefaultGeolocation() {
  return {
    type: RECEIVE_LOCATION,
    ...defaultPosition,
  };
}

export function getGeolocation() {
  if (!navigator.geolocation) {
    return store.dispatch(getDefaultGeolocation());
  }
  return store.dispatch(requestGeolocation());
}
```

In this case `requestGeolocation()` callback fired `fetchMeetupGroups` from another action module.

**Comment by johanneslumpe** [comment]
If these actions are inherently coupled together and always have to happen combined, I do not see why you couldn't go down this route. The thunk middleware was made to exactly support cases like this where you have multiple dispatches going on.

**Comment by gaearon** [comment]
Yes, see [thunk middleware](https://github.com/gaearon/redux-thunk) and how it lets you [combine action creators and express control flow in them](https://github.com/rackt/redux/blob/c6ac7ab497c570a54c3fccbb4f63fb6aef469e1d/examples/async/actions/index.js#L38-L64).
