### ISSUE TITLE
Question on a possible side effect of composing several middlewares.

### ISSUE THREAD

**Issue by kwangkim** [rackt/redux#603]
It is a very basic question.
I learned I need a middleware to handle async actions. 
If I apply several middlewares together, is there any possible side effect?
(Frankly speaking, I do not know whether I can apply middlewares together.)
Thanks.

**Comment by zerko** [comment]
You need a single middleware to handle any amount of async action, you can check the docs https://rackt.github.io/redux/docs/advanced/AsyncActions.html.

You also could apply any number of middlewares you want, again check the docs https://rackt.github.io/redux/docs/advanced/Middleware.html. Composing them should not be an issue as long as they dont have any interfering side-effects.

**Comment by kwangkim** [comment]
Thank you very much.
I have a plan to make a middleware for the action queue.
Is there any spec from middleware?

**Comment by eugene1g** [comment]
The full spec with several sample implementations is available at the same page at https://rackt.github.io/redux/docs/advanced/Middleware.html

**Comment by kwangkim** [comment]
Middleware seems like
```
Middleware= store=>next=>action=>{
//code
return next(action); //I guess it is related to a dispatch.
}
```

Did I miss something?

**Comment by eugene1g** [comment]
That's basically correct - roughly speaking, "middleware" just a wrapper around the dispatch function that allows you to run your code before/after it is actually dispatched. Redux middleware is designed to be combined and stacked, so applying several middleware together is both allowed and even expected.

**Comment by gaearon** [comment]
You can apply several middleware together. They will form a chain.
