### ISSUE TITLE
Component won't re-render (universal)

### ISSUE THREAD

**Issue by boyswan** [rackt/redux#610]
I have an action posting to my database, with the reducer successfully posting the response to my state. This works fine, however my component isn't re-rendering automatically, I can only use the updated component with a manual re-render.

Here's my component:

```javascript
export default class Colours extends React.Component {

  componentDidMount() {
    this.props.getColours();
  }

  render() {...}

  addItem = () => {
    this.props.postColour({ 
      colour: 'pink' 
    });
  }

}
```

my action: 

```javascript
import req from 'axios';

export function postColour(value) {
  return {
    type: 'POST_COLOUR',
    promise: req.post('/api/colours', value)
  };
}
```

and my reducer:
```javascript
import Immutable from 'immutable';

export default function colourReducer(state = new Immutable.Map(), action) {
  switch(action.type) {

    case 'POST_COLOUR': {
      return state.merge(action.res.data.colours)
    }

    ...
  }
}
```

Am I missing/doing something completely wrong for my props not to be updated as soon as the response is merged with my initial state?

Thanks!

**Comment by gaearon** [comment]
React Redux version?
How do you connect `Colours` to read the Redux state?

**Comment by boyswan** [comment]
Using 1.0.0-rc.

Here's the parent component where I connect:

```javascript
@connect(state => ({ 
  colours: state.colours.get('colours'),
  typography: state.typography.get('typography')
}))

export default class App extends React.Component {

  render() {

    const { colours, typography, children, dispatch } = this.props;
    
    const bindDispatch  = { ...bindActionCreators(actions, dispatch) };
    const mergedProps   = assign({}, { colours, typography }, bindDispatch);

    return (
      <div>
        <Header />
          { React.cloneElement(children, mergedProps) } 
      </div>
    );

  }

}
```

**Comment by gaearon** [comment]
What version of `react-redux` are you using?

**Comment by boyswan** [comment]
Sorry my bad, 0.8,2

**Comment by gaearon** [comment]
Any chance you could share the project to reproduce?

**Comment by boyswan** [comment]
Just added you as a collab

**Comment by gaearon** [comment]
Thanks. I can't get to start it. I installed `nodemon`, it crashes with `serve-favicon` missing, I installed it, now it crashes with `body-parser` missing, etc. Can you please declare all dependencies?

**Comment by boyswan** [comment]
Just updated repo!

**Comment by gaearon** [comment]
Dependencies work now, but now I get this:

```js
    throw err;
    ^
Error: Cannot find module 'server/routes'
    at Function.Module._resolveFilename (module.js:332:15)
```

**Comment by boyswan** [comment]
pushed again, very strange it's working on my machine, trying to think if I have anything globally installed that would make a difference..

**Comment by gaearon** [comment]
Still not working.

```
 62% 228/259 build modulesmodule.js:334
    throw err;
    ^
Error: Cannot find module 'server/routes/routes'
```

I'm on OSX if that matters..

**Comment by gaearon** [comment]
By the way I'm curious why non-relative routes are supposed to work. Shouldn't it be `./server` instead of `server`?

**Comment by gaearon** [comment]
Also, I'm using io.js 2.2.1

**Comment by boyswan** [comment]
I honestly have no idea, i'm on OSX too.

 You're right I didn't even notice that, that shouldn't work at all..

I've just updated my io.js to 3.1.0 and now I'm getting your error haha.. would you be able to leave this open and i'll let you know when i've fixed it?

**Comment by gaearon** [comment]
Yeah sure.

**Comment by boyswan** [comment]
Ok fingers crossed this one works.. Thanks for bearing with me !

**Comment by gaearon** [comment]
It's working! What should I do to repro?

**Comment by boyswan** [comment]
Ahh good,

If you go to /colours, and press the '+' on the page it posts a colour to mongo, however the component doesn't re-render. If you refresh/componentDidUpdate then the state updates

**Comment by gaearon** [comment]
So, I added redux-logger and here's what I see:

<img width="446" alt="screen shot 2015-08-24 at 02 23 36" src="https://cloud.githubusercontent.com/assets/810438/9430673/3d0ae0d6-4a07-11e5-8b66-fc31e4edce8d.png">

**Comment by gaearon** [comment]
Oh wait, I see your point, this is exactly what you wanted state shape to be..

**Comment by gaearon** [comment]
Here's the `action` I see. There's no `action.res.data.colours` in it.

<img width="371" alt="screen shot 2015-08-24 at 02 33 24" src="https://cloud.githubusercontent.com/assets/810438/9430716/9552d0b8-4a08-11e5-8860-23a88219b23c.png">

**Comment by gaearon** [comment]
It's also a bit strange that you seem to be using Immutable structures for states, but `state.set('colours', action.res.data)` will just put `action.res.data` (a plain array) into the state. The React components also seem to be expecting plain arrays and objects. Why use Immutable one just one level?

**Comment by gaearon** [comment]
I sent a PR. The problem was that the data reducer tried to use wasn't present in the `action` object, and also that mutable objects weren't converted before being put into Immutable maps.
