### ISSUE TITLE
Dispatching part of state in action creator as payload

### ISSUE THREAD

**Issue by nickdima** [rackt/redux#612]
I'm wondering if this can be a good use case for the thunk middleware.
Basically in my reducer I need to read some piece of data that's handled by another reducer.
So I was thinking to pass this after reading it with `getState` in a thunk.

Opinions?

**Comment by gaearon** [comment]
Yes, it's a valid use case for `redux-thunk`. Make sure you don't pass large portions of state there, as this seems more like an anti-pattern. Reading a few bits here and there is fine.
