### ISSUE TITLE
TodoList.js in Usage with React page is not highlighted

### ISSUE THREAD

**Issue by yoo2001818** [rackt/redux#620]
While reading the tutorials of Redux, I found that TodoList.js is not highlighted at all in
[here](http://rackt.github.io/redux/docs/basics/UsageWithReact.html).

But in [here](https://github.com/rackt/redux/blob/master/docs/basics/UsageWithReact.md), the code is escaped well. Maybe it's a page generator's problem?

**Comment by gaearon** [comment]
This is covered by https://github.com/rackt/redux/issues/345.
We'd welcome help with making Gitbook use Prism instead of Highlight.js.
