### ISSUE TITLE
Problem with componentWillMount on connected component

### ISSUE THREAD

**Issue by tadjik1** [rackt/redux#621]
I have a problem with server rendering when use ```componentWillMount``` method for request data. Some of my requests are pre-fetched on server-side and some of them not.
Example:
```javascript
// HomePage container
class HomePage extends Component {
  static willRender = store => {
    // I don't want fetch anything - let's client do this job
  }

  componentWillMount() {
    this.props.fetchSongs();
    this.props.fetchAlbums();
    this.props.fetchBands();
  }

  ...
}

export default connect(select, mapDispatchToProps)(HomePage);
```

When server render markup client can not use it, I see this error in console:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) eoa8oo3k.1.$/"><div class="loader-block"
 (server) eoa8oo3k.1.$/"><div data-reactid=".meeoa
```

As I understand it's because this method invoked on the client side before rendering and on server side "after".

**Comment by gaearon** [comment]
This is just how React works, isn't it? Either you generate identical markup, and then client is able to reuse it, or you generate a different markup, and client cannot reuse it.

In your example the server renders the data, but the client renders `<div class="loader-block"` first. Unfortunately I can't help you further because I don't understand the problem from the issue description.

**Comment by gaearon** [comment]
If you want to only fetch something on the client, put it into `componentDidMount` which executes only on the client:

```js
  componentDidMount() {
    this.props.fetchSongs();
    this.props.fetchAlbums();
    this.props.fetchBands();
  }
```

**Comment by tadjik1** [comment]
yes, I want to make some requests only on client side. thanks for description
