### ISSUE TITLE
Add redux todo app example to todoflux.com

### ISSUE THREAD

**Issue by pukhalski** [rackt/redux#629]
Hello redux fellows, 
I am looking for some help in building a perfect [TodoFlux](http://todoflux.com/) app using redux.

If you have some spare time, I would really appreciate your effort in building a simple todo app. The app in examples, unfortunately, doesn't meet all the requirements.

[TodoFlux](http://todoflux.com) is the project that helps to select a proper Flux/Flux-like framework/variation comparing the implementations of [that well-known Todo app](http://todomvc.com/examples/backbone/). TodoFlux is using [TodoMVC](http://todomvc.com/) experience and infrastructure. The project is still in the development phase (I am still updating some stuff here and there, but in all cases the updates are very minor), but it's the right time to start adding your examples over there.

- [Contribution guidelines](https://github.com/TodoFlux/todoflux/blob/master/contributing.md)
- [App Template](https://github.com/todoflux/todoflux-app-template)
- [App Spec](https://github.com/todoflux/todoflux/blob/master/app-spec.md)

— *Why didn't you write the app on my own?*
— *I want all the apps to be as close to framework masterminds as it could be.*

Looking forward to get Redux app example in PRs.

Btw, if you want to help the project, don't hesitate to ask any questions, [submit issues](https://github.com/todoflux/todoflux/issues) or message me directly.

Thanks.

**Comment by aaronazlant** [comment]
I am actually in the middle of finishing the final touches on a version of a TodoMVC implementation that makes use of [this starter repo](https://github.com/erikras/react-redux-universal-hot-example), which seems to have a lot of best practices in it, as well as the [standard todo mvc css](https://github.com/tastejs/todomvc-app-css). 

I was planning to create a barebones repo and then write a Medium article explaining step-by-step how to pull that repo and then complete the TodoMVC example from scratch. I don't know how well my code will conform to the template above -- the directory structure will probably be a little different, for instance -- but if it is useful, I'd be happy to link my example for inclusion at todoflux.com.

**Comment by pukhalski** [comment]
@aaronazlant, thanks, mate! Waiting for your PR then.

**Comment by gaearon** [comment]
I'm closing, as we don't have intention to work on this officially (at least not yet).
Feel free to keep discussing here!
