### ISSUE TITLE
Tweak Universal example

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#643]
Here's a few issues I'd like to see addressed:

* Unlike all examples, you need to open `localhost:8080` in it instead of `localhost:3000`. I'd rather change it to be the other way: put app server at `3000` and use something like `3001` for WebpackDevServer. This way you don't have to memorize which example you are running.

* You need to `npm start & npm run client` in universal example. I struggled with non-working example for 15 minutes before figuring that out. This is obvious to someone experienced with server rendering, but wasn't obvious to me. I missed that part in the doc, and I'm sure a lot of people will `npm start` and expect things to happen.

* I'd prefer to see `client`, `server` and `universal` folder structure at the very top, which signals which modules are related to which part. Lots of universal examples follow that structure and we should do it too.

**Comment by gaearon** [comment]
What if `npm start` printed a message like `Run "npm run dev" for development, and "npm run prod" for production`? `npm run dev` would launch both server and WebpackDevServer, `npm run prod` would use compiled assets. Does this make any sense?

cc @erikras @davezuko who have experience with universal examples

**Comment by timdorr** [comment]
That could work. I'm tweaking some my stuff in #642 around the port numbers and what it prints to screen when booting up.

**Comment by timdorr** [comment]
As for the last point, it's implied that everything except `client.js` and `server.js` is universal stuff. But I'm ambivalent about it. I keep everything top-level, but don't mind reorganizing if that's more standard.

**Comment by gaearon** [comment]
Let's reorganize.

**Comment by gaearon** [comment]
Also, a few things:

* hot reloading reducers doesn't work because there's no `<Root>` component
* change root node ID to `'root'` instead of `'app'` for consistency with other examples
* I assumed pressing a counter talks to server because there's `api` folder. Let's remove 'Increment async' because it's counter intuitive what it does in the context of this example?

**Comment by gaearon** [comment]
`api` folder actually is a good example of something that would go in `server/` folder because it's not used on client.

**Comment by timdorr** [comment]
Just addressed the first two bullet points in this issue in my other PR. I don't think we should worry about production usage, because there are too many assumptions about setup there. Running a universal app in production on Heroku and your own Ubuntu box is drastically different.

**Comment by timdorr** [comment]
`api` isn't universal in this example, but would be in other contexts. Take a blogging engine. That would have a way to fetch the posts on the page, which would apply to the initial server-side render and then as you browse around. I'd want to hint at that so people don't end up writing two versions of the same thing.

**Comment by gaearon** [comment]
@timdorr 

>api isn't universal in this example, but would be in other contexts. 

In this case we need "increment" action to work through server, otherwise its role is confusing. Bonus point: optimistic update.

**Comment by gaearon** [comment]
I guess my point is: we have two places with `setTimeout` calls. `actions` and `api` confuse me because they look very similar and the relationship is obscured. I'd assume `api` is what runs on server (actual REST-like API), and `actions` is how I access it, both on client and server.

**Comment by timdorr** [comment]
Hmm, I didn't want to get into a real API example, since that starts touching on things way outside of the realm of redux (a HTTP client like `superagent` or `whatwg-fetch` and more express coding). Hence the fake async via a `setTimeout`. I figure those looking for a more sophisticated example could check out awesome-redux or react-redux-universal-hot-example.

But yeah, we can get rid of the async increment action. That was some copy pasta on my part.

**Comment by timdorr** [comment]
Oh! I could, rather than wrapping the initial render in a promise to prefetch data, instead just use `redux-promise` to issue an initial action and hook into the `.then` returned from `dispatch` to send the response once it resolves. That would make it so the entire prefetch is redux-based.

**Comment by gaearon** [comment]
Yes, or you could use `redux-thunk` which we use in Reddit example for the same purpose.

**Comment by davezuko** [comment]
I really like that dev vs. prod approach @gaearon, and it's something I've been toying with integrating into the react-redux-starter-kit, since right now the server essentially just acts like your `prod` example.

I originally thought just having a `prod` mode would suffice, and didn't really want to have to run babel/register against the server, but after looking at the universal Redux example it definitely seems more convenient to be able to differentiate between serving a live vs. compiled app.

**Comment by davezuko** [comment]
I do have a question about the existing universal example, though. Since only one webpack bundle gets compiled, how would non-js imports be handled? Currently the application is able to render on the server because it makes use of `babel/register`, but once you get into importing any of the things that make webpack awesome (images, styles, etc.), I'm not sure how well this method holds up.

I was temporarily avoiding this issue by never running a non-compiled application from the server, but that makes server development fairly tedious. I'm at a loss for how the current example would accommodate these features. Does anybody have experience with this?

**Comment by timdorr** [comment]
Again, I didn't want to make any decisions about how someone might use it in production. There a eleventy bajillion ways of doing it and many options to consider (Data uri images or static files? Hash cache busting? etc etc.). Those are an exercise in how you might set up webpack, which has nothing to do with redux and how you use it with server rendering.

**Comment by gaearon** [comment]
>I was temporarily avoiding this issue by never running a non-compiled application from the server, but that makes server development fairly tedious. I'm at a loss for how the current example would accommodate these features. Does anybody have experience with this?

One way is to just use Webpack for Node server. Not everybody would be on board with this though.

**Comment by gaearon** [comment]
I agree with @timdorr regarding keeping the scope to minimum.
That said,

* routing (even with a single route)
* data fetching the Redux way with `redux-thunk` (even just initially)

should be covered because it's related to universal rendering.

**Comment by timdorr** [comment]
@hedgerh and I had talked about that in the PR on his repo. I think those sort of "next steps" items should be put in an advanced recipe. Possibly a sort of "Tying It All Together" recipe. 

Do you have a sense of when react-router is going to land a 1.0 (or at least 1.0-rc)? There look to be substantial changes upcoming, so it might be a good idea to wait a bit to avoid having to re-write such an article later on.

**Comment by gaearon** [comment]
1.0 isn't likely to change much from betas.
2.0 will be interesting but it'll take more time.

**Comment by mjw56** [comment]
I've been working on a universal example here: https://github.com/mjw56/redux-starter-pack

It can be tweaked more. Feedback is welcomed!

**Comment by gaearon** [comment]
I'd keep it open because there's still `api` / `actions` weirdness. Let's close when we refactor it to use async actions all the way.

**Comment by timdorr** [comment]
OK, sounds good. 

What do you think about refactoring around `react-transform` and `webpack-hot-middleware` (since we're already using Express)?

**Comment by gaearon** [comment]
>What do you think about refactoring around react-transform and webpack-hot-middleware (since we're already using Express)?

Sounds good to me, but this would need to be done for all examples at once.

**Comment by timdorr** [comment]
Well, in light of #690, I can focus on just the hot-middleware conversion. Shouldn't be that much work.

**Comment by timdorr** [comment]
What about including the efforts of #721 in the universal example? Or is that too much stuff in one place? I worry it might be getting too specific and guiding new users towards having to set up all this stuff just to get started with redux (rather than starting minimally and tacking on features as needed)

**Comment by gaearon** [comment]
Wouldn't #721 actually simplify the universal example by doing everything via Express?

**Comment by timdorr** [comment]
I mean more in terms of adding devTools into the mix. It's becoming the `kitchensink` example instead of the `universal` example :smile:

**Comment by gaearon** [comment]
No, I don't want to add DevTools there.

**Comment by timdorr** [comment]
OK, I'll just do hot-middleware and call it a day.

**Comment by mhahn** [comment]
@timdorr it is understandably out of scope of the redux documentation to go into how to run a universal example in production, but it also is a little annoying coming across "in production you wouldn't do this and it's out of scope to talk about what you should do". I've been incredibly impressed by the redux documentation and think it would be awesome if there was an "advanced recipe" like you mentioned, or just resources where people new to universal apps can learn more about them.

**Comment by timdorr** [comment]
The only mention of scope comes with the handling of static files. That's entirely a configuration thing that you would handle with nginx or whatever frontend webserver you have. That's something left to your sysadmin (which may be yourself!) to determine how to handle. 

Nonetheless, that section of the docs was removed in #766 and will be put into the next documentation rebuild. 

Outside of that, I do all of the things in the universal example in my real world production apps. There might be a slight change here or there, but it's almost entirely the same thing. This is production-ready code.

**Comment by mhahn** [comment]
@timdorr good to know, thanks!
