### ISSUE TITLE
Guidance on hooking lazily loaded actions+reducer into existing store

### ISSUE THREAD

**Issue by garborg** [rackt/redux#654]
It may be out of the scope of the docs, but I haven't found any inspiration in the various middleware/scaffolding/example repos, either.

In my case, I've just switched `react-router` config to lazily-load sub-apps via `require.ensure`, and I'm trying to figure out how to bundle the sub-app's actions and reducers with the lazily loaded chunks rather than with the shared bundle.

**Comment by timdorr** [comment]
I'd keep an eye on #625. That will enable lazy/progressive loading of reducers.

**Comment by garborg** [comment]
Thanks, @timdorr. I subscribed to #625 -- feel free to close this if it seems redundant.

**Comment by gaearon** [comment]
@garborg In the meantime feel free to use `store.replaceReducer()`.
