### ISSUE TITLE
Question: How to architect multiple instance of a component in the same store

### ISSUE THREAD

**Issue by tusharmath** [rackt/redux#659]
Consider the Todo List example, if I want to create multiple TodoLists, one for each work, home personal and grocery, then the actions and the reducers would need to know which TodoList am I talking about every single time I want to use them. This can still be easily solved by dynamically creating these actions, the real problem arises when the reducer are mutating the states.

The state of each of the TodoList would be different and one would have to create some sort of a namespace in the global store to differentiate between them. Is there are more cleaner way of solving this problem?

**Comment by 0x80** [comment]
You could create one big array of todo objects and give each item a "category" property for work / home / etc, besides the name/label of the todo. The currently active/selected category could be a variable in the store and used to know what category to set on newly created todo's in the reducer function.

In your list rendering you would use this category to filter the array for the relevant todo items to show.

This way you can create an arbitrary number of categories easily.

**Comment by tusharmath** [comment]
@0x80 I really appriciate your answer, but it seems too specific to the current example. What if I want to persist the state of filters (completed, active, all) independantly for each todo list?

**Comment by 0x80** [comment]
@tusharmath I don't quite understand you. Add category as a property to each todo item. When you want to show only home + completed filter on those two properties. Category would just be an extra filter that you use to display the items from one of your lists.

I didn't look at the todo example before, but I see it is already an array of items (which makes total sense). So just add category as a property and in the store create a variable to keep track of the selected category, and you should have enough data to display/edit any number of lists.

**Comment by tusharmath** [comment]
What I meant was: I want to save the states of these todo lists ie. the selected filters and the data, in a global store.

**Comment by edge** [comment]
You could have a "shape" reducer similar to [this](https://github.com/edge/fluxette/blob/master/src/reducer/shape.js).

Normally it's used for the same purpose as `combineReducers`, but you could also make it so that you could attach an id for a new todo list, and then assign the todo list reducer to it. All you need to do then is to make sure the right action goes to the right reducer.

**Comment by tusharmath** [comment]
Had I create a state for each component, I wouldn't have to manually handle this at all right ? Worrying about ids and passing them to reducers?

**Comment by edge** [comment]
You mean directly modifying the state from the component? That's not redux anymore.

**Comment by tusharmath** [comment]
I agree, that its not redux, but is it like the cost one need to pay for all the gains we get from a single store?

**Comment by edge** [comment]
I mean, the whole point of flux is to sacrifice a bit of convenience for maintainability and scalability.

**Comment by timdorr** [comment]
You probably want to look over [the docs on state shape](ttp://rackt.github.io/redux/docs/basics/Reducers.html#designing-the-state-shape) again. You'll also probably find some use with [normalizr](https://github.com/gaearon/normalizr) to give you better access to your state data in a shape that's scalable.

**Comment by timdorr** [comment]
Also, if you kept state on a per-component basis, you wouldn't be able to do things like have a counter of the number of incomplete todos in your header. A single store means there is a single source of truth in your app, and therefore no conflicting states in your app.

**Comment by malcolmyu** [comment]
We can assume another case, which seems like the multiple TodoLists, but it's hard to avoid by a better design of state tree:

We have a SPA application consists of a `profile` page and a `followerList` page. The state tree is as shown in the following:

    {
      profile: { name: xx, sex: xx, followers: 123 },
      followerList: []
    }

We can open a follower list page from a profile **page A**, and then open a profile **page B** from the follower list page. In my application, page A and page B share the same reducer `profile`.

Here is the problem: when page B rendered, the `profile` in state tree has been changed by B's info; when it returns back to page A, it is supposed to keep A's info, **but it has also been rendered by B's info**.

How can we solve this problem?

**Comment by tusharmath** [comment]
@malcolmyu for your particular case, i think when ever you go to a profile page an http request needs to be made to get that particular profile data.

**Comment by malcolmyu** [comment]
@tusharmath It means that I have to refresh the profile page even if just returning back to it. In my option, it's not an elegant way in a SPA hybrid application.

**Comment by tusharmath** [comment]
@malcolmyu You can always cache that response with a different Service layer. Having all the responses saved in the store won't be a really good idea, as it could cause memory leaks.

**Comment by malcolmyu** [comment]
@tusharmath Thank you for your advice, and I will give it careful reconsideration.

**Comment by zivni** [comment]
I had the same problem as @tusharmath. I ended up writing the following [reducer enhancer](https://gist.github.com/zivni/677638f712b9d16f78ee1903b5a11596)

**Comment by kidequinox** [comment]
@malcolmyu what did you guys end up doing for a multi-screen redux solution ?

**Comment by kidequinox** [comment]
Good Concepts: [NameSpaced Instances](https://stackoverflow.com/questions/42906358/having-multiple-instance-of-same-reusable-redux-react-components-on-the-same-pag)

**Comment by mkantz84** [comment]
Is there a new approach for this issue?

**Comment by Javes7777** [comment]
I tried using [multireducer](https://github.com/adailey14/multireducer)

The problem with this is I can't add reducer instances dynamically. There can only be a limited copy of reducers initially defined.
