### ISSUE TITLE
Docs middleware inconsistencies

### ISSUE THREAD

**Issue by kentor** [rackt/redux#682]
In the **Middleware** section:

> It provides a third-party extension point between dispatching an action, and the moment it reaches the **store**.

In the **Async Actions** section:

> In the previous section, we explored how Redux middleware can intercept, delay or transform actions before they reach the **reducer**.

I'm guessing the latter is clearer?

**Comment by gaearon** [comment]
Yep. Wanna send a PR?

**Comment by kentor** [comment]
Sure thing
