### ISSUE TITLE
A way to select state based on react-router params

### ISSUE THREAD

**Issue by gyzerok** [rackt/redux#684]
For example I have a roiute ```/item/edit/:id``` and a React component for this route as a handler.
Is there a way to select item based on router id from items?

It feels like pass all items to React component and than find item by id is not the best way.

**Comment by gaearon** [comment]
This is a question for [react-redux](https://github.com/rackt/react-redux) repo, not for Redux.
There is an example in its README: https://github.com/rackt/react-redux#inject-todos-of-a-specific-user-depending-on-props

**Comment by gyzerok** [comment]
@gaearon sorry, missed it. Thank you for help!
