### ISSUE TITLE
add github link to docs

### ISSUE THREAD

**Issue by omnidan** [rackt/redux#685]
use the http://plugins.gitbook.com/plugin/edit-link gitbook plugin to add a button that takes you to the same page on github

I had to google the redux github repo a few times already, a button on the docs that sends me to the same page/file would've been very useful

**Comment by gaearon** [comment]
Yeah, there's a PR for that: #498. I should merge it :-P

**Comment by omnidan** [comment]
Oops - Sorry for not checking first! Thanks for merging it.
