### ISSUE TITLE
Promise (universal) unable to resolve on server

### ISSUE THREAD

**Issue by boyswan** [rackt/redux#692]
I'm using this promise middleware on a universal app, using the majority of the code from this tutorial as a boilerplate. 

https://medium.com/@bananaoomarang/handcrafting-an-isomorphic-redux-application-with-love-40ada4468af4

The only difference is that im using mongodb as my backend on the server. The fetchComponentData function works fine on the client, but on the server fails with a 404 when trying to fetch /api/data . If I use firebase or something that's hosted elsewhere (like in the tutorial), it works fine.

I've tried mongolabs, using bluebird etc, but haven't successfully been able to get mongo/mongoose/express to resolve the promise on the server, and can't retrieve any data on the initial load. Am I right in thinking this is an express/mongoose problem? (If it is then I'll do some more digging, unless there's any info you could provide on how to approach!)

fetchComponentData (static needs = [action] in component):
`````javascript
export function fetchComponentData(dispatch, components, params) {
  const needs = components.reduce((prev, current) => {
    return (current.needs || [])
      .concat((current.WrappedComponent ? current.WrappedComponent.needs : []) || [])
      .concat(prev);
  }, []);
  const promises = needs.map(need => {
      return dispatch(need(params))    
    });

  return Promise.all(promises);
}
`````

Promise middleware:
`````javascript
export function promiseMiddleware() {
  return next => action => {
    const { promise, type, ...rest } = action;
    if (!promise) return next(action);

    const SUCCESS = type;
    const REQUEST = type + '_REQUEST';
    const FAILURE = type + '_FAILURE';

    next({ ...rest, type: REQUEST });

    return promise
    .then(res => {
      next({ ...rest, res, type: SUCCESS });
      return true;
    })
    .catch(error => {
      next({ ...rest, error, type: FAILURE });
      console.log(FAILURE + ':\n', error);
      return false;
    });
  };
}

`````

As always, thank you!

**Comment by timdorr** [comment]
How are you using it in your server app? I suspect the problem lies there. 

If you're using Express, you'll put your `res.send`'s inside of the results of that Promise's `then`. Maybe you're not passing that through so the server socket can send back data?

**Comment by boyswan** [comment]
Here's the code for the server:

`````javascript
const app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true })); 
app.use('/public', express.static(path.join(__dirname, 'public')));
app.use(favicon(__dirname + '/public/assets/favicon.ico'));

mongoose.connect('mongodb://localhost/mod');

// require('./server/routes/routes')(app);



import { Data } from './server/models'
app.route('/api/data')
.get((req, res) => {
  Data.find({})
  .then((data) => res.send(data))
  .catch(err => alert(err))
})


app.use((req, res) => {

  const routes   = createRoutes();
  const location = new Location(req.path, req.query);
  const store    = applyMiddleware(promiseMiddleware)(createStore)(reducer);

  Router.run(routes, location, (err, routeState) => {

    if (err) return console.error(err);
    if (!routeState) return res.status(404).end('404 page m8');

    function renderView() {
      return `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>Redux Demo</title>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
          </head>
          <body>
            <div id="app">${React.renderToString(
              <Provider store={store}>
                { () => <Router { ...routeState }/> }
              </Provider>
            )}</div>
            <script> window.__INITIAL_STATE__ = ${JSON.stringify(store.getState())}; </script>
            <script type="application/javascript" src="${
              process.env.NODE_ENV === 'PROD' ? 'public/bundle.min.js' : '/bundle.js'
            }"></script>
          </body>
        </html>
      `;
    }

    fetchComponentData(store.dispatch, routeState.components, routeState.params)
    .then(renderView)
    .then(html => res.end(html))
    .catch(err => res.end(err.message));
  
  });

});

app.listen(process.env.PORT || 3000, 
  () => console.log('\n\n ==> 🌎  Server listening on port 8080\n')
);

`````

**Comment by timdorr** [comment]
Everything looks good from what I can see. What version of `react-router` are you using? And to be clear, it's hitting the `!routeState` line, right?

**Comment by boyswan** [comment]
I'm using react-router 1.0.0-beta3, and yeah the !routeState works fine!

I have a feeling it's something to do with mongo/mongoose resolving promises itself, although I might be completely wrong! If it helps I could provide a repo

**Comment by MikeBarnhardt** [comment]
Have you tried using an absolute URL on the server? I had a similar issue a while back when messing around with isomorphic JS apps.

**Comment by gaearon** [comment]
I'm closing as the question doesn't appear specific to Redux, and there is no easy way to reproduce the problem.
