### ISSUE TITLE
How to write tests regarding Action Creators which return functions?

### ISSUE THREAD

**Issue by rui-infotrack** [rackt/redux#700]
It's mentioned in the documentation:
```
In Redux, action creators are functions which return plain objects. When testing action creators we want to test whether the correct action creator was called and also whether the right action was returned.
```

However, action creators can also return functions like this:
```javascript
(dispatch, getState) => {...}
```
In this case, how do I write tests? It's not a simple checking object equality anymore.

Thank you

**Comment by por** [comment]
The counter example app has [some tests](https://github.com/rackt/redux/blob/master/examples/counter/test/actions/counter.spec.js#L13) that cover this.

Maybe an idea to add this to [the documentation](https://github.com/rackt/redux/blob/master/docs/recipes/WritingTests.md)?

**Comment by rui-infotrack** [comment]
@por 
Thank you very much for the help!

**Comment by gaearon** [comment]
Duplicate of https://github.com/rackt/redux/issues/546.
See https://github.com/rackt/redux/issues/546#issuecomment-134789273.

>Maybe an idea to add this to the documentation?

I'd happily accept a pull request.

**Comment by mik01aj** [comment]
> However, action creators can also return functions like this:

>     (dispatch, getState) => {...}

I see it's not true anymore... Did the API change?

**Comment by gaearon** [comment]
Yes, use thunk if you want to have this.

**Comment by just-boris** [comment]
Also, there is a related issue: https://github.com/gaearon/redux-thunk/issues/14
