### ISSUE TITLE
Question on using componentDidMount() with react-router

### ISSUE THREAD

**Issue by tkiethanom** [rackt/redux#702]
I have a simple route `/accounts/:acccountId`. When the page loads I use `componentDidMount()` to dispatch the request to get data from the API using the `accountId` param. 

This works fine except when I link from `/accounts/1` to `/accounts/2`. The `componentDidMount()` already ran once so it will never fetch new data from the API. 

I've tried using some of the other life cycle methods `componentWillReceiveProps()` but since the dispatch updates the `props` I get stuck in a forever loop.  

I can also do some checking within `componentWillReceiveProps()` but I was wondering if there is a better way to do this since this kind of thing would be used for any Model that has and ID.

```javascript
componentDidMount() {
	dispatch(fetchAccountView(this.props.params.accountId)); 
}

//This will loop forever
componentWillReceiveProps() {
	dispatch(fetchAccountView(this.props.params.accountId)); 
}
```

**Comment by koulmomo** [comment]
your `componentWillReceiveProps` is wrong, it should be:

```js
componentWillReceiveProps(nextProps) {
    var nextAccountId = nextProps.params.accountId;
    if (nextAccountId !== this.props.params.accountId) {
        dispatch(fetchAccountView(nextAccountId));
    }
}
```

alternatively, you can use `react-router`'s [static lifecycle methods](https://rackt.github.io/react-router/#static-lifecycle-methods). Namely, the `willTransitionTo` method, which only needs to be defined once.

```js
statics: {
    willTransitionTo(transition, params, query) {
        dispatch(fetchAccountView(params.accountId));
    }
},
```

**Comment by tkiethanom** [comment]
Okay I understand that I can do some checks in `componentWillReceiveProps()`. I'm looking for a way to do this without added repetitive code to each Page. 

I'm not sure how the `statics` translates to redux though. How or where would you put that code?

**Comment by koulmomo** [comment]
```js
'use strict';

module.exports = React.createClass({
    statics: {
         willTransitionTo(transition, params, query) {
             dispatch(fetchAccountView(params.accountId));
         }
    },

    render () {
        // render account view page
     }
});
```

**Comment by gaearon** [comment]
>I'm not sure how the statics translates to redux though. How or where would you put that code?

This is not a Redux question per se. If you mean [react-redux](https://github.com/rackt/react-redux/), you'd put statics on the `connect()` result:

```js
class MyComponent extends Component {
  render() { }
}

MyComponent = connect(mapStateToProps)(MyComponent);

// Put any statics on it:
MyComponent.willTransitionTo = function () { }

export default MyComponent;
```

>Okay I understand that I can do some checks in componentWillReceiveProps(). I'm looking for a way to do this without added repetitive code to each Page.

You can create a [higher order component](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750) like `connect()`, but that would dispatch actions on route change. For example, like [here](https://github.com/emmenko/redux-react-router-async-example/blob/ef5e3f51b6d27f153bdb8492aab670f30cf70067/lib/decorators/fetchOnUpdate.js).
