### ISSUE TITLE
Allow grouped actions in bindActionCreator

### ISSUE THREAD

**Issue by sbycrosz** [rackt/redux#716]
I know that I could write my own and I'm doing so at the moment.
Binding every actions as a props result in lots of props being passed down into the nested property chain. So instead of

```javascript
bindActionCreators({
    createCard,
    displayCardForm,
    updateCardForm,
    hideCardForm
    createList,
    displayListForm,
    updateListForm,
    hideListForm
  }, dispatch);
```

Should we allow
```javascript
bindActionCreators({
    cardAction: {
      createCard,
      displayCardForm,
      updateCardForm,
      hideCardForm
    },
    listAction: {
      createList,
      displayListForm,
      updateListForm,
      hideListForm
    }
  }, dispatch);
```

the same syntax with es6 import

```javascript
import * as CardAction from '../actions/cards';
import * as ListAction from '../actions/lists';

bindActionCreators({
    CardAction,
    ListAction
}, dispatch);

```

And then we just need to pass actions group instead of each bounded action separately.
Will do a pull request later if this is a good idea.

**Comment by gaearon** [comment]
I think we should keep core helpers simple. (Same goes for `combineReducers` that also doesn't support nesting out of the box.)

If you use a library like Lodash, you can write `mapValues({ cardActions, listActions }, actions => bindActionCreators(actions, dispatch))`. And indeed you can write a custom helper that does this, and publish it for others to use.

I don't think we want this in core, as we're entering a very opinionated territory with this.
