### ISSUE TITLE
Why using stage:2 for babel?

### ISSUE THREAD

**Issue by coodoo** [rackt/redux#724]
Just flipped through the v3 examples and found them all using {stage:2} in `.babelrc`, just wondering is there any particular reasons in doing so? Thanks.

**Comment by gaearon** [comment]
We don't want to scare people off by using proposed-for-ES7 features in examples.
Previously people commonly assumed they are *required* for Redux.

#226 
#373 
#466

**Comment by coodoo** [comment]
Good call, thanks for the clarification!

**Comment by dbrans** [comment]
@gaearon stage 2 is still experimental. https://babeljs.io/docs/usage/experimental/
