### ISSUE TITLE
Nested reducers

### ISSUE THREAD

**Issue by omeshechkov** [rackt/redux#727]
Hello,

I have nested data model like this: 
```javascript
{
  sports: [
    {
      id: 1,
      name: 'Soccer',
      leagues: [
        {
          id: 10,
          name: 'Some league',
          matches: [
            {
            id: 100,
            name: 'team1 - team2',
            scores: [
              {
                id: 1000,
                homeTeam: 0,
                awayTeam: 0
              },                                
              {
                id: 1001,
                homeTeam: 1,
                awayTeam: 2
              }
            ]
          },
          {
            id: 101,
            name: 'team3 - team4',
            scores: [
              {
                id: 1002,
                homeTeam: 0,
                awayTeam: 0
              },
              {
                id: 1003,
                homeTeam: 0,
                awayTeam: 0
              }
            ]
          }
        ]
      },
      {
        id: 11,
        name: 'Some other league'
      }
    ]
  },
  {
    id: 2,
    name: 'Tennis',
    leagues: [...]
  }
  ]
}
```

I have reducers:
 * sports
 * sport
 * leagues
 * league
 * matches
 * match
 * sports

For instance I want to change score 1001 and change _only path_ to the score.
In action I know only id of score.
Ergo, I have to traverse all the model and check in the match reducer if match scores is changed and if it is, I should return cloned match. In the matches reducer I should check if any match is changed and if it is, I should return cloned list of matches, etc.

```javascript
scoresReducer(state, action) {
  switch (action.type) {
    case ADD_SCORE:
     ...
     return new state;

    case CHANGE_SCORE:
        //check if state contains action's score and return new state if it does.
        //P.S. state may doesn't contain action's score if it is in another match.

    case REMOVE_SCORE:
     ...
     return new state;
  }

  return state;
}

matchReducer(state, action) {
  switch (action.type) {
    case CHANGE_MATCH_NAME:
      ...
     return new state;
  }

  //if it's nothing changed in match, it's probably changed in the scores
  var newScores = scoresReducer(state.scores, action);
  if (newScores !== state.scores) {
    return [...state, {scores: newScores}];
  }

  return state;
}

matchesReducer(state, action) {
  switch (action.type) {
    case ADD_MATCH:
     ...
     return new state;

    case REMOVE_MATCH:
     ...
     return new state;
  }

  //dispatching 'unknown' actions.
  for (var i = 0; i < state.matches.length; i++) {
    var match = state.matches[i];
    var newMatch = matchReducer(match, action);
    
    if (newMatch !== match) {
       return matches.set(i, newMatch); //Using Immutable.js
    }
  }

  return state;
}

And so on...
```

Upon your documentation reducers have to clone every entity in my case, but I think it's too expensive in all reasons, especially performance. Because in the React's shouldUpdateComponent methods I'll have to compare all entities by values but not by references.

Thanks in advance.

Is there advice about this situation? Because it looks like a mess.  Maybe I doing something wrong?

**Comment by tcoopman** [comment]
You can take a look at some immutable libraries that will help with this. For example look at https://facebook.github.io/immutable-js/
If you search the issues you can probably find more case like this to find more info.

**Comment by alesch** [comment]
According to the [docs](http://rackt.github.io/redux/docs/basics/Reducers.html) you might be better of avoiding nesting in your data structure. See the note on Relationships.

**Comment by omeshechkov** [comment]
I've already looked through immutable js and normalizr and I'm already using immutable js.
But I've just realized that I need just a full key. If I had the id of the target entity I had to traverse all entities but if I have full key I can filter entities during the reducer traverse.
i.e.:
Old action if I change score for example:
```javascript
{
  type: CHANGE_SCORE,
  scoreId: 123,
  //some params
}
```
But I need something like this: 
```javascript
{
  type: CHANGE_SCORE,
  sportId: 1,
  leagueId: 2,
  matchId: 3,
  scoreId: 123,
  //some other params
}
```
But I really haven't understood yet why I should use normalizr.
:going to read the doc: :smiley:

Thanks.

**Comment by gaearon** [comment]
Please see the [real-world example](https://github.com/rackt/redux/tree/master/examples/real-world).
It [uses normalizr in the middleware](https://github.com/rackt/redux/blob/0e723bdbb7840092167d23f3e1d575adbd1d7e39/examples/real-world/middleware/api.js#L39) and makes sure [entity cache is flat](https://github.com/rackt/redux/blob/0e723bdbb7840092167d23f3e1d575adbd1d7e39/examples/real-world/reducers/index.js#L6-L13).

Therefore, if you want to edit some entity, it's right there in `entities.leagues[id]` or `entities.sports[id]` or `entities.scores[id]`—no nesting.

**Comment by sabrinaluo** [comment]
hi @gaearon the *real-world example* link is dead, can you give an updated one? really need it, thank you!
