### ISSUE TITLE
Store schema validation

### ISSUE THREAD

**Issue by tricoder42** [rackt/redux#728]
I'm thinking about validating store the same way how `propTypes` validates `props` in React.

## Why?
I want to be sure that my store has always the expected format and all my reducers change always preserve the same format (schema).

## How?
At the moment, I use `chai-json-chema` when testing reducer and check that schema is preserved. Maybe the store could also raise a warning during development?

This is more question than proposal. I'm interested in your opinion. It certainly make sense when you have external objects in store (fetched from REST API) and you don't want to alter them in a way which would break them.

**Comment by FredyC** [comment]
It's really interesting thought. It might go well together with gaearon/redux-devtools#108 to actually check that deserialized state from persistState has the required format. It might be better than trying to figure out the way how do it with the same code.

**Comment by gaearon** [comment]
Relevant: https://github.com/gcanti/redux-tcomb by @gcanti

**Comment by timdorr** [comment]
As an alternative to redux-tcomb, you could implement it as a store enhancer to check the results upon dispatch and rollback to the previous state (a la redux-devtools) if it doesn't validate.

**Comment by tricoder42** [comment]
@gaearon `redux-tcomb` is awesome. I guess that's exactly what I was looking for. Much easier to use than `json-schema` validator.

I'll send a PR with a chapter about type checking to resolve this issue properly ;)

Thank you!

**Comment by gaearon** [comment]
Note I'm not sure how to implement reducer composition with `redux-tcomb`. It seems to force you to define transformations *on* actions which is a bit opposite to how Redux should work.

**Comment by gcanti** [comment]
> It seems to force you to define transformations on actions which is a bit opposite to how Redux should work

@gaearon The automatically generated reducer is opt-in, you can get type safety with a "standard" reducer (with the new `getCheckedReducer` API)

https://github.com/gcanti/redux-tcomb#3-automatically-generated-reducer

**Comment by gaearon** [comment]
Oh, I see now! I think it's better split README into two "options" because right now it looks like you _have to_ define transformations on actions even if you use `getCheckedReducer`.

**Comment by gcanti** [comment]
@gaearon good suggestion, thanks.
Updated [README](https://github.com/gcanti/redux-tcomb)

**Comment by gaearon** [comment]
:+1: 

If you add tests to the library I'll be happy to link to it from [Ecosystem](https://github.com/rackt/redux/blob/master/docs/introduction/Ecosystem.md) page.

**Comment by gcanti** [comment]
> If you add tests to the library

Done! https://github.com/gcanti/redux-tcomb/releases/tag/v0.1.3

> I'll be happy to link to it from Ecosystem page

Great, thanks @gaearon ;-)

**Comment by gaearon** [comment]
Closed via https://github.com/rackt/redux/commit/99a0dc6a4ca0cea8106ed6c5a7b21f6693cfd1bd.
