### ISSUE TITLE
Why is the reducer called three times?

### ISSUE THREAD

**Issue by alesch** [rackt/redux#729]
In the `counter` example, the reducer is called three times upon start.
The same happens in `todomvc` example.
Why is this?

Thanks!

I added:
```javascript
export default function counter(state = 0, action) {
  console.count('reducer');
   // ....
```

**Comment by gaearon** [comment]
`combineReducers()` [probes your reducers to check for common mistakes](https://github.com/rackt/redux/blob/0e723bdbb7840092167d23f3e1d575adbd1d7e39/src/utils/combineReducers.js#L72-L94) before actually using them.
Don’t worry about it!

**Comment by alesch** [comment]
The reason I started looking into this is that in another project of mine, the reducer is called two times for every action. I am not using `combineReducers` there.

```javascript
function defaultReducer (state, action) {
  return state;
}

function reducer (state, action) {
  return {
    data : defaultReducer(state.data, action),
    ui: {
      mainMenu: mainMenuReducer(state.ui.mainMenu, action)
    }
  }
}
```

**Comment by gaearon** [comment]
Please provide a runnable example to reproduce the issue, with expected and actual invocation count.
Otherwise it's hard to say.

**Comment by alesch** [comment]
I guess the question is: without using `combineReducers`, should my reducer be called __once__ per action, and __once__ on startup?
Or are there other invocations behind the scenes?

PS: Thanks a lot for Redux and for your time answering this questions. You rock!

**Comment by gaearon** [comment]
>should my reducer be called once per action, and once on startup?

Reducer is called once on startup, and then once per every action.
