### ISSUE TITLE
Hierarchy Component State Coupling

### ISSUE THREAD

**Issue by ronag** [rackt/redux#730]
The one thing I find a bit difficult with redux is that, as far as I understand, when I need some more data I need to modify parents in order to make sure that the new state is properly passed down the component tree through props, which is not very good encapsulation. This is essentially due to the Provider only being used on the root component in all the examples.

I would much prefer a practice where similar to Relay one only passes down ids to children and then each child subscribes with its own query.

e.g. right now (not Redux) we create "queries" which are basically Rx.Observable streams of data where each component builds it's own query from the different module stores based on its id and a very few limited pros. Very similar to Relay and React-Firebase.

i.e. a component in our software can look something like:

```
@ui.createContainer({
  propTypes: {},
  propQueries: {
    templates: onProps => onProps
      .pluck('ids')
      .flatMapLatest(ids => ids.length
        ? Rx.Observable.combineLatest(
            ids.map(id => templateQueries.get(id).map(x => ({...x, id}))), (...all) => [...all])
        : Rx.Observable.return([]))
  }
})
class Editor extends React.Component {
}
```

I would love to be able to simply hook into redux this way instead of passing down props through the hierarchy.

What are the redux thoughts on this?

**Comment by gaearon** [comment]
>This is essentially due to the Provider only being used on the root component in all the examples.

I think you're confusing `Provider` and `connect()`. There is always one `Provider` because its only function is to provide the store in context down the tree. But you can have many `connect()`s on different levels of the tree if that's how you roll.

**Comment by gaearon** [comment]
See https://github.com/rackt/redux/issues/419
