### ISSUE TITLE
Actions Docs Question

### ISSUE THREAD

**Issue by hnordt** [rackt/redux#731]
Hello.

I'm reading the docs and I would like to ask a question:

http://rackt.github.io/redux/docs/basics/Actions.html

```js
export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
};
```

What's the convention here? Why `VisibilityFilters` is capitalized? I thought that capitalization is just used for constructor functions.

**Comment by idolize** [comment]
I don't think `redux` has any particular convention here - just do whatever you prefer.  :smiley: 

Some people `export` each constant separately, [others don't even `export` the constants at all](https://github.com/erikras/ducks-modular-redux) (just use them directly with the reducer in the same file), others export an object map with constants (as the example you have here shows) etc.

**Comment by gaearon** [comment]
Completely up to you.
