### ISSUE TITLE
ES6 spread operator in ES5

### ISSUE THREAD

**Issue by kraftwer1** [rackt/redux#733]
What's the best (and shortest) way to translate this to ES5:

```
return [...state, {
  text: action.text,
  completed: false
}];
```

It looks to me that a (deep?) copy of the state array should be created, with the new state at the end. I had a look what Babel would do, but it generates a big function that is probably not necessary for this little use case.

**Comment by hunterc** [comment]
In this example, all the array spread syntax is doing is copying all the existing elements into the new array.
```
return state.slice().push({
    text: action.text,
    completed: false
});
```

**Comment by HeyImAlex** [comment]
@hunterc `Array.prototype.push` returns the new length of the array. You need to split it up like this.

```js
var myNewValue = state.slice(); // Make a copy of the state array
myNewValue.push({ text: action.text, completed: false });
return myNewValue;
```

**Comment by danmartinez101** [comment]
```
return state.concat( [ { text: action.text, completed: false } ] );
```

**Comment by gaearon** [comment]
`state.concat(newStuff)` is right as @danmartinez101 said.

`state.slice().push()` will work too because `slice()` copies the array, but it can be misleading to beginners who might think doing `push()`es is fine.

**Comment by SkateFreak** [comment]
hey guys,
should the returned array should be the reducer itself or can i update an array which sits under an object, like so:

    stories {
        isFetching: false,
        items: [...]
    }

how can i push ri 'items' and return the new state?
