### ISSUE TITLE
Docs - Reducers Broken Link

### ISSUE THREAD

**Issue by hnordt** [rackt/redux#734]
Hello.

At:

http://rackt.github.io/redux/docs/basics/Reducers.html

```md
(...)

Object.assign() is a part of ES6, but is not implemented by most browsers yet.
You’ll need to either use a polyfill, a Babel plugin, or a helper from another library like _.assign().

(...)
```

"Babel plugin" link is broken.

**Comment by gaearon** [comment]
Thanks, fixed in https://github.com/rackt/redux/commit/74ec8fefbbbb07bb29eb9ce5e3b84b748eb99a86. Unfortunately I don't know where's the Github repo for it now.

**Comment by danmartinez101** [comment]
@gaearon is it this one? https://github.com/babel/babel/tree/development/packages/babel-plugin-transform-object-assign

**Comment by gaearon** [comment]
Oh, I wasn't aware of `development` branch, thanks.
