### ISSUE TITLE
Failed Context Types: Required context `router` was not specified in ...

### ISSUE THREAD

**Issue by iMoses** [rackt/redux#741]
I've updated some of my libraries and suddenly parts of the application stopped working. The errors I'm receiving are all similar:

```
Warning: Failed Context Types: Required context `router` was not specified in `SearchForm`. Check the render method of `DefaultLayout`.
```

I'm currently using React 0.14-rc1, React-Router 1.0-rc1 and Redux 3.

After upgrading I changed the `Provider`'s child from a function into the Router element and I'm suspecting it has something to do with the context not being forwarded into the components.

```
ReactDOM.render(
    <Provider store={createStore(reducers)}>
        <Router history={history} children={routes}/>
    </Provider>,
    document.getElementById('root')
);
```

Couldn't find anything online, I'm assuming it's a bug between the three latest versions of these libraries OR that I'm doing something completely wrong and it finally broke :)

Tips? Tricks? Ideas?

**Comment by timdorr** [comment]
This is a react-router issue, not a redux one. However, to not totally kick you to the curb, they removed the `router` context and have replaced with [a `history` and `location` context](https://github.com/rackt/react-router/blob/master/modules/RoutingContext.js#L33-L38). You'll need to update any components relying on that context.

**Comment by iMoses** [comment]
Thanks, I've been debugging it myself for the last hour, indeed I found that the issue is with the router.
I've also noticed the code which currently only passes the `history` and `location` contexts to its children nodes, but I couldn't find any official notes about this change and was unable to locate the `transitionTo` method with this new approach.
Can you provide a little help on this as well?

**Comment by gaearon** [comment]
Use `history.pushState(null, url)` instead of `router.transitionTo(url)`.
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#navigation-mixin

**Comment by iMoses** [comment]
Oh, thank you very very much! You just saved me a lot of time :)

**Comment by wmyers** [comment]
Thanks a lot for that tip! That upgrade guide link is now a 404 and react-router's latest API docs still make reference to [context.router](https://github.com/rackt/react-router/blob/latest/docs/API.md#contextrouter)

**Comment by juanpaco** [comment]
Thanks for the help on this one.

It took me a minute to find it, but `history` and `location` are available as props on the component (e.g. `this.props.history`).
