### ISSUE TITLE
Application Plugins?

### ISSUE THREAD

**Issue by ronag** [rackt/redux#750]
Has anyone given any thoughts on how make a plugin system using redux? i.e. pluggable toolbars, panels etc...

Should one have one store and Provider for each plugin or would it be more appropriate to build a system where they somehow dynamically register/unregister their root reducers into the main applications root reducer?

**Comment by danmartinez101** [comment]
I think you'll be interested in https://github.com/rackt/redux/issues/159

**Comment by gaearon** [comment]
You might be interested in https://github.com/erikras/ducks-modular-redux.
