### ISSUE TITLE
Why subscribe again can unsubscribe?

### ISSUE THREAD

**Issue by EcutDavid** [rackt/redux#752]
When I reading the document, found code like this:    
```
let unsubscribe = store.subscribe(() =>
  console.log(store.getState())
);
unsubscribe();
```
Thought it must be wrong, so made a wrong pull request.    
https://github.com/rackt/redux/pull/751   
But the code really work, very confused.    
Thanks!

**Comment by ronag** [comment]
what is wrong?

**Comment by EcutDavid** [comment]
Nothing wrong, just confused. :(

**Comment by EcutDavid** [comment]
It seems very strange.

**Comment by jrios** [comment]
Take a look at the code. It explains in a comment what the function is doing and why it's returning a function that you can call to remove subscriptions.
 
https://github.com/rackt/redux/blob/master/src/createStore.js#L60

**Comment by EcutDavid** [comment]
Thank you @jrios ! 
It really solve my problem.   
And now I know I should read the implement code before ask question!

**Comment by EcutDavid** [comment]
@ronag Thank you too! I was confused why unsubscribe can work, and jrios give me the answer :)
