### ISSUE TITLE
Naming reducers for combineReducers

### ISSUE THREAD

**Issue by franzwong** [rackt/redux#762]
This may not be an issue actually. Is the name of the imported reference equals to the property name of "state" when I call mapStateToProps? e.g. I need to use "state.someReducers". I am still new to redux, perhaps I missed something in documentation.

```javascript
import someReducers from './someReducers';

const rootReducer = combineReducers({
  someReducers
});
```

Why don't we do it more explicit?

```javascript
import someReducers from './someReducers';

const rootReducer = combineReducers({
  items: someReducers
});
```

**Comment by timdorr** [comment]
Yes, the shape of the object passed into `combineReducers` matches the store state that those reducers will operate on. If we do `{ itemsReducers }`, that desugars to `{ itemsReducers: itemsReducers }`, which is probably not what you want. I normally do something like this:

```js
import items from './someReducers';

const rootReducer = combineReducers({
  items
});
```
Your import name can be whatever you want it to be, so you can match it to your state shape.

**Comment by gaearon** [comment]
There's a balance between being explicit in examples and showing what we believe to be best practices. We don't really want to encourage people to name reducer files `someReducers`; the convention we encourage is to match reducer name to the state field name. But then writing `{ something: something }` is redundant in ES6 so we don't do that either.
