### ISSUE TITLE
Using context to pass down handlers

### ISSUE THREAD

**Issue by ronag** [rackt/redux#765]
Is this something frowned upon?

Basically I have two actions `acquire` and `release` that basically every component needs to be able to access. Currently I'm passing it down as usual by props however it might be easier and a lot less boilerplate to pass it down through the context.

What are the general thoughts regarding `context` in the context of redux?

**Comment by dbrans** [comment]
fwiw, I've taken to using `connect` liberally to give components the state and actions they need to do their job.

**Comment by ronag** [comment]
Here is a made of example illustrating what I want to achieve. 

From the start only the `id` of every item is available and first when `load` is called will it be fetched and updated from the database until `unload` is called.

There are many issues with this way of doing things. One of which is that one has to keep passing down `load` and  `unload` through the entire hierarchy.

```

function selectItem(items, id) {
  const item = items[id]
  return {
    id,
    ...item && {
      title: item.title,
      children: item.children.map((id) => selectEvent(items, id))
    }
  }
}

const mapStateToProps = (state) =>
  selectItem(state.items, 'root')
const mapDispatchToProps = {
  load: itemActions.load,
  unload: itemActions.unload
}

@connect(mapStateToProps, mapDispatchToProps)
class TreeViewItemContainer extends Component {
  
  render() {
    return (
      <TreeViewItem {...this.props}/>
    )
  }

}

class TreeViewItem extends Component {

  componentWillMount() {
    this.props.load(this.props.id)
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.id !== this.props.id) {
      this.props.unload(this.props.id)
      this.props.load(nextProps.id)
    }
  }

  componentWillUnmount() {
    this.props.unload(this.props.id)
  }

  render() {
    const { title = 'Loading...', children = [] } = this.props
    return (
      <div>
        <div>{title}</div>
        {children.map((child) => 
          <TreeViewItem { ...child }
            load={this.props.load}
            unload={this.props.unload}/>)}
      </div>
    )
  }
}
```
