### ISSUE TITLE
Page Refresh - Getting back the old state and multiple actions

### ISSUE THREAD

**Issue by Thomsos** [rackt/redux#770]
Hello,

I am trying to make it so that when I refresh the page, I make a first action call to request the data from my server using a query string. After that, how can I make a second action call use state data received form the first call? The second action call is being executed before the first action call is completed.

How can I dispatch the second action after the state has been changed?

Note: The two action methods are being stored in different files.

**Comment by gaearon** [comment]
If you use [redux-thunk](https://github.com/gaearon/redux-thunk) and Promises, you can chain action creators.

```js
import 'babel-core/polyfill'; // for Promise
import fetch from 'isomorphic-fetch'; // for fetch

export function loadPost(postId) {
  return function (dispatch) {
    dispatch({ type: 'LOAD_POST_REQUEST, postId });
    return fetch(`http://somejson.com/posts/${postId}.json`).then(
      res => res.json()
    ).then(
      json => dispatch({ type: 'LOAD_POST_SUCCESS', json }),
      err => dispatch({ type: 'LOAD_POST_FAILURE', json })
    );
  };
}

export function loadComments(postId) {
  return function (dispatch) {
    dispatch({ type: 'LOAD_COMMENTS_REQUEST', postId });
    return fetch(`http://somejson.com/posts/${postId}/comments.json`).then(
      res => res.json()
    ).then(
      json => dispatch({ type: 'LOAD_COMMENTS_SUCCESS', json, postId }),
      err => dispatch({ type: 'LOAD_COMMENTS_ERROR', json, postId })
    );
  };
}

export function loadPostWithComments(postId) {
  return function (dispatch) {
    // You can do this at the same time:
    return Promise.all([
      dispatch(loadPost(postId)),
      dispatch(loadComments(postId))
    ]);

    // Or you could do this sequentially as you asked:
    return dispatch(loadPost(postId)).then(() =>
      dispatch(loadComments(postId))
    );
  };
}
```

**Comment by Thomsos** [comment]
Thanks!

**Comment by Thomsos** [comment]
So I have been testing this out. I have installed and added the middleware for redux-thunk, and I believe its is set up properly.

However, I am getting "Uncaught TypeError: Cannot read property 'then' of undefined" as an error message.

Any tips on why this is happening?

**Comment by svnlto** [comment]
Seems like you're missing promises:

```js
import 'babel-core/polyfill'; // for Promise
import fetch from 'isomorphic-fetch'; // for fetch
```

**Comment by Thomsos** [comment]
Alright, I have added "import 'babel-core/polyfill';". But I am getting the same result. I am using super agent to make my API calls, rather then fetch.

**Comment by gaearon** [comment]
If you're using superagent, you can't expect it to return a `Promise`, and `then()` is a method on `Promise`. You can either find a way to have superagent return Promises, use `fetch()`, or a different Promise-based library like axios.

**Comment by Thomsos** [comment]
So I have started using Axios and it is working as expected! I was wondering if anyone knew a way to implement Interceptors into redux? https://github.com/mzabriskie/axios#interceptors

**Comment by gaearon** [comment]
Can't you use them as is? Alternatively you can implement a custom Redux middleware. See `real-world` example for some custom middleware.

**Comment by Thomsos** [comment]
Not sure yet, I will try it out. Thank you for all your help!
