### ISSUE TITLE
react-router example request

### ISSUE THREAD

**Issue by eriknyk** [rackt/redux#772]
Hi,
can you add an example integrating react-router?

Best Regards.

**Comment by mazicky** [comment]
Real-world example uses react-router, and 'migrate-real-world-example-to-redux-react-router' branch uses redux-react-router as well.

**Comment by gaearon** [comment]
Yup.

https://github.com/rackt/redux/tree/master/examples/real-world
https://github.com/rackt/redux/pull/714

**Comment by eriknyk** [comment]
Thank you!
