### ISSUE TITLE
does Redux support IE8 ?

### ISSUE THREAD

**Issue by FuGardenia** [rackt/redux#774]
react support IE8 with [react-ie8](https://github.com/xcatliu/react-ie8),

does Redux support IE8 ?

**Comment by edge** [comment]
Redux intends not to support IE8.

https://github.com/rackt/redux/blob/master/webpack.config.production.js#L14

**Comment by FredyC** [comment]
Yeah, I am wondering who might need that. Developing new application to support IE8? Why? I doubt you would be adding Redux to old running application just for the fun.

**Comment by FuGardenia** [comment]
@FredyC In China， IE8 has 22.39%.   http://tongji.baidu.com/data/browser/  ， we cant abandon them

**Comment by FuGardenia** [comment]
@edge tks~ If I want to continue using Redux, what should I do ？

**Comment by FredyC** [comment]
@FuGardenia I guess you would have to make your own fork, but I am not sure how many incompatibilities are there, IE8 is really out of my interest since WinXP are gone.

**Comment by aphillipo** [comment]
Redux really doesn't do that much.  Surely if you polyfill it should be fine?  I'd be interested in hearing how you get on FuGardenia.

**Comment by gaearon** [comment]
There is no need for a fork. The `screw_ie8` line is from Webpack config, which is only relevant for UMD builds (the one on cdnjs and `dist` folder). If you use Redux from NPM as CommonJS modules, it's up to you to minify it any way you like (you get to pick Uglify settings in your own project obviously).

Redux should work fine in any browser supporting ES5. You can use [es5-shim](https://github.com/es-shims/es5-shim) to get the missing methods for really old browsers.

**Comment by FuGardenia** [comment]
@gaearon tks~  Now it is clear for me.

**Comment by tlightsky** [comment]
helpful for me too

**Comment by gggin** [comment]
helpful for me too

**Comment by gaearon** [comment]
Note that we plan to drop support for IE8 in the next major version. It is not supported neither by Microsoft nor by React anymore.
