### ISSUE TITLE
Symbols for constants

### ISSUE THREAD

**Issue by brandondewitt** [rackt/redux#779]
I like the idea of using Symbols for action types...opinions?

```
export const ADD_TODO = Symbol();
export const DELETE_TODO = Symbol();
export const EDIT_TODO = Symbol();
export const COMPLETE_TODO = Symbol();
export const COMPLETE_ALL = Symbol();
export const CLEAR_COMPLETED = Symbol();
```

**Comment by simplesmiler** [comment]
Action types should be serializable, and symbols are not.

**Comment by gaearon** [comment]
Yeah. You can do this technically but we don't encourage this because action types will disappear in the logs or if you persist them like [Redux DevTools](https://github.com/gaearon/redux-devtools) does.

**Comment by wmertens** [comment]
I've been thinking about using a little helper function that takes an array
of strings and outputs a constants object of String->String.
The twist is that for production builds, it would use the array indices as
values, String->Int.

I wonder if it will make any difference in performance though. Probably not
worth bothering.

On Wed, Sep 23, 2015, 02:34 Dan Abramov <notifications@github.com> wrote:

> Closed #779 <https://github.com/rackt/redux/issues/779>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rackt/redux/issues/779#event-416496363>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by brandondewitt** [comment]
@gaearon Thanks, I guess I would have noticed that if I were using the DevTools.  Next on my list.

**Comment by jameswomack** [comment]
@wmertens Did you mean something like this: https://www.npmjs.com/package/keykey ?

**Comment by jjwill** [comment]
@brandondewitt I was using Symbols to reduce the user-error of having action types with the same name. When it happens it can be hard to track (most times it's obvious). 

This may work if you need to keep your action types uniq:

```
function getUniqueType(name) {
  class UniqueType {
    constructor() {
      this.name = name;
    }

    toString() {
      return this.name;
    }

    toJSON() {
      return this.name;
    }    
  }
  return new UniqueType();
};
```

It there a better way to handle this?

**Comment by markerikson** [comment]
@jjwill : That's probably going to be an issue for the same reason as symbols.  See the [Redux FAQ on action type constants](http://redux.js.org/docs/faq/Actions.html#actions-string-constants) for more info.

There's a wide variety of utilities out there for generating action constants - check out the [Actions](https://github.com/markerikson/redux-ecosystem-links/blob/master/actions.md) and [Action/Reducer Generators]https://github.com/markerikson/redux-ecosystem-links/blob/master/action-reducer-generators.md) sections of my [Redux addons catalog](https://github.com/markerikson/redux-ecosystem-links) for links to libs that are out there.

**Comment by jjwill** [comment]
Thanks @markerikson I'll check those links out! The function above works for the debugging tools. We were using Symbols but after installing the debugging tools had to implement that for readability.
