### ISSUE TITLE
Is middleware needed?

### ISSUE THREAD

**Issue by ronag** [rackt/redux#781]
If the same thing can be achieved using enhancers/higher order stores I don't see why we need to confuse people with two overlapping concepts?

**Comment by gaearon** [comment]
It's a simpler tool for 80% use cases. It also has a very specific action lifecycle: middleware can either pass it on (eventually) or restart the chain.

The behavior of restarting the chain can't be accomplished by store enhancers alone—you need something holding them together, at which point we arrive at middleware again.
