### ISSUE TITLE
2 inconsistencies in docs for Universal example

### ISSUE THREAD

**Issue by pedrottimark** [rackt/redux#785]
1. Should the bulleted list have a point for Universal following Async and preceding Real World? in https://github.com/rackt/redux#examples

2. Second part of npm command refers to script which does not exist and is not needed? in http://rackt.github.io/redux/docs/introduction/Examples.html#universal

```
npm start & npm run client
```

but the scripts object in package.json for the Universal example has only start but not client (and not sure what that would mean) so should this line be just like the other examples? 

```
npm start
```

**Comment by gaearon** [comment]
Both are right. PR is welcome.
