### ISSUE TITLE
example tests

### ISSUE THREAD

**Issue by svnlto** [rackt/redux#788]
I'm looking for help in creating tests for the 'real-world' example. Could you point out of the write tests for these kind of action creators?

**Comment by gaearon** [comment]
Woah, cool, thanks for taking a look at this!
Please see https://github.com/rackt/redux/issues/546.

**Comment by svnlto** [comment]
Sure, no problem. Maybe I didn't express myself properly tho. I'm having trouble writing tests for those kind of actions creators. mind providing some pointers?

**Comment by gaearon** [comment]
Can you explain the problem more specifically? Maybe I'm missing the point as to what exactly you're looking to test.

**Comment by svnlto** [comment]
Sure. I'm attempting to write a test for https://github.com/rackt/redux/blob/master/examples/real-world/actions/index.js#L3-L17 based on the action creators test example in the docs. But when I call `actions.fetchUser(someString)` all I get back is `{}`. 

The test example in the docs makes perfect sense, It's just not clear to me how I'd write a test for an action creator that uses a "custom" middleware.

**Comment by gaearon** [comment]
Oh, that's just because it puts the middleware-specific stuff behind a symbol. You can read it the same way it is written:


```js
import { CALL_API } from '../middleware/api';
import { fetchUser } from '../actions';

expect(fetchUser('svnlto')[CALL_API].endpoint).toEqual('/users/svnlto');
```

I'm not sure how useful it is to test these things, as tests will look pretty much the same as functions themselves. These are just descriptions after all. You might want to test the middleware itself instead.

**Comment by svnlto** [comment]
> You might want to test the middleware itself instead.

Yeah, thinking about it, this would make much more sense.
