### ISSUE TITLE
How would I make a helper file that is aware of this.props?

### ISSUE THREAD

**Issue by tkiethanom** [rackt/redux#798]
In my container file I'm starting to have a generous amount of reused code that gets the hierarchy of my models to generate breadcrumbs. I want to extract this code out to another file but `this.props` will be undefined. If I pass `this.props` as a parameter it will never get updated when the state is changed.

```javascript
  dispatch(fetchTile(tileId)).then(() => {
      dispatch(fetchTiles(this.props.Tile.details.adgroup_id));

      dispatch(fetchAdGroup(this.props.Tile.details.adgroup_id)).then(() => {
        dispatch(fetchAdGroups(this.props.AdGroup.details.campaign_id));

        dispatch(fetchCampaign(this.props.AdGroup.details.campaign_id)).then(() => {
          dispatch(fetchCampaigns(this.props.Campaign.details.account_id));
          dispatch(fetchAccount(this.props.Campaign.details.account_id));
        });
      });
  });
```

**Comment by gaearon** [comment]
Seems like you want to use Redux Thunk and describe a composite action creator. It can read `getState()` at any time so the state will not be stale.

See https://github.com/gaearon/redux-thunk#composition for an example.
