### ISSUE TITLE
Duplicate actions with dispatching on componentWillReceiveProps and time-travel debugging

### ISSUE THREAD

**Issue by ryanashcraft** [rackt/redux#803]
In an application I work on, data is fetched in response to a store change, very similarly to how the `async` example works, and following the suggested pattern from issue #448. However, I've noticed with redux-devtools and time-travel debugging, there's an unfortunate consequence to this design. If you reverse actions and replay them, they can fire additional, unwanted actions that are appended to the end of the event stream. This leads to a messy event stream any time you replay actions that may cause a fetch async action.

This behavior can be reproduced by adding redux-devtools to the async example. You'll see if you revert and replay the actions, that the `fetchPostsIfNeeded` action will be called again [here](https://github.com/rackt/redux/blob/master/examples/async/containers/App.js#L22). This will append a new action to the end of the action stream.

Are actions fired from React lifecycle methods in response to store changes actually a bad pattern? If so, does anyone have any suggestions for alternatives that would not exhibit this behavior?

**Comment by ryanashcraft** [comment]
Another way to express my question – I'm not sure if this is a bad pattern for redux apps in general, or the pattern is ok and the best way to solve this issue is with some sort of change to redux-devtools.

**Comment by gaearon** [comment]
This is something I've been thinking about too. My current thinking is that it's something that can be solved in the DevTools UI. For example, if DevTools had two modes (“normal” and “loop”) and you'd opt into replaying a particular slice of actions by selecting them first, we would be able to ignore any new actions when we’re in the “loop” mode. This way it would be pure replay. Alternatively there could be a toggle switching whether new actions are handled while we’re time traveling. Currently I don’t have time to implement this, but I (or somebody else) may experiment with this later on.

**Comment by gaearon** [comment]
I'll close because I don't think it's actionable here.
DevTools redesign issue: https://github.com/gaearon/redux-devtools/issues/74
