### ISSUE TITLE
Should the "@@INIT" action ever occur more than once?

### ISSUE THREAD

**Issue by gbmhunter** [rackt/redux#811]
My reducer is receiving the "@@INIT" state more than once. I have a feeling that this shouldn't be happening. I am using Redux with a Reflux view, with nothing fancy like reloading happening.

If this is not meant to be happening, I can post more details about what is happening and the call stack.

**Comment by gaearon** [comment]
It's part of sanity checks performed by `combineReducers` to catch common mistakes.
Don't worry about it.

**Comment by gbmhunter** [comment]
Hmmm, I'm not using `comineReducers` (I was, but switched back to doing it manually after I wanted control of the root-level key names in the state object).

**Comment by gbmhunter** [comment]
Oh wow, just noticed, everytime an action is dispatched, all the previous actions occurs in sequence (with the appropriate state history) again and then the new action is the last to run. Is this something to-do with a debugging feature turned on?

**Comment by gbmhunter** [comment]
Ahhhhhh, even though I had commented out the:

````javascript
<DebugPanel top right bottom>
   <DevTools store={store} monitor={LogMonitor} />
</DebugPanel>
````

I still had:

````javascript
const finalCreateStore = compose(
  // Enables your middleware:
  applyMiddleware(thunk) // any Redux middleware, e.g. redux-thunk
  // Provides support for DevTools:
  devTools()
)(createStore);
````

which enabled dev tools and caused the state/action history to be re-run everytime.

**Comment by FredyC** [comment]
@gbmhunter Yeah, it's a known thing about devtools, they replay all the actions when new one is dispatched. There are [unit tests](https://github.com/gaearon/redux-devtools/commit/aa5ee9b6c60f4fa69f928789c70e38ed04be11fa) now so there is a chance this will get improved eventually.

**Comment by gaearon** [comment]
Yeah, this is a DevTools issue and will be fixed there.
