### ISSUE TITLE
Shopping Cart example

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#823]
I just rewrote [flux-comparison Redux example](https://github.com/voronianski/flux-comparison/tree/master/redux/js) to be idiomatic Redux: https://github.com/voronianski/flux-comparison/pull/64.

I want it to be in our repo too because it contains fairly interesting bits such as queries and denormalization—something a lot of “advanced” examples miss.

@voronianski would you be comfortable with us copying (and tweaking) that example to be in Redux repo too?

I'd imagine that moving it here would involve:

* porting to use Webpack since that's what other our examples use
* stripping down UI (no styles—a vanilla UI like in `todos-with-undo` example is fine for our purposes)
* moving the "common" components and API mocks to the example folder

If @voronianski doesn't mind, would somebody be up to do this?

**Comment by voronianski** [comment]
@gaearon I'm completely fine with it :+1:

**Comment by hedgerh** [comment]
@gaearon I can take this on.  Should I just move the common folder to `examples/common`?

**Comment by wetals** [comment]
@gaearon would be nice to include the Shopping cart in Readme docs

**Comment by omnidan** [comment]
@wetals @hedgerh feel free to add it and send a PR :smiley:

**Comment by hedgerh** [comment]
I'm on it
