### ISSUE TITLE
Best Practices for Login/Auth 

### ISSUE THREAD

**Issue by penguinsoccer** [rackt/redux#829]
So, I'm making an app right now and I've got a decent login system working, but I was wondering what exactly the best practices for the flow of it is.  

Here is my general app flow. 
  
- Action with usr and pass ->
- login api post request ->
- verify at server -> 
- send down jswebtoken with all of the info ->
- The reducer stores token in `localStorage` and decodes to the token to the store -> 
- login container has `componentWillReceiveProps` and reroutes to the main page if `loggedIn == true`

I'm pretty happy with the flow, the only real side effect is that it stores it in localStorage in the reducers which should be side effect free, but it is the best I can come up with.

So, I'm basically asking about your application login/auth flow in redux and the best practices for auth systems

**Comment by nhagen** [comment]
This generally looks fine to me except for the reducer side effect. Why not
handle that in the action creator when you call `LOGIN_SUCCESS`?

**Comment by penguinsoccer** [comment]
Thanks for the suggestion, I'm using a middleware for api calls so I wouldn't be worth writing a custom function to handle this minor side effect.

Sorry if I'm being ignorant, but isn't having a side effect in an action virtually the same as having it in a reducer.

**Comment by gaearon** [comment]
>Sorry if I'm being ignorant, but isn't having a side effect in an action virtually the same as having it in a reducer.

It isn't. We explicitly say many times in the documentation that you should never have any side effects in reducers. This is essential for [Redux DevTools](https://github.com/gaearon/redux-devtools), addons like [redux-undo](https://github.com/omnidan/redux-undo), or action record/replay.

**Comment by gaearon** [comment]
I'll close in favor of https://github.com/rackt/redux/issues/829 because it's the same question but appeared earlier.

**Comment by gaearon** [comment]
Oops, I meant https://github.com/rackt/redux/issues/826.

**Comment by penguinsoccer** [comment]
I just made the localStorage editing part of the middleware reducers are side effect free now. 

I might make an example someday...

**Comment by Kizl** [comment]
With regards to storing the token in local storage, stormpath recommends storing JWTs in a secure cookie. I'll paste a link to their reasoning & recommendation, but the tl;dr is:

> Stormpath recommends that you store your JWT in cookies for web applications, because of the additional security they provide, and the simplicity of protecting against CSRF with modern web frameworks. HTML5 Web Storage is vulnerable to XSS, has a larger attack surface area, and can impact all application users on a successful attack.

https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage/

**Comment by kienvn** [comment]
i'm looking for a login example...

**Comment by jamesmbowler** [comment]
https://github.com/mxstbr/login-flow
