### ISSUE TITLE
Considering a concise dispatch API

### ISSUE THREAD

**Issue by wizawu** [rackt/redux#833]
Is it possible to provide a API, e.g. `dispatch2`, that I can use as below

```
LoginStore.dispatch2("LOGIN", data);

function handler(state, {type, data}) { ... }

Redux.createStore(handler);
```

I think it's quite common to use these two parameters.

**Comment by gaearon** [comment]
We generally try to have one way of doing things in the core API.
If there is a `dispatch2()` that acts almost like `dispatch()` but not quite, it will cause a ton of confusion.

Also, on an unrelated note, in Redux, there is just a single store. You shouldn't have “LoginStore” and other stores—there should be just one `store`.

**Comment by gaearon** [comment]
Nothing really prevents you from adding your own `dispatch2` onto the store instance:

```js
store.dispatch2 = (type, rest) => store.dispatch({ ...rest, type });
```

The confusion added by this approach and the fact that other packages (e.g. any Redux middleware, or bindings like [React Redux](https://github.com/rackt/react-redux)) depend on the normal `dispatch()` signature is why I don't think you'll find it useful.

**Comment by wizawu** [comment]
Thanks
