### ISSUE TITLE
Database Error handling with Redux

### ISSUE THREAD

**Issue by Thomsos** [rackt/redux#837]
Hello,

I was wondering how some of you guys handle errors from the database in Redux? I am currently using Redux to call an action that uses Axio(along side Redux-Thunk and ES6 Promises) to fetch my data then dispatch it into the Redux state. From there, should the response be 500 or 401,  I want to redirect them to a certain page or show an error message. 

My first thought would be to return the response and do the logic from there, but I would like to know how other people approach this.

Thanks for all your help!

**Comment by qur2** [comment]
Hi,

I'm also thinking about something similar (my app is speaking to an different API, but in the end I also have to handle errors somehow). It's just at the stage of an idea, I'm not writing code yet: I want to try to get some action creators to actually put the errors in the store and have components connect to it (think flash messages or lightboxes).
I think this can fit nicely for global errors (service is gone, need to re-authenticate, ...). If there are more specific errors, I would think they need to be handled locally.

Hope that make sense. I'll be following the thread and see what you come up with!

**Comment by gaearon** [comment]
In `examples/real-world` in this repo, there is error handling that shows a message.
Please take a look at it.

Performing router transitions isn't different from how you'd do it normally: call the router method (or dispatch an appropriate action if you use something like [redux-router](https://github.com/rackt/redux-router)) in the AJAX callback.
