### ISSUE TITLE
Emphasize defining selectors alongside reducers in examples

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#839]
We should use selectors in our examples like we do here: https://github.com/voronianski/flux-comparison/pull/64.

Otherwise people are having a hard time how to change the state shape safely because they have to update their `mapStateToProps` all over the project.

**Comment by barock19** [comment]
@gaearon  should we start use "reselect" ?

**Comment by gaearon** [comment]
Not necessarily. I mostly mean the idea of exporting selector functions from reducer. They don't have to be powered by reselect (although it's a nice optimization).

In fact we already moved shopping cart example from Flux comparison into Redux repo, so this issue can be closed, as it adequately demonstrates the technique.
