### ISSUE TITLE
Question: Whats the difference?

### ISSUE THREAD

**Issue by scofs** [rackt/redux#843]
When defining a middleware:

```javascript
store => next => action => {
  var modifiedAction = modifyAction(action);

  // Whats the difference between:
  next(modifiedAction); // this
  store.dispatch(modifiedAction); // and this?
}
```

and when is it appropriate to use either?

**Comment by johanneslumpe** [comment]
'next' will continue the middleware chain downwards from where it is at that point and 'dispatch' will make it start at the top again.

**Comment by scofs** [comment]
Any advice or examples on when to use which?

**Comment by gaearon** [comment]
>Any advice or examples on when to use which?

If you want to “pass the action on”, use `next`. You'll see the same action in the middleware again.

If you want to “spawn a few new actions”, you may use `store.dispatch()`. The newly spawned actions will go through your middleware in this case.

The primary use case for this distinction is [redux-thunk](https://github.com/gaearon/redux-thunk). It lets use `dispatch()` things, and of course thunks should be able to dispatch other thunks. If there was no `store.dispatch()`, thunks wouldn't be able to dispatch each other.

**Comment by scofs** [comment]
I just read the docs and realized my question was already answered there.
Sorry for wasting your time.

**Comment by gaearon** [comment]
No problem!
