### ISSUE TITLE
Numerous, deeply-nested, semi-smart components and their performance

### ISSUE THREAD

**Issue by tstavinoha** [rackt/redux#846]
I'm trying to put some localization data (just a map of keys and translations) into my redux state and use it in practically any component (e.g. some input or label component).

Somehow it feels right to make components handle their own content - you wouldn't pass an input placeholder value via props in most cases, it would just sit within the component that is responsible for displaying that HTML input. Passing all translations from HOC down through every component via props seems tedious. I dont mind ditching reusability and just @connect everything I can for the sake of simplicity and encapsulation. That way the code won't be cluttered and smart stuff will be more noticeable.

However, there are two problems about this approach:
1. React complains about these deeply-nested connected objects, warning about how 'owner-based context will be replaced with parent-based context in 0.14' and there is a possibility that the following will not work. React does not know about redux, so this might just be a false-positive.
2. I'm wondering how much this would impede performance. Translations would rarely change (only on explicit user language change), but maybe a large number of 'managed' properties could be felt in application speed?

So the question is, which way to go? Is it better to handle this 'used-everywhere' state by passing it as props or connecting it?

**Comment by gaearon** [comment]
>1. React complains about these deeply-nested connected objects, warning about how 'owner-based context will be replaced with parent-based context in 0.14' and there is a possibility that the following will not work. React does not know about redux, so this might just be a false-positive.

This depends on how you render the top-level components (e.g. the router). There are numerous issues in different repositories dedicated to what this warning means, and explaining the difference between 0.13 and 0.14 handling of context, so please try to search for them. Usually, unless you're using exotic things like portals, you won't have problems migrating to 0.14. And you can try today with 0.14 RC1.

>2. I'm wondering how much this would impede performance.

I wouldn't expect performance to be an issue here.

**Comment by tstavinoha** [comment]
Thank you for answering, Dan
Keep up the good work :)

**Comment by vincentfretin** [comment]
@tstavinoha you may be interested in
[React Intl v2](https://github.com/yahoo/react-intl/issues/162) too.

**Comment by wmertens** [comment]
Regarding performance: We're using the same approach and on one of our
pages we have close to a hundred connected elements, working fine even on a
phone.

Really happy with the react-intl v2 approach btw, looks awesome, thanks for
the link!

On Sat, Oct 10, 2015, 11:20 Vincent Fretin <notifications@github.com> wrote:

> @tstavinoha <https://github.com/tstavinoha> you may be interested in
> React Intl v2 <https://github.com/yahoo/react-intl/issues/162> too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rackt/redux/issues/846#issuecomment-147068080>.
>
-- 

Wout.
(typed on mobile, excuse terseness)
