### ISSUE TITLE
Examples regarding redux-logger

### ISSUE THREAD

**Issue by gsklee** [rackt/redux#851]
Last I checked, `redux-logger` exports a `createLogger` *function* which only returns a Redux middleware upon execution. [Some of the examples](https://github.com/rackt/redux/blob/master/examples/real-world/store/configureStore.js#L14) are using `redux-logger` as if it outrightly exports a middleware which is wrong.

**Comment by gaearon** [comment]
It's not wrong per se (examples work), they're just using an older version in `package.json`.
PR to update the version and usage is welcome.
