### ISSUE TITLE
Should `combineReducers` return the same object if nothing changes?

### ISSUE THREAD

**Issue by aaronjensen** [rackt/redux#853]
Right now, the reducer returned by `combineReducers` returns a new object regardless of whether or not the reducers it is combining make any changes. This means breaking reference equal every action, which limits its usefulness when using nested combinations unless you always select all the way down to the piece of state that maintains reference equality integrity. It'd be a little bit more slow to introduce an equality check, after the `mapValues` but it seems like it'd be better, yeah?

**Comment by gaearon** [comment]
Let's add the check. Something like `hasChanged = false` which gets set to `true` if `newState[key] !== state[key]`. If `!hasChanged`, we will return the previous state.

**Comment by georgebonnr** [comment]
:100: Went through a painful process figuring out why disparate parts of my app were re-rendering.  Was about to write my own function when I figured this out, but glad I can update instead.  :+1:

**Comment by Tomassito** [comment]
@aaronjensen Can you help me understand the issue here? You're normally interested in only a part of the state that you're combining together. You'd have to have a dependency on the whole combined chunk in order to run into trouble, right? Have you got such usecase really?

**Comment by aaronjensen** [comment]
I don’t use redux anymore. This issue is 6 years old.

**Comment by aaronjensen** [comment]
I imagine I did have a use case at the time or I would not have opened an issue and submitted a patch.
