### ISSUE TITLE
Redux GitBook

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/redux#859]
Hey there,

I was trying to get a epub copy of the redux Gitbook you have at http://rackt.github.io/redux/
from https://www.gitbook.com but I could only find a copy of it in Mandarin. Could you guys publish it
on https://www.gitbook.com so that we can read it offline?

Great work guys!

**Comment by gaearon** [comment]
I think we want to keep it on GH Pages for now.
You can grab offline version here: https://github.com/paulkogel/redux-offline-docs
