### ISSUE TITLE
Update of examples for final react release 0.14.0

### ISSUE THREAD

**Issue by eriknyk** [rackt/redux#867]
some examples, by example universal still is working with react 0.13 and when it is running with react 0.14 we have the following warnings/errors:

```
Warning: Failed propType: Invalid prop `children` supplied to `Provider`, expected a single ReactElement.

With React 0.14 and later versions, you no longer need to wrap <Provider> child into a function.

Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```
would be great to have the examples up to date with the recent releases react 0.14.0

Regards.

**Comment by ocowchun** [comment]
As the [document](https://github.com/rackt/react-redux/blob/master/docs/api.md#provider-store) say:
`<Provider> accepts a function as a child with your root component. This is a temporary workaround for a React 0.13 context issue, which will be fixed when React 0.14 comes out.`

so change your code from

```js
import React from 'react';
import { Provider } from 'react-redux';

React.render(
  <Provider store={store}>
    {() => <App />}
  </Provider>,
  document.getElementById('root')
);
```


to 

```js
import React from 'react';
import ReactDOM from 'react-dom';
ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root')
);
```

**Comment by gaearon** [comment]
See https://github.com/rackt/redux/issues/864.
We'll accept PRs updating examples—no need to create issues specifically for that.

**Comment by mnpenner** [comment]
Is it not safe to use

    import * as ReactDOM from 'react/lib/ReactDOM';

?

Or should I install `react-dom` separately?

**Comment by gaearon** [comment]
Nothing inside `react/lib` is safe to use. Those are not public API.
Yes, you need to install `react-dom`.
`react/lib/ReactDOM` is temporary for backward compat and will be removed soon.
