### ISSUE TITLE
Several instances of the same widget (Have multiple instance of redux store)

### ISSUE THREAD

**Issue by bulby97** [rackt/redux#871]
I'm building a react app that can be exported as a widget and used in a iFrame. So I'm running it like this : 
```
<iframe src="http://localhost:3000/?&id=1&foo=all&bar=all"></iframe>
```

In the main website (using classic php), I want to load several of these react widgets, but to make it more sexy, I don't want to use an iFrame in the main website, but directly use those react widgets. So my react widget have two modes : iFrame mode, and data-url mode.

So I made naively something like that in my main.js : 

```javascript

import React     from 'react';
import ReactDOM  from 'react-dom';
import App      from './app.react';
import configureStore from './store';
import createBrowserHistory from 'history/lib/createBrowserHistory';

const targets = document.querySelectorAll('.my-widget');

Array.prototype.forEach.call(targets, (target) => {

    const store  = configureStore();
    const node = <App routerHistory={createBrowserHistory()} store={store} url={target.dataset.url}/>;
    ReactDOM.render(node, target);

});

```

in index.html of my Iframe: I have this : 

```
<body>
    <div class="widget"></div>
</body>

```

And in my website, I'm loading some of thoses widgets : 

```
<body>
   ...
    <div class="widget" data-url="http://localhost:3000/?&id=1&foo=all&bar=all"></div>
   ...
    <div class="widget" data-url="http://localhost:3000/?&id=1&foo=all&bar=all"></div>
   ...
   ...
   ...
    <div class="widget" data-url="http://localhost:3000/?&id=1&foo=all&bar=all"></div>
    <div class="widget" data-url="http://localhost:3000/?&id=1&foo=all&bar=all"></div>
</body>
```

As you would expect, redux is using a singleton store, so all my widgets share the same store and at any state update all widgets get updated.

What would be the best solution to this problem ?

**Comment by tracker1** [comment]
Assign a unique ID to the parent of the widget's scope, and use that to segregate your data within the single store for each id...

**Comment by bulby97** [comment]
@tracker1 Thank you. Could you be more specific ? I get the main concept but I'm having a hard time to make it concrete, could you give me an example ? Also should I rewrite pretty much everything, like actions, stores, etc ?

**Comment by gaearon** [comment]
>As you would expect, redux is using a singleton store, so all my widgets share the same store and at any state update all widgets get updated.

Why is it “using a singleton store”? If you create store per widget, then you have a store per widget.
Unfortunately I don't understand your problem. If you look at Redux source, you'll see there's no “singleton-ness” in there.

**Comment by bulby97** [comment]
@gaearon Actually you're right, thank you. I found a weird bug, I figured that widgets only "conflict" for a specific feature, and I though that was because of singleton.

I have a tree like this : 
```javascript
const initialState = {
    currentTab: 'main',
   ...
    filters: [
        {... }, {... }
   ]
```

For example if I'm changing a Tab, with 
```javascript
[c.SWITCH_TAB] : (state, action) => {
        return Object.assign({}, state, {
            currentTab: action.payload
        });
    },
```
It's ok, every widget has his own currentTab.

But when I want to change filters
```javascript
[c.FILTER_SET_ACTOR]: (state, action) => {
        return Object.assign({}, state, {
            actors: state.actors.map((actor)=>{

                action.actorsToCheck.forEach((actorToCheck) =>{
                    if (actor.label === actorToCheck.label)
                        actor.checked = actorToCheck.checked;
                });


                return actor;
            })
        });
    },
```

There is conflicts, filters of widget 2 is the same as widget 1, like if stores were updated for filters.

**Comment by bulby97** [comment]
@gaearon Here is a gif to help you understand : http://recordit.co/J1bFEl0h9W

**Comment by gaearon** [comment]
You're mutating the state:

```js
                action.actorsToCheck.forEach((actorToCheck) =>{
                    if (actor.label === actorToCheck.label)
                        actor.checked = actorToCheck.checked;
                });
```

Redux docs explicitly call out in several places *never* to do that.
Redux examples also never do that.

Instead your code should be:

```js
[c.FILTER_SET_ACTOR]: (state, action) => {
        return Object.assign({}, state, {
            actors: state.actors.map(actor => Object.assign({}, actor, {
                checked: actor.checked || action.actorsToCheck.some(a => a.label === actor.label)
            }))
        });
    },
````

**Comment by bulby97** [comment]
Damn...ù_ù thank you a lot @gaearon. I'll switch to ImmutableJS because I'm not very comfortable with Object assign. Have a good day.
