### ISSUE TITLE
Why does this work?

### ISSUE THREAD

**Issue by ericclemmons** [rackt/redux#872]
So, after literally hours of moving things around, trudging through docs, etc., I finally got this to work:

```js
const middleware = compose(
  applyMiddleware(promise, thunk),
  devTools(),
  persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/)),
);

// You may call this a finalCreateStore
const store = middleware(createStore)(reducer); // reducer is already combined up the chain
...
```

So...
- What gets `compose`d vs. `applyMiddleware`d?
- Why can't I `compose(promise, thunk, devTools(), persist(...))`?
- Why can't I `applyMiddleware(promise, thunk, devTools())`
- Why can't I do `compose(..., createStore, reducer)`?

Sorry if these are "newbie" questions, but my take was that things are either `actions`, `actionCreators`, `reducers`, or `middleware`, so I thought all of the above was middleware?

**Comment by gaearon** [comment]
DevTools is not middleware.
persistState is not middleware. 

Both are "store enhancers".
Incidentally applyMiddleware is also one.
That's why they're on the same level.


It's the opposite:

* The basic concept is "store enhancer". It's createStore => createStore.
* Store enhancers are too powerful, usually all you want is dispatch => dispatch (and have a reference to store for good measure).
* There's a store enhancer called applyMiddleware().

**Comment by gaearon** [comment]
Maybe it's easier to understand if you stop using compose(). It's just an inessential helper.

What's really happening is this:

```
let createStore = require('redux').createStore;

createStore = applyMiddleware(thunk, promise)(createStore);

createStore = devTools()(createStore);

createStore = persistState(...)(createStore);

let store = createStore(reducer);
```

**Comment by ericclemmons** [comment]
Ok, so if I understand correctly...

- middleware _can directly handle events from action creators_, which is why they get wrapped by the `applyMiddleware` "store enhancer".
- Store enhancers aren't really part of the action dispatching process/changing/handing responsibility, but are there for adding features _using_ the store?

**Comment by gaearon** [comment]
Store enhancers can do pretty much anything. For example they can wrap reducers, override any store method, or map state.

The only thing middleware does is wrap dispatch() method. It's less powerful but easier to write correctly.

Everything that middleware can do, store enhancers can do. But they're more complicated to implement so we don't talk about them much in the docs.

If all you need is wrap dispatch, write middleware. If you need more exotic things write a store enhancer.

Also check out applyMiddleware() source.

**Comment by ericclemmons** [comment]
This helps a lot.  Thanks!

Knowing these are the pieces, I ended up with something up:

```js
const store = createStoreWith(middlewares, enhancers)(reducer, initialState);
// Internally does the above, but now the terseness helps
// the team understand what goes where.
```

**Comment by gaearon** [comment]
Yeah you could do that.

One side effect is that you might want to apply middleware twice.

**Comment by gaearon** [comment]
What I meant to say is that there are cases where you want to apply some middleware, then some enhancer, and then some more middleware. For example if you want to put logger after some enhancer that generates actions you want to log.

Not saying it's a common use case but it's something that gets lost with the signature above. That's the reason we don't include such createStoreWith in the core, too.

**Comment by ericclemmons** [comment]
Ah, good explanation.  This reminds me much more of doing Koa-middleware where you `yield next` and create very special little sandwiches :)

**Comment by ericclemmons** [comment]
Another question (last one!):  if "middleware" were all just store enhancers (but only concerned themselves with the dispatch part), would it then read:

```js
compose(
  thunkEnhancer,
  promiseEnhancer,
  devTools(),
  ...
)(createStore)(reducer, initialState);
```

If that's correct, then `applyMiddleware` is really _enhancing_ `thunk` and `promise` to be a "store enhancer" like the rest of the chain...

**Comment by acdlite** [comment]
If we want to be precise about it, `applyMiddleware()` is a function whose arguments are middleware and which returns a store enhancer.

**Comment by acdlite** [comment]
So you could make a `thunkEnhancer` or `promiseEnhancer` like so:

```js
const thunkEnhancer = applyMiddleware(thunk);
const promiseEnhancer = applyMiddleware(promise);
```

**Comment by ericclemmons** [comment]
:+1:

**Comment by ericclemmons** [comment]
@acdlite I think that's clarification I (we) needed. Finally arrived to that conclusion, but   that distinction hasn't been clear.  Thanks guys!
