### ISSUE TITLE
Auto action_creators based on reducer names

### ISSUE THREAD

**Issue by hadriandeoliveira** [rackt/redux#875]
Hey guys! 
I'm learning Redux and loving it, fantastic project!!

Question:
Was reading about actions when thought of something... what do u think of this approach?: http://jsbin.com/bovuze/edit?js,console

It's a function that receives an object with reducers, then returns a function which also is a reducer (sorry about the "store" naming, gotta change it) and that also holds the action creator functions, with unique action types

I liked this for it automatically generating the action creators based on the reducers, so it's a very concise definition. But would there be any down sides? ( critique on the code also welcome :smile: )

**Comment by hadriandeoliveira** [comment]
I've got to practice naming things :laughing:

**Comment by gaearon** [comment]
There is a reason action creators are separated from reducers:

* You may have many reducers handling the same action.
* You may have reducers reacting not to action types, but to some predicates on action (e.g. does actions have `error` field).
* You may have action creators with additional logic for side effects or composition.

Please see [Reducing Boilerplate](http://rackt.github.io/redux/docs/recipes/ReducingBoilerplate.html), it explains why some things that seem like boilerplate really aren't.
