### ISSUE TITLE
Switch chat away from Reactiflux Slack

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#887]
Let's discuss in the original thread: https://github.com/rackt/react-router/issues/2250
(But keep it here for posterity)

**Comment by gaearon** [comment]
Discord it is?
https://github.com/reactiflux/volunteers/issues/25#issuecomment-147538522

**Comment by timdorr** [comment]
It certainly seems to be the top contender.

There's a channel under the rackt "server" here: https://discord.gg/0ZlaQ0Nx6oNlpp6p

**Comment by gaearon** [comment]
Closed via https://github.com/rackt/redux/commit/e59c185b55462ef49df128753c545b9aacafc416.
