### ISSUE TITLE
Proposal: move docs to redux.js.org

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#890]
There are two problems:

1. The official doc URL is kinda long (http://rackt.github.io/redux)
2. There is http://reduxjs.com which is unofficial and hosts outdated docs

I'd like to see both of these problems solved by moving to a free [.js.org](https://dns.js.org/) domain for the docs. That would be `redux.js.org`.

Ideally I'd like to see http://reduxjs.com (which is currently owned by @demohi, as per https://github.com/camsong/redux-in-chinese/issues/1#issue-101240158) redirect to the official docs. I understand the noble effort of Chinese translation, but a much more complete Chinese translation is available at http://camsong.github.io/redux-in-chinese/, and at this point http://reduxjs.com only confuses beginners who find outdated docs in Google and assume they are official.

@demohi Can I count on your help with this? We'd really appreciate setting up a redirect instead. I can prepare a PR to redirect every page, if you'd like.

Thoughts?

-----------------

- [x] Establish http://redux.js.org
- [x] Make sure it doesn't go away on next `npm run docs:publish`
- [ ] Redirect from http://rackt.github.io/redux/* to appropriate pages on redux.js.org
- [ ] Redirect from http://reduxjs.com/* to appropriate pages on redux.js.org
- [ ] Update links

**Comment by gaearon** [comment]
cc @mjackson @ryanflorence — we probably should have some common way of doing that at rackt.
I like `stuff.js.org` over `rackt.github.io/stuff`.

**Comment by mjackson** [comment]
Feel free to do this with redux and let us know how it goes. I wasn't actually aware that js.org was a thing until now. I'm still waiting for the .js TLD to be registered so I can claim react-router.js ;P

For now, we don't actually have a website for the router. We were focusing so hard on closing issues and getting the API right that we decided to let the site go until the 1.0 dust settles.

If you want to standardize on something, I'd like to standardize on the general structure of the `docs` directory and the format of the files therein. If we standardize on that, it will make it a lot easier for us to build sites for all rackt projects later from the same tool.

**Comment by knowbody** [comment]
I didn't know .js was a thing. I think that's a good idea Dan! You know that I really like the way Redux docs are structured and what is in there. Up for helping with that

**Comment by demohi** [comment]
@gaearon  I'm sorry for the problems. I forgot to update this site. I can redirect http://reduxjs.com to http://rackt.github.io/redux (with your help pr). 

@camsong I can redirect http://cn.reduxjs.com to http://camsong.github.io/redux-in-chinese/

What do you think?

**Comment by camsong** [comment]
@demohi Really appreciate for doing that.

**Comment by demohi** [comment]
I configed the domain dns and added a PR

#892   @gaearon 

https://github.com/camsong/redux-in-chinese/pull/37  @camsong

**Comment by gaearon** [comment]
Hi @demohi!
Thank you for such a quick response!

Rather than make `reduxjs.com` a permanent home for Redux docs, I want to:

* Move our docs to `redux.js.org`
* Set up redirect for every page on `reduxjs.com` to the corresponding `redux.js.org` page

I'll proceed with step (1) first, and after that's done, I'll let you know and we'll figure out how to do (2).

**Comment by timdorr** [comment]
This is great! Here are the instructions for doing it: https://github.com/js-org/dns.js.org

I'll get some PRs in place so you can just click some buttons to make it happen :smile:

**Comment by indus** [comment]
Hi - I´m the maintainer of JS.ORG. If you have any questions... oh you made a PR just in this moment ;-)

**Comment by timdorr** [comment]
@indus Yep, I updated everything so we can make this happen. Thanks for joining in!

**Comment by indus** [comment]
While waiting for the CNAME and this issue is still open you maybe want to discuss the [free SSL](https://github.com/js-org/dns.js.org/blob/master/cnames_active.js#L17-L21) opt-in. JS.ORG is using it for its own pages and some other libraries too ([https://riotgear.js.org](https://riotgear.js.org),[https://frzr.js.org/](https://frzr.js.org/)). May be handy in terms of SEO?!?

**Comment by timdorr** [comment]
Ah, that's neat. I think that certainly wouldn't hurt us. I can submit a PR for it once we're sure everything is in place with the base setup.

**Comment by gaearon** [comment]
I added todo checklist to the first post.

**Comment by timdorr** [comment]
Note that the github.io redirect will happen with the CNAME file in place automatically, so I'll check that one off.

**Comment by indus** [comment]
The is one last thing I wanted to mention (maybe a bit to much know, and maybe to late). I have seen that you are having a lot of repositories under the organisation "rackt".
If you want all your projects become available under a single domain you can set it up like the following:

bind the JS.ORG subdomain (like "rackt.js.org") to to a Organisation repo named "rackt.github.io" (use the master branch for the page content as described [here](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages))

then you have a landing-page: ```rackt.js.org```
and all your projects will become available under:
- ```rackt.js.org/react-modal```
- ```rackt.js.org/redux-router```
- ...
(exactly like they are now available under ```rackt.github.io/react-modal```` only ```github.io``` gets replaced by ```js.org```. Thats of course also possible with "redux" - but not both).
But keep in mind that if you use such a organisation approach, links will brake (not like now, where you have requested for a project page where old URL still works).

Thats all! Think about adding note about the "JS.ORG badge" to you chacklist. Have fun!

**Comment by timdorr** [comment]
Rackt itself doesn't have a website and the org is really only there to put some high quality React modules under the same roof. So, having individual subdomains for each project is probably the best approach here.

**Comment by indus** [comment]
I see!

**Comment by mjackson** [comment]
I bought rackt.org the other day. Not sure if we wanna use it.

@gaearon redux.rackt.org?

**Comment by gaearon** [comment]
I think I'd go for a simpler (`redux.js.org`) name because that's what people are going to google when they have a problem.

I'd say `rackt` is more about how it's being developed, and <project name> is what the released product it. That's what you see on NPM, and I think that's what you should see in domain name.

**Comment by gaearon** [comment]
@timdorr 

How come both `rackt.github.io/redux` and `redux.js.org` work at the same time? Is it always going to be this way? Do you know how GH pages handle this?

I want to set up 301 redirects instead so we don't split the google juice..

**Comment by timdorr** [comment]
I don't know. [The documentation says it should](https://help.github.com/articles/adding-a-cname-file-to-your-repository/#example-of-a-real-world-cname-file), but it doesn't appear to be working. Maybe it only works at the user/org level and not the repo level? That's kind of a bummer :disappointed:

**Comment by indus** [comment]
@timdorr yes thats the way it works. Only user/organisation pages have an automatic redirect. project pages stay reachable with the original URL.

**Comment by timdorr** [comment]
Ah, bananas. Well, I'm not sure of a good way to handle it. Outside of a rackt.org server that 301's over to redux.js.org.

**Comment by gaearon** [comment]
>Outside of a rackt.org server that 301's over to redux.js.org.

Seems like a viable option to me. (That's what I do with http://gaearon.github.io/redux btw.) We'd also need to create a separate repo for hosting Redux (e.g. `reduxjs.github.io`) and change the build script to put it there instead of `gh-pages` branch I suppose.

**Comment by timdorr** [comment]
Welp, @mjackson just set up the DNS stuff, so it's at http://rackt.org/redux/ now. The redux.js.org domain does not redirect, at least. To fix it, either you would have to move redux to its own org or we would have to host rackt.org somewhere with a server that can be configured to 301 redirect. 

I can set up the JS redirection page, but that's not going to carry over the Google link juice. That's up to you if that's important. I think most people will start updating links and Google will play catch up soon enough. FWIW, I still see the npm page as the top result for "redux". The docs aren't anywhere on the first page...

**Comment by demohi** [comment]
@gaearon  I think maybe there are too many domains for the docs。Can I use the reduxjs.com for the Chinese Doc Site(I will add the English Version Link in the index page )?

**Comment by gaearon** [comment]
@demohi Maybe it's better to do something like `cn.redux.js.org`?

**Comment by gaearon** [comment]
There's also http://camsong.github.io/redux-in-chinese/, do you want to join efforts with them?

**Comment by camsong** [comment]
@gaearon @demohi We(I plus 13 other contributors) are trying to find if there is a way to let http://camsong.github.io/redux-in-chinese/ merge back to the official redux community, especial for the consistency of  domain url. `cn.redux.js.org` looks good for me

**Comment by gaearon** [comment]
I have no idea about domain name management.
@timdorr Is this something we could do while keeping it in a separate repo?

**Comment by timdorr** [comment]
You can only have one CNAME file per gh-pages branch. You could go the other way on the URL: http://redux.js.org/cn/ (or more with the locale code of /zh-cn/)

**Comment by timdorr** [comment]
I think this is mostly working. James Kyle is working on the internationalization stuff in other issues, so keep track there.

**Comment by indus** [comment]
@camsong when it is just about the URL: It would be a pleasure for me to provide you "cn.redux.js.org". But as @timdorr pointed out, there is only one CNAME possible per repository. So this would make a merge impossible (Sorry for beeing 3 month late ;-)

**Comment by camsong** [comment]
thanks @indus  #551
