### ISSUE TITLE
bindActionCreators causes re-render

### ISSUE THREAD

**Issue by ccorcos** [rackt/redux#899]
If you're using bindActionCreators in the render function, you're returning a new function every time

https://github.com/rackt/redux/blob/master/src/utils/bindActionCreators.js#L4

This means that the component will necessarily re-render every time because the new function doesnt referentially equal the old function...

**Comment by gaearon** [comment]
Yes, and this is expected.
You're supposed to cache the result if you care about this.
React Redux, for example, caches it.
