### ISSUE TITLE
Docs: should ./actions be ./actionCreators

### ISSUE THREAD

**Issue by appsforartists** [rackt/redux#904]
In the [Actions docs](http://rackt.github.io/redux/docs/basics/Actions.html):

> Action creators are exactly that—functions that create actions. It's easy to conflate the terms “action” and “action creator,” so do your best to use the proper term.

In keeping consistent with that, should `actions.js` be called `actionCreators.js`?

(This may be more bikeshedding, ala #377)

**Comment by gaearon** [comment]
We try to always use the proper term in docs, but we make concessions for things you type most often.
In this case, we use the shorter file names and prop names in examples—but not the API or docs.
I think it's a fine balance, and from my experience answering the questions people don't find it confusing.
