### ISSUE TITLE
How to organise global objects configured by state?

### ISSUE THREAD

**Issue by fobdy** [rackt/redux#924]
Suppose i have some global object (in terms of `OOP`) that i need to be configured by some state value, for example:

```javascript
let backend = new Backend(getState().backend.host)
```

Later in some action creators or even in reducers i may have to access this global one...
What is the best way to achieve this?

I don't want to instantiate these objects everytime with getState.

it comes down to the question how to organise interaction and object sharing (not values, but OOP ones) between some different parts (modules) of application. Do i need some additional framework or i have to think different in the pure functional and immutable world?

**Comment by gaearon** [comment]
I don't get it. `Backend` depends on the initial value of `getState()`? What happens when the state changes? Does this object need to be re-created?

**Comment by fobdy** [comment]
`Backend` is configured asynchronously and only once after app has loaded. So other parts of the app depends on that condition. Вообще мне на русском было бы проще писать :(

**Comment by gaearon** [comment]
What exactly is the problem?
You can create this object once and then export it from a module that you can import from other modules.

**Comment by fobdy** [comment]
Отвечу пока на русском, потом переведу тогда ;) Загрузка конфига асинхронна и объект должен инициализироваться после загрузки. Соответственно конфиг ничего не знает о бекенде, это отдельная функциональность, поэтому actionCreator загрузки конфига не может внутри себя ничего конфигурить. Остается 2 варианта: реагировать на сообщение о готовности загрузки и там создавать глобальный `Backend` (в рамках модуля) - но так делать нельзя, тк reducerы не должны вносить side-effect. И остается единственный вариант, это там где я вызываю actionCreator загрузки конфига, на промис навесить создание `Backend`. Выглядит это не очень, тк казалось бы если система построена на сообщениях, то это как-то через них и должно решаться. Есть еще один вариант через редьюсеры - это класть сами объекты в стейт и использовать его как глобальный обменник объектов, но это не очень красиво тоже.

**Comment by gaearon** [comment]
I still don't understand :-(
Maybe you can provide a minimal runnable example showing the dilemma?
It doesn't have to *work*—just to show what exactly `Backend` is used for and how it's created.

**Comment by fobdy** [comment]
Here it is https://gist.github.com/fobdy/d5aa4771ffbe03d3f741

**Comment by winstonewert** [comment]
Why don't you want to rebuild Backend each time you need it? Is it because of performance, or is it semantically necessary?

**Comment by timdorr** [comment]
Unless you're going to use that configuration in other parts of your application, I wouldn't use Redux for this. It's not application logic you are managing here, just setuo/configuration. It would sort of be like trying to use redux to control webpack. Possible, but silly :smile:
