### ISSUE TITLE
Routing in real world example does not update URL

### ISSUE THREAD

**Issue by alexjg** [rackt/redux#926]
I've just checked out master and built the real world example and found that the URL is not updating when changing which login the "Explore" box is pointing at. Reloading the app with a login in the URL works fine. I ran into this because I'm experiencing a similar bug in an application I am building where the URL is not updating and I was hoping for an example of how to fix it. Any idea what I'm missing?

**Comment by gaearon** [comment]
Can you provide the exact steps to reproduce the issue?
Just in case, try killing `examples/real-world/node_modules`, running `npm install` there and try again?

**Comment by alexjg** [comment]
Okay, it seems this only happens when running through the webpack dev server.

```
cd examples/real-world
npm install
webpack-dev-server --config webpack.config.js
open localhost:8080/webpack-dev-server/
```

Entering "alexjg" in the explore text entry shows my repositories but doesn't update the URL. However, if I directly `open localhost:8080` and enter "alexjg" the URL is updated. I guess this might actually not be solvable given that webpack runs the app inside an iframe. Do people generally not use `/webpack-dev-server/*`?

**Comment by alexjg** [comment]
Okay, this was because I wasn't using the webpack inline mode. The lack of URL updates in iframe mode being well documented in the webpack documentation. My bad.

**Comment by gaearon** [comment]
Oh, we just assume you run `npm start`.
