### ISSUE TITLE
What is the correct way to go about reducers?

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/redux#929]
So I recently began using redux in an application I'm making, learning as I go. I came across a situation where I saw the way the redux documentation structured the reducer:
```javascript
function posts(state = {
  isFetching: false,
  didInvalidate: false,
  items: []
}, action) {
  switch (action.type) {
  case INVALIDATE_REDDIT:
    return Object.assign({}, state, {
      didInvalidate: true
    });
  case REQUEST_POSTS:
    return Object.assign({}, state, {
      isFetching: true,
      didInvalidate: false
    });
  case RECEIVE_POSTS:
    return Object.assign({}, state, {
      isFetching: false,
      didInvalidate: false,
      items: action.posts,
      lastUpdated: action.receivedAt
    });
  default:
    return state;
  }
}
```
My concern with this is that the new state that is being generated all the logic is mixed up in there.
I later saw an article where they abstracted the logic into separate reducers then plugged the functions into the switch statement:
```javascript
// These are the functions that contain the logic
export function setEntries(state, entries) {
  const list = List(entries);
  return state.set('entries', list)
              .set('initialEntries', list);
}

export function next(state, round = state.getIn(['vote', 'round'], 0)) {
  const entries = state.get('entries')
                       .concat(getWinners(state.get('vote')));
  if (entries.size === 1) {
    return state.remove('vote')
                .remove('entries')
                .set('winner', entries.first());
  } else {
    return state.merge({
      vote: Map({
        round: round + 1,
        pair: entries.take(2)
      }),
      entries: entries.skip(2)
    });
  }
}
...

// This is the switch statement where the reducers are plugged into the cases
import {setEntries, next, restart, vote, INITIAL_STATE} from './core';

export default function reducer(state = INITIAL_STATE, action) {
  switch (action.type) {
  case 'SET_ENTRIES':
    return setEntries(state, action.entries);
  case 'NEXT':
    return next(state);
  case 'RESTART':
    return restart(state);
  case 'VOTE':
    return state.update('vote',
                        voteState => vote(voteState, action.entry, action.clientId));
  }
  return state;
}

```

I am wondering which way I should go and why, but another thing I noticed was that the actionCreators from the article have the same name would that be an issue?

**Comment by elithrar** [comment]
It's ultimately up to you - you can also use [`combineReducers()`](http://rackt.org/redux/docs/api/combineReducers.html) to split them entirely, with each reducer handling a single part of the state (i.e. rather than a big switch - just each listening for 1-2 actions each).

**Comment by kennetpostigo** [comment]
Well isn't that combine reducer for the switch statements that contain the reducers? As in you have reducers that only deal with a certain task and you place those inside a switch that only handles that one target area. Then use the `combineReducers()` to combine the switch statements of that specific area with others?

**Comment by gaearon** [comment]
Sorry, I don't understand the question. :-/

>My concern with this is that the new state that is being generated all the logic is mixed up in there.

Can you expand on that?

**Comment by kennetpostigo** [comment]
Like the logic within the switch statements, the instructions for how to handle the action to proceed to the next state:

```javascript 
case REQUEST_POSTS:
// This logic for how to handle the action
//Here its nice and simple but in some cases it may get more complicated.
    return Object.assign({}, state, {
      isFetching: true,
      didInvalidate: false
    });
```
To this:
```javascript 
case REQUEST_POSTS:
// Here the logic is abstracted away into a function in a separate file
    return requestPosts(state);
```
So what Im trying to get at is whether its a good idea to place the logic in a separate file and the plug it in like I showed previously. I also wonder if the logic is placed in a separate file does the function have to also contain `(previousState, action) => newState` or if it just requires `(previousState) => newState` since the reducer that wraps around the switch handles the action?

I just want to say again that I'm using redux for the first time, sorry if I am confusing you guys.

**Comment by gaearon** [comment]
>So what Im trying to get at is whether its a good idea to place the logic in a separate file and the plug it in like I showed previously.

Sure, it's fine. Reducer is just a function. How you structure it and whether you split it into many and call other functions is completely up to you.

>I also wonder if the logic is placed in a separate file does the function have to also contain (previousState, action) => newState or if it just requires (previousState) => newState since the reducer that wraps around the switch handles the action?

Again, up to you. Whatever looks natural in your code.
