### ISSUE TITLE
integrate npm package in todomvc

### ISSUE THREAD

**Issue by js08** [rackt/redux#936]
Hi,

Is it possible to integrate this package depcheck-es6 in our example app through webpack, since I would like to check unused dependencies through automate process.
https://www.npmjs.com/package/depcheck-es6

Can you tell where I should make changes its confusing
https://github.com/rackt/redux/blob/master/examples/todomvc/webpack.config.js

They have given an API code too

API

Want to call depcheck from code? See the example:

var path = require('path');
var depcheck = require('depcheck-es6');

var options = {
  withoutDev: false, // check against devDependencies
  ignoreBinPackage: false, // ignore the packages with bin entry
  ignoreDirs: [ // folder with these names will be ignored
    'sandbox',
    'dist',
    'bower_components'
  ],
  ignoreMatches: [ // ignore dependencies that matches these globs
    'grunt-*'
  ],
  parsers: { // the target parsers
    '*.js': depcheck.parser.es6,
    '*.jsx': depcheck.parser.jsx
  },
  detectors: [ // the target detectors
    depcheck.detector.requireCallExpression,
    depcheck.detector.importDeclaration
  ],
  specials: [ // the target special parsers
    depcheck.special.eslint,
    depcheck.special.webpack
  ]
};

depcheck('/path/to/your/project', options, function(unused) {
  console.log(unused.dependencies); // an array containing the unused dependencies
  console.log(unused.devDependencies); // an array containing the unused devDependencies
  console.log(unused.invalidFiles); // files that cannot access or parse
  console.log(unused.invalidDirs); // directories that cannot access
});

**Comment by gaearon** [comment]
This is the issue tracker of Redux.
It's not a support forum for Webpack.
Your question is specifically about Webpack, and should be asked on StackOverflow, or Webpack discussion forums.
