### ISSUE TITLE
Call unsubscribe many times will remove other listeners

### ISSUE THREAD

**Issue by jzlxiaohei** [rackt/redux#938]
I write a test

    const store = createStore(reducers.todos);
    const listenerA = expect.createSpy(() => {});
    const listenerB = expect.createSpy(() => {});

    let unsubscribeA = store.subscribe(listenerA);
    store.subscribe(listenerB);

    unsubscribeA();
    unsubscribeA();//invoke two times

    store.dispatch(unknownAction());
    expect(listenerA.calls.length).toBe(0);
    expect(listenerB.calls.length).toBe(1); // failed

reason:
   
   `arr.splice(-1,1)` still remove the item of the arr.

//createStore.js  
   
    function subscribe(listener) {
        listeners.push(listener);

        return function unsubscribe() {
          var index = listeners.indexOf(listener);
          // if index ===1 ,should return
          listeners.splice(index, 1);
        };
  }

**Comment by gaearon** [comment]
Fixed in #939 and b7031ce3acb23b6ecadbd977b1cfa32486447904.
Out in 3.0.4.
Thanks.
