### ISSUE TITLE
How many containers and state should I have in a real world big application?

### ISSUE THREAD

**Issue by CrisLi** [rackt/redux#940]
I am new to the ```redux```, but I like it very much. The single store is really awesome for SPA. But I have a question for a real world big application.

For example, if there is a membership management application. We have login page, member management page and accounting page. Should I have 3 ```states``` for each page? If I still have one single state, my concern is the ```state``` is going to huge.
Should I have 3 containers for each page? If we need a new page, such as AddMember page. Should I add a new container?

I have checked the examples provided in the source code. Most of them are only for a small SPA. Is there a big application scaffold?

**Comment by gaearon** [comment]
Please ask this on StackOverflow.
Recently we've been trying to keep the issue tracker for issues and discussions, not questions.
