### ISSUE TITLE
State mutation in the documentation example on splitting reducers

### ISSUE THREAD

**Issue by danillouz** [rackt/redux#950]
While reading the documentation (basics section on reducers, 2.2) the examples note that state mutation is not allowed in reducers and therefore `Object.assign()` is used:

```
case SET_VISIBILITY_FILTER:
    return Object.assign({}, state, {
      visibilityFilter: action.filter
    });
```

However when illustrating reducer composition, it seems like state is mutated:

```
function visibilityFilter(state = SHOW_ALL, action) {
  switch (action.type) {
  case SET_VISIBILITY_FILTER:
    return action.filter;
  default:
    return state;
  }
}
```

This confused me a bit. Am I missing something (I'm still new to redux), or is this a mistake in the documentation? I would really appreciate some clarification.

**Comment by johanneslumpe** [comment]
It returns a new state, which is the value of `action.filter`. The state value here is just a string, which you cannot mutate. Mutation can happen with objects and arrays, which are passed by reference. The scalar values are passed by value, not by reference.

**Comment by danillouz** [comment]
Thanks for your answer, but why use `Object.assign()` in the first example?

**Comment by johanneslumpe** [comment]
In order to return a new object, so you can use a referential integrity check (`===`) to determine whether the state has changed. If you were to mutate the props, you would have to do a deep-compare to figure out if something has changed.

**Comment by danillouz** [comment]
I see, thank you for taking the time explaining it to me!

**Comment by johanneslumpe** [comment]
Sure, not a problem!
