### ISSUE TITLE
Are there any major downsides to creating a redux store for testing?

### ISSUE THREAD

**Issue by penguinsoccer** [rackt/redux#954]
Let's say I've got a counter application, I could just create the "fake" store in one file. And import it to my tests.

```javascript
FakeStore.js
CounterTests.js

// in CounterTests

import Store from './FakeStore'

let expected = {
count: 2
}
Store.dispatch(counterAdd())
expect(expected).to.eql(CounterSelector(Store.getState()))

```

To me it seems that with this approach and a localhost server running you can test every part of your redux logic and the only untested part would be the components and containers.

**Comment by gaearon** [comment]
Please ask usage questions on StackOverflow. The `counter` and `todomvc` examples in the `examples` folder show how to test different parts of Redux apps. I'm not sure what's being asked specifically here.
