### ISSUE TITLE
Constructor syntax needs to be changed..

### ISSUE THREAD

**Issue by vmc29** [rackt/redux#955]
Hi,

Have found issue with constructor syntax which we used in todomvc app, while running depcheck-es6.

https://github.com/rackt/redux/blob/master/examples/todomvc/server.js#L06

hope this will be the proper syntax.
 new (require('express'))();

you can check it out here : https://github.com/lijunle/depcheck-es6/issues/91

Thanks

**Comment by gaearon** [comment]
Closed by #979, thanks for reporting.
