### ISSUE TITLE
Provide an Example with UNIVERSAL APP + React Router (redux-router)

### ISSUE THREAD

**Issue by eriknyk** [rackt/redux#957]
Hi, I was trying to make merged example with the examples/universal + examples/real-world
but I got some unexpected troubles,.. and browsig with the web I found differents approach about
howto implement it, but for each implementation I found some hack, and others not clear implementations,.. 
I wish that you can provide an example as the right way to implement
an redux app + universal + react-router/redux-router .

Best Regards.

**Comment by gaearon** [comment]
I agree this would be nice.
However personally I don't have time to contribute it.
Router is also changing a lot so it's better to wait until 1.0 before working on this.

Regardless, this is currently not actionable for us, so I'm closing. When RR 1.0 comes out we can revisit, but in any case, we'd need somebody to volunteer to create an example.
