### ISSUE TITLE
Disable currently processing UI element

### ISSUE THREAD

**Issue by alexfedoseev** [rackt/redux#963]
Sorry if it's a dup, but I haven't found anything on subject.

In my UI I have form for editing some `dummy` entity. This entity has 2 boolean attributes: `attrOne`, `attrTwo` — in terms of UI it's 2 checkboxes. When user clicks on one of the checkboxes, request goes to the server to update entity's attribute. Until the response, checkbox must be disabled. So the question is what's preferred way of implementing it in redux app.

My first thought is to use global state to store the status of each attribute. Something like this: 

```js
// dummyActionCreator
export function updateEntity(entityId, attr, value) {
  return dispatch => {
    dispatch({
      type: actionTypes.ENTITY_UPDATE_REQUESTED,
      entityId,
      attr,
      value,
    });
    return apiCall({
      method: 'PATCH',
      url: apiPaths.entityPath(entityId),
      data: { [attr]: value },
    })
      .then(() => {
        dispatch({
          type: actionTypes.ENTITY_UPDATE_SUCCEED,
          entityId,
          attr,
          value,
        });
      })
      .catch(res => /* handle... */);
  };
}

// dummyState
{
  entities: { [entityId]: { /* entity */ } },
  isProcessing: {
    [entityId]: {
      attrOne: true / false,
      attrTwo: true / false,
    }
  }
}

// dummyReducer
case actionTypes.ENTITY_UPDATE_REQUESTED: {
  return state.setIn(['isProcessing', entityId, attr], true);
}
case actionTypes.ENTITY_UPDATE_SUCCEED: {
  return state.setIn(['isProcessing', entityId, attr], false);
}

// dummyComponent
<input type="checkbox" disabled={state.get('isProcessing').get(entityId).get(attr)} />
```

But I'm not sure it's a right way to go. Appreciate any advices / thoughts / comments on this. Thanks!

**Comment by mindjuice** [comment]
Seems reasonable to me.  You definitely want to keep the state that controls whether it is disabled or not in your app state, and not locally in the component.

One thing I might do differently is instead of having the ``disabled`` attribute of the ``<input>`` tag be based on ``isProcessing``, I would probably make a more generic ``isDisabled`` state (still using your ``entityId`` and ``attr`` bits), as there could be other reasons you might want to disable a control.

You could have your existing reducers for ``ENTITY_UPDATE_XXX`` set the ``isDisabled`` flag too, but that unnecessarily couples them.

Instead, you could dispatch a second action and have the reducer for that set the flag.  You might also want to batch those dispatches too as described here:

    https://github.com/tshelburne/redux-batched-actions

**Comment by alexfedoseev** [comment]
@mindjuice Thanks for feedback! :+1:

**Comment by gaearon** [comment]
>You could have your existing reducers for ENTITY_UPDATE_XXX set the isDisabled flag too, but that unnecessarily couples them.

I'm not sure about coupling.
I think it's pretty reasonable.

One action is enough—if you need `isDisabled` to depend on other things, you might want to keep `{ isFetching: bool, isDoingSomethingElseLol: bool, isDoingSomethingElseYetHaha: bool }` in the state, all triggered by different actions, and `isDisabled` will be a *calculation* over them calculated in the view (a selector).

This is exactly how we disable “Load More” button while it's fetching a page in `examples/real-world`.

**Comment by faergeek** [comment]
What about using `undefined` value when you load something? `null` stands for "no value", `undefined` stands for "undefined state" (i.e. in the middle of data loading or something like that).

**Comment by gaearon** [comment]
>What about using undefined value when you load something? null stands for "no value", undefined stands for "undefined state" (i.e. in the middle of data loading or something like that).

Yeah, how you store your state is up to you.
