### ISSUE TITLE
Connecting multiple components in a component ownership hierarchy, is it advisable?

### ISSUE THREAD

**Issue by jpierson** [rackt/redux#966]
I'm just starting out with React and Redux and am questioning one of my first implementations in which I connect redux to a root component but for some high level components that sit right under the router I would rather make these smart components as well. Is it advisable or even intended to have multiple components within a single path in the component ownership hierarchy connected directly via a call to _connect_? Perhaps it is what is intended but for some reason it feels wrong to me like I'm overwriting some inherited context.

**Comment by gaearon** [comment]
Yes, having multiple connected components is fine.
#419
