### ISSUE TITLE
Best way to design a Class which contains some isomorphic code ?

### ISSUE THREAD

**Issue by vieks** [rackt/redux#967]
I create a class "Locale" to manage i18n. I need it on the client and server side.
Some methods must work everywhere whilst others are specific to a side.
For instance:
On server a "load" method to find a language resource locally.
On the client side, a "fetch" method to make HTTP req for new lang template or a "translate" method to handle pluralization case.

What do you think is the best way to design it ?

-> With 2 separeted Locale class files, one for each side.
-> With an inheritance ? Where shared code base goes to the parent and specific code for each side on 2 children classes.
-> With a more 'isomorphic' approach' like this:

```javascript
export default class Locale{
  /* 
    shared code base 
  */
}

if(__SERVER__){
   Locale.prototype.load = function(){};
}else{
 //client
 Locale.prototype.fetch = function(){};
 Locale.prototype.translate = function(){};
}
```

Where static constants will be dead code eliminated on prod.

What approach you advice ?

Thanks in advance.

**Comment by gaearon** [comment]
This does not appear Redux-specific.
Please ask usage and general questions on StackOverflow.

**Comment by vieks** [comment]
Ok sorry but finally no need I found a elegant declarative solution with decorators.
