### ISSUE TITLE
combineReducers with no reducers passed

### ISSUE THREAD

**Issue by andrewrothman** [rackt/redux#968]
Is it possible for combineReducers to produce a valid output instead of an error without any reducers passed to it?

I'm currently working on a new project and I want to get a basic setup without any reducers (as there is currently no data, I'm just hooking in Redux to a mocked-up HTML page) and I thought calling this with no reducers would produce an empty reducer.

Instead I got this error message:

    Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.

Can we make an exception for when an object is passed that is empty? Maybe there's something I'm missing, and this is a bit of an edge case, but I wanted to get some thoughts before maybe hacking on this.

**Comment by andrewrothman** [comment]
I was able to add this to my application code to make it work:

    const rootReducer = combineReducers({
      blank: function(state, action) {if (state == null) state = [] return state;}
    });

While this got things working perfectly, I think it would be a minor improvement to have it work with no errors without having to define a blank reducer.

**Comment by nhagen** [comment]
There is no need to call `combineReducers` if you are not going to pass in any reducers. It just returns a simple reducer, not a special type of reducer. Any place where you would use `combineReducers`, you can just use and identity function `state => state`

**Comment by gaearon** [comment]
```js
const store = createStore(state => state);
```

**Comment by gaearon** [comment]
In fact even no-op will work because the sanity checks are only done in `combineReducers()`.

```js
const store = createStore(() => {});
```

**Comment by andrewrothman** [comment]
Oh I see. That makes sense. Thank you.

**Comment by eddskt** [comment]
for old composeWithDevTools and Thunk users:

`const store = createStore(() => composeWithDevTools(applyMiddleware(thunk.withExtraArgument())));`

**Comment by markerikson** [comment]
@eddskt not sure why you left this on an issue that's over 8 years old :)

note that [we _really_ don't want people using `createStore` directly today](https://redux.js.org/introduction/why-rtk-is-redux-today), and instead [you _should_ be using RTK's `configureStore`](https://redux.js.org/usage/migrating-to-modern-redux#store-setup-with-configurestore).

In this case, you could do:

```ts
const store = configureStore({
  reducer: {}
})
```
