### ISSUE TITLE
Using conditions in reducer when updating specific object

### ISSUE THREAD

**Issue by kudlajz** [rackt/redux#976]
I have a following snippet of code:
```
const defaultState = {
	traded: {
		activeColumn: 'update',
		order: 'DESC'
	},
	perspective: {
		activeColumn: 'created',
		order: 'DESC'
	}
};

function gridReduce(state, action) {
	switch (action.type) {
		case GridActions.GRID_SELECT_COLUMN:
			return Object.assign({}, ...state, {
				activeColumn: action.column,
				order: action.order
			});
		default:
			return state;
	}
}

export default function (state = defaultState, action = {}) {
	let newState = {};
	for (let grid in state) {
		if (state.hasOwnProperty(grid)) {
			if (action.grid === grid) {
				newState[grid] = Object.assign({}, gridReduce(state[grid], action));
			} else {
				newState[grid] = Object.assign({}, state[grid]);
			}
		}
	}

	return newState;
}
```

and my question is: Is it okay to have that condition in my reducer, if I want to change only one object in the state?

Obviously, without the condition, all my objects get updated, which is not desired result.

**Comment by gaearon** [comment]
Don't pass objects from state in actions if possible. It's almost always an anti pattern.

Pass the *information* to identify the appropriate object. For example you can keep "grids" by ID and pass an ID in the action. Then you won't need a for loop.

**Comment by kudlajz** [comment]
I am passing only grid's key not the entire object. So should I return the
entire state by default and when SELECT_COLUMN occurs, Object.assign
current state and change only the desired grid's state?

**Comment by gaearon** [comment]
Oh, good point, I always forget how `for ... in` works!
I'd write it like this then:

```js
export default function (state = defaultState, action = {}) {
    return Object.assign({}, state, {
        [action.grid]: gridReduce(state[grid], action)
    });
}
```

using ES6 computed property syntax.

Or even like this (with object spread operator proposed for ES7):

```js
export default function (state = defaultState, action = {}) {
    return {
        ...state,
        [action.grid]: gridReduce(state[grid], action)
    };
}
```
