### ISSUE TITLE
No mention of Provider children change in release notes

### ISSUE THREAD

**Issue by kumar303** [rackt/redux#987]
I just upgraded from redux 2.0.0 to 3.0.4 (and upgraded to react 0.14 at the same time) but I did not see any mention of the breaking change for how to use `<Provider/>` in the [release notes](https://github.com/rackt/redux/releases). Maybe it's worth adding retroactively? Or is there another migration/upgrade guide that I missed?

I found the answer only by Googling because I didn't understand the error message. For completeness, here are the details:

I got an error (yes it broke my app) like "Failed propType: Invalid prop `children` supplied to `Provider`, expected a single ReactElement."

I had to change this:
````
  <Provider store={dataStore}>
    {() => <App/>}
  </Provider>
````
to this:
````
  <Provider store={dataStore}>
    <App/>
  </Provider>
````
I did the scan the examples in the docs to try and figure out if there was a new way to use `Provider` but I guess it was such a subtle change that I missed it.

**Comment by dbrans** [comment]
@kumar303 Provider comes from [react-redux](https://github.com/rackt/react-redux). It's in the [release-notes](https://github.com/rackt/react-redux/releases).

**Comment by gaearon** [comment]
Yep, it's from a different project which is upgraded separately.
https://github.com/rackt/react-redux/releases/tag/v4.0.0

**Comment by kumar303** [comment]
d'oh! Totally knew that. *facepalm*
