### ISSUE TITLE
Confusion on comparison about "reducers" vs. "stores" in Flux

### ISSUE THREAD

**Issue by chiefGui** [rackt/redux#995]
Hey guys!

Reading your documentation, very well written by the way, I noticed that you wrote a thing that gives a chance for a misunderstood.

At [Prior Art's Flux Section](https://github.com/rackt/redux/blob/master/docs/introduction/PriorArt.md#flux), you have the following content:

> Redux prescribes that you concentrate your model update logic in a certain layer of your application (“stores” in Flux, “reducers” in Redux).

When zooming this quote, we can see: 

> (“stores” in Flux, “reducers” in Redux)

And here is our pitfall.

In the same documentation, a little bit further, when [covering the basics](http://redux.js.org/docs/basics/index.html), you have two different, decoupled topics:

- [Reducers](http://redux.js.org/docs/basics/Reducers.html)
- [Stores](http://redux.js.org/docs/basics/Store.html)

I got confused when I started reading the Stores. _Hey! Aren't they the same?_ Then I gone through the topic to make sure you did make a reference on what you've said earlier and, for my surprise, _you mentioned nothing_.

To have better comprehension about my thought, at first I was expecting that reducers were occupying the same role as stores on Flux. That I was supposed to not see stores on Redux, _but this isn't real and your analogy emphasized this conceptual mistake_.

By the bye, this is not a big deal at all. The comparison you did first just relies on technical equality about Flux's Store and Redux's reducers—yes, they perform the same role here and there—, but I am pretty sure you can improve the comparison to _avoid_ others to think the same as I, that just understood better after thinking and rethinking about what was written in both places.

Unfortunately I didn't think in something that could replace the sentence. It is supposed to be minimal and straight forward—so I wasn't able to think in something on the same fashion.

Am I a bad interpreter? Am I wrong somewhere? I didn't open a pull request because this subject is worthy to be discussable.

**Comment by faergeek** [comment]
There's no 'Stores', but one 'Store', it's an object which holds you application state, reducers handle partial updates of it.

In Flux there are multiple stores and multiple places with update logic, Redux just abstracts some things away, by using single state tree and passing parts through reducers, that's pretty much it actually, aside from immutability.

**Comment by gaearon** [comment]
The document you link to isn't called “Stores”. It's called “Store” because that's what it describes — a single store in Redux.

A store doesn't contain logic in Redux because it isn't written by the user. It is provided by Redux. So yes, we have a store, but it's not something you write, it's something you *use*.

>To have better comprehension about my thought, at first I was expecting that reducers were occupying the same role as stores on Flux. 

That's exactly the case. In Flux, you describe update logic in Stores. In Redux, you describe update logic in reducers.

>but I am pretty sure you can improve the comparison to avoid others to think the same as I, that just understood better after thinking and rethinking about what was written in both places.

I'm happy to merge a PR that makes this more clear.
I think it's best to discuss this in terms of specific changes though, so I'll close this issue.
The best way to start a discussion around this is to propose specific changes. :wink:
