### ISSUE TITLE
sauce variable in documentation

### ISSUE THREAD

**Issue by barrystaes** [rackt/redux#996]
I am looking into Redux documentation. I got confused by the example code at [Example: Using Thunk Middleware for Async Actions](http://rackt.org/redux/docs/api/applyMiddleware.html#example-using-thunk-middleware-for-async-actions) because it seems the variable `sauce` magically exists in this context, but i dont understand where it comes from.

Is `sauce` a variable that `fetch()` in `fetchSecretSauce()` aught to return or create in scope/context?

	function makeASandwichWithSecretSauce(forPerson) {

	  // Invert control!
	  // Return a function that accepts `dispatch` so we can dispatch later.
	  // Thunk middleware knows how to turn thunk async actions into actions.

	  return function (dispatch) {
		return fetchSecretSauce().then(
		  sauce => dispatch(makeASandwich(forPerson, sauce)),                       // <-------
		  error => dispatch(apologize('The Sandwich Shop', forPerson, error))
		)
	  }
	}

**Comment by mist123** [comment]
```javascript
sauce => dispatch(makeASandwich(forPerson, sauce))
```
Is an anonymouse function with `sauce` as a param.
The same without es6 arrow functions:
```javascript
function makeASandwichWithSecretSauce(forPerson) {

  // Invert control!
  // Return a function that accepts `dispatch` so we can dispatch later.
  // Thunk middleware knows how to turn thunk async actions into actions.

  return function (dispatch) {
    return fetchSecretSauce().then(
      function (sauce) {
        return dispatch(makeASandwich(forPerson, sauce));
      },
      function (error) {
        return dispatch(apologize('The Sandwich Shop', forPerson, error));
      }
    )
  }
}
```

**Comment by gaearon** [comment]
Yep.

**Comment by barrystaes** [comment]
Ok i feel stupid now, i apparently expected the resulting `sauce` anonymous function to get called in this example. (its not, right?) I did not know of a dual parameter `.then()` and i must have interpreted that as a PHP keyed array or something.
