### ISSUE TITLE
Simulate 2-way data binding

### ISSUE THREAD

**Issue by andreisoare** [rackt/redux#998]
Is there an easy way to simulate 2-way data binding?

For example: Component A has an input box. As the user types in it, a field in an object is updated. That object is rendered in Component B as well, so the field should update in real time as the user types.

The only solution I can think of is to listen for each key pressed and trigger a redux action that generates a new store, but generating a new store for each key pressed seems excessive.

**Comment by gaearon** [comment]
>The only solution I can think of is to listen for each key pressed and trigger a redux action that generates a new store, but generating a new store for each key pressed seems excessive.

What do you mean by “generates a new store”? The store is a single object. Every time you dispatch an action, a *new state* object is generated which I presume is what you meant.

In this case, it may be excessive (and then you can forgo Redux and do this via React state model—find a common parent and let it hold the state). *Or* you can use Redux like you described, and fire an action on every keypress. To be honest I don't think it's a big deal—for example, this is exactly how [Redux Form](http://erikras.github.io/redux-form) works. You may have performance issues with giant forms, so always profile for your use case first.

**Comment by andreisoare** [comment]
I meant to say generating new state objects, sorry. Thank you for the answer!

**Comment by dbrans** [comment]
@andreisoare have a look at [redux-form](https://github.com/erikras/redux-form). I believe it handles updating a store on keypress.

**Comment by dbrans** [comment]
... though it might be overkill for what you need.
